### ISSUE TITLE
Error when using SGLang rollout

### ISSUE THREAD

**Issue by yujianll** [volcengine/verl#1049]
Hi, I get this error when using SGLang for rollout.
```
(WorkerDict pid=2199833) [2025-04-12 21:11:01 TP0] Scheduler hit an exception: Traceback (most recent call last):
(WorkerDict pid=2199833)   File "/proj/long-multi/midi/miniforge3/envs/exp_t/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 1999, in run_scheduler_process
(WorkerDict pid=2199833)     scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
(WorkerDict pid=2199833)   File "/proj/long-multi/midi/miniforge3/envs/exp_t/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 249, in __init__
(WorkerDict pid=2199833)     self.tp_worker = TpWorkerClass(
(WorkerDict pid=2199833)   File "/proj/long-multi/midi/miniforge3/envs/exp_t/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in __init__
(WorkerDict pid=2199833)     self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
(WorkerDict pid=2199833)   File "/proj/long-multi/midi/miniforge3/envs/exp_t/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 74, in __init__
(WorkerDict pid=2199833)     self.model_runner = ModelRunner(
(WorkerDict pid=2199833)   File "/proj/long-multi/midi/miniforge3/envs/exp_t/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 174, in __init__
(WorkerDict pid=2199833)     min_per_gpu_memory = self.init_torch_distributed()
(WorkerDict pid=2199833)   File "/proj/long-multi/midi/miniforge3/envs/exp_t/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 316, in init_torch_distributed
(WorkerDict pid=2199833)     before_avail_memory = get_available_gpu_memory(self.device, self.gpu_id)
(WorkerDict pid=2199833)   File "/proj/long-multi/midi/miniforge3/envs/exp_t/lib/python3.10/site-packages/sglang/srt/utils.py", line 277, in get_available_gpu_memory
(WorkerDict pid=2199833)     free_gpu_memory, _ = torch.cuda.mem_get_info(gpu_id)
(WorkerDict pid=2199833)   File "/proj/long-multi/midi/miniforge3/envs/exp_t/lib/python3.10/site-packages/torch/cuda/memory.py", line 712, in mem_get_info
(WorkerDict pid=2199833)     return torch.cuda.cudart().cudaMemGetInfo(device)
(WorkerDict pid=2199833) RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
(WorkerDict pid=2199833) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

However, the same script runs well on the same machine when using vllm. I wonder what could be the possible reasons for this error. Thanks!

**Comment by zhaochenyang20** [comment]
try to launch SGLang separately?  https://docs.sglang.ai/backend/send_request.html to check wehter this in sglang or in verl-engine.

**Comment by yujianll** [comment]
@zhaochenyang20 Thanks for the reply.
I can launch SGLang separately with ` python -m sglang.launch_server --model-path Qwen/Qwen2-7B-Instruct --tp 2`.
But I get the above error when running the verl script.
I cloned the most recent verl and installed it with `pip3 install -e .[sglang]`

**Comment by zhaochenyang20** [comment]
Thanks. We will find a way to fix this.

**Comment by zhaochenyang20** [comment]
cc @ocss884 could you help to take a look? thanks!

**Comment by ocss884** [comment]
Thank you for reporting! I'm looking into it.

**Comment by tjoymeed** [comment]
@yujianll  @ocss884 Have you solved the problem? I got the same problem. 
I just did the DAPO with vllm without any problem and then when I  deactivate out my venv_vllm and then source into my venv_sglang, I got this error.

RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable 

From nvidia-smi it seems that all the devices are idle.

What's wrong?

I used the docker image: whatcanyousee/verl:ngc-cu124-vllm0.8.3-sglang0.4.5-mcore0.12.0-te2.2

**Comment by yujianll** [comment]
@tjoymeed No, I still have the problem. Have you resolved it?

**Comment by zhaochenyang20** [comment]
quite strange. We can not reproduce this

**Comment by eranhirs** [comment]
This issue seems related to the use of multiprocessing.

I tried running `torch.cuda.mem_get_info(0)` outside of the `run_scheduler_process` and it works:

```
            print(torch.cuda.mem_get_info(0))
            data = scheduler_pipe_readers[i].recv()
```
(see https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/entrypoints/engine.py#L805C1-L805C52)

Then I tried running right after `run_scheduler_process` starts and I got this error
```
Process Process-1:
Traceback (most recent call last):
  File ".../multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File ".../multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File ".../site-packages/sglang/srt/managers/scheduler.py", line 2274, in run_scheduler_process
    print(torch.cuda.mem_get_info(0))
  File ".../site-packages/torch/cuda/memory.py", line 738, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
``` 

Note 1: in both cases, `torch.cuda.is_initialized` returns True
Note 2: Running `python3 -m sglang.launch_server --model-path qwen/qwen2.5-0.5b-instruct --host 0.0.0.0` does not throw this error


=========

Edit: I am pretty sure it's related to the fact that the `EXCLUSIVE_PROCESS` is turned on for my node, combined with the use of multiprocessing as mentioned above.

**Comment by gpsbhargav** [comment]
I'm facing the same problem. Is there a fix or a workaround?

**Comment by MYC000801** [comment]
facing the same problem with verl v0.5.0 and v0.4.1.

**Comment by MYC000801** [comment]
Follow-up: it seems the problem does not exist when GPU mode is Default, but happens when GPU mode is Exclusive_Process. 

Although found this out, I still can’t make it work… I don’t have access to change GPU mode to Default. Any idea for this?

**Comment by gpsbhargav** [comment]
My GPUs are running in the exclusive process mode too. Why is it a problem for SGLang and not for vLLM? Is there an option to run SGLang on k out of N GPUs and use the remaining N-k for non-rollout processes?

**Comment by MYC000801** [comment]
Compared vllm_rollout.py and sglang_rollout.py — sglang uses multiprocessing while vllm does not. I suspect this is the reason.

**Comment by gpsbhargav** [comment]
If you're on a cluster with schedulers such as LSF or SLURM, you can specify things like `mode=exclusive_process` and `mps=yes` while submitting the job. I could get sglang to work this way.

References:
- https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=o-gpu
- https://www.sherlock.stanford.edu/docs/user-guide/gpu/#gpu-compute-modes

**Comment by MYC000801** [comment]
> If you're on a cluster with schedulers such as LSF or SLURM, you can specify things like `mode=exclusive_process` and `mps=yes` while submitting the job. I could get sglang to work this way.
> 
> References:
> 
> * https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=o-gpu
> * https://www.sherlock.stanford.edu/docs/user-guide/gpu/#gpu-compute-modes

It works!!! Just setup mps then sglang works! Thanks a lot for your help!

`export CUDA_MPS_PIPE_DIRECTORY=/tmp/$USER/mps-pipe `
`export CUDA_MPS_LOG_DIRECTORY=/tmp/$USER/mps-log`
`nvidia-cuda-mps-control -d`

**Comment by Kirrito-k423** [comment]
定时清理检查结果：这个 issue 最近一次由当前运行账号以外账号产生的公开回复或公开引用是 `2025-08-08T18:09:58Z`。本轮检查日期为 2026-07-04，该时间已经超过 6 个月。检查来源包括 issue comments API `https://api.github.com/repos/verl-project/verl/issues/1049/comments?per_page=100` 和 timeline API `https://api.github.com/repos/verl-project/verl/issues/1049/timeline?per_page=100`。

按照本仓库的定时 issue 清理标准，我会先留下这条说明并关闭该 issue。若作者或社区成员仍能提供新的复现、证据或需求背景，请继续评论请求重开，或创建新的 issue 并引用这里的上下文。

---

Scheduled cleanup check: the latest public reply or public reference from an account other than the current automation account was `2025-08-08T18:09:58Z`. The check date for this run is 2026-07-04, so that activity is more than 6 months old. The checked public sources were the issue comments API `https://api.github.com/repos/verl-project/verl/issues/1049/comments?per_page=100` and the timeline API `https://api.github.com/repos/verl-project/verl/issues/1049/timeline?per_page=100`.

Following the scheduled issue cleanup policy, I am leaving this note first and then closing the issue. If the author or community can still provide a fresh reproduction, evidence, or requirement context, please comment to request reopening or open a new issue that links back to this one.

This response was generated by a scheduled Codex GPT5.5 issue processing task.
