### ISSUE TITLE
(Solved) running error on AMD Mi300:

### ISSUE THREAD

**Issue by Alan-Qin** [volcengine/verl#1485]
When I used the default rocm docker to run experiments on MI300 cluster, I met the below error:

-------------------

Memory access fault by GPU node-4 (Agent handle: 0xb26d7b0) on address 0x7f2900ffc000. Reason: Unknown

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/scratch/amlt_code/verl/trainer/main_ppo.py", line 246, in <module>
    main()
  File "/usr/local/lib/python3.12/dist-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.12/dist-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/usr/local/lib/python3.12/dist-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/usr/local/lib/python3.12/dist-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/usr/local/lib/python3.12/dist-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.12/dist-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/amlt_code/verl/trainer/main_ppo.py", line 64, in main
    run_ppo(config)
  File "/scratch/amlt_code/verl/trainer/main_ppo.py", line 76, in run_ppo
    ray.get(runner.run.remote(config))
  File "/usr/local/lib/python3.12/dist-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 2755, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 906, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ActorDiedError): [36mray::TaskRunner.run()[39m (pid=7724, ip=100.64.198.149, actor_id=89c0e36413389f369ec9cbd101000000, repr=<main_ppo.TaskRunner object at 0x7f152fcd7dd0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/amlt_code/verl/trainer/main_ppo.py", line 183, in run
    trainer.fit()
  File "/scratch/amlt_code/verl/trainer/ppo/ray_trainer.py", line 908, in fit
    gen_batch_output = self.actor_rollout_wg.generate_sequences(gen_batch)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/amlt_code/verl/single_controller/ray/base.py", line 49, in func
    output = ray.get(output)
             ^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
	class_name: create_colocated_worker_cls.<locals>.WorkerDict
	actor_id: 998350f339fdd6b977376f2001000000
	pid: 8967
	name: t8kHKQWorkerDict_0:3
	namespace: 945aa7b0-2462-469a-8b5b-b0b544b9e4df
	ip: 100.64.198.149
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
[36m(WorkerDict pid=8777)[0m /usr/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown

-----------------------

Could you please help me figure out this issue?

**Comment by yushengsu-thu** [comment]
@Alan-Qin  Could you please share more details such as 
1. Training script
2. Environmental setting (are you also using the Dockerfile.rocm to build docker and run within it)?

**Comment by Alan-Qin** [comment]
Hi yusheng,

I have fixed this issue with reference: https://github.com/vllm-project/vllm/issues/2988

Thanks for your help!

PS:
**Will you be providing updated ROCm-compatible Docker images for vLLM (version 0.8.~)?**

Thanks!

**Comment by yushengsu-thu** [comment]
@Alan-Qin  Hello, actually, vllm-0.8+ still has some issues on ROCm. We are waiting for this PR to be merged. After this PR is merged, we will prepare the release the Docker with `vllm-0.8+` version.

Btw, @Alan-Qin , might I know which vllm version you are currently use now :D

**Comment by Alan-Qin** [comment]
My current vllm version is 0.6.3+rocm634. @yushengsu-thu
