### ISSUE TITLE
CUDA error: an illegal memory access was encountered for 32B 4 node training

### ISSUE THREAD

**Issue by edchengg** [volcengine/verl#184]
I got this error when I was running 32B 4-node GRPO training script.
The training runs fine for 12 steps and crashed after it.

- vllm==0.6.3
- xformers==0.0.27.post2
- transformers==4.47.1
- torch==2.4.0
- python==3.9.0
- nvidia-cublas-cu12        12.1.3.1                 
- nvidia-cuda-cupti-cu12    12.1.105                 
- nvidia-cuda-nvrtc-cu12    12.1.105                 
- nvidia-cuda-runtime-cu12  12.1.105               
- nvidia-cudnn-cu12         9.1.0.70                 
- nvidia-cufft-cu12         11.0.2.54                
- nvidia-curand-cu12        10.3.2.106           
- nvidia-cusolver-cu12      11.4.5.107           
- nvidia-cusparse-cu12      12.1.0.106         
- nvidia-ml-py              12.560.30                
- nvidia-nccl-cu12          2.20.5                  
- nvidia-nvjitlink-cu12     12.6.85               
- nvidia-nvtx-cu12          12.1.105              

script i used:

```


export VLLM_ATTENTION_BACKEND=XFORMERS
DIR=""

math_train_path=$DIR/data/math/train.parquet
math_test_path=$DIR/data/math/test.parquet


train_files="['$math_train_path']"
test_files="['$math_test_path']"

echo "[Node ${SLURM_NODEID}] Launching Python training script"
python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=512 \
    data.val_batch_size=1312 \
    data.max_prompt_length=1000 \
    data.max_response_length=5000 \
    actor_rollout_ref.model.path=Qwen/Qwen2.5-32B \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=24000 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.grad_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.tensor_model_parallel_size=4 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name='grpo' \
    trainer.experiment_name='32b_grpo_math500' \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=4 \
    trainer.save_freq=10 \
    trainer.test_freq=10 \
    trainer.total_epochs=15 $@
```
error:
```
[36m(WorkerDict pid=3175143, ip=10.49.193.113)[0m Fatal Python error: Aborted
[36m(WorkerDict pid=3175143, ip=10.49.193.113)[0m
[36m(WorkerDict pid=3175143, ip=10.49.193.113)[0m miniconda3/envs/verl/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
[36m(WorkerDict pid=3175143, ip=10.49.193.113)[0m   warnings.warn('resource_tracker: There appear to be %d '
Traceback (most recent call last):
 File "/verl/verl/trainer/main_ppo.py", line 153, in main
   run_ppo(config)
 File "/verl/verl/trainer/main_ppo.py", line 163, in run_ppo
   ray.get(main_task.remote(config, compute_score))
 File "miniconda3/envs/verl/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
   return fn(*args, **kwargs)
 File "miniconda3/envs/verl/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
   return func(*args, **kwargs)
 File "miniconda3/envs/verl/lib/python3.9/site-packages/ray/_private/worker.py", line 2772, in get
   values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
 File "miniconda3/envs/verl/lib/python3.9/site-packages/ray/_private/worker.py", line 919, in get_objects
   raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::main_task()[39m (pid=3131056, ip=10.49.195.199)
 File "/verl/verl/trainer/main_ppo.py", line 249, in main_task
   trainer.fit()
 File "/verl/verl/trainer/ppo/ray_trainer.py", line 652, in fit
   gen_batch_output = self.actor_rollout_wg.generate_sequences(gen_batch)
 File "/verl/verl/single_controller/ray/base.py", line 42, in func
   output = ray.get(output)
ray.exceptions.RayTaskError(RuntimeError): [36mray::WorkerDict.actor_rollout_generate_sequences()[39m (pid=3175143, ip=10.49.193.113, actor_id=b5a506360c00880da9f130fd01000000, repr=<verl.single_controller.ray.base.WorkerDict object at 0x1521e2b1d340>)
 File "miniconda3/envs/verl/lib/python3.9/site-packages/vllm/worker/model_runner.py", line 1708, in execute_model
   output: SamplerOutput = self.model.sample(
 File "miniconda3/envs/verl/lib/python3.9/site-packages/vllm/model_executor/models/qwen2.py", line 433, in sample
   next_tokens = self.sampler(logits, sampling_metadata)
 File "miniconda3/envs/verl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
   return self._call_impl(*args, **kwargs)
 File "miniconda3/envs/verl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
   return forward_call(*args, **kwargs)
 File "miniconda3/envs/verl/lib/python3.9/site-packages/vllm/model_executor/layers/sampler.py", line 274, in forward
   maybe_deferred_sample_results, maybe_sampled_tokens_tensor = _sample(
 File "miniconda3/envs/verl/lib/python3.9/site-packages/vllm/model_executor/layers/sampler.py", line 878, in _sample
   return _sample_with_torch(
 File "miniconda3/envs/verl/lib/python3.9/site-packages/vllm/model_executor/layers/sampler.py", line 847, in _sample_with_torch
   return get_pythonized_sample_results(
 File "miniconda3/envs/verl/lib/python3.9/site-packages/vllm/model_executor/layers/sampler.py", line 713, in get_pythonized_sample_results
   sample_results = _random_sample(seq_groups,
 File "miniconda3/envs/verl/lib/python3.9/site-packages/vllm/model_executor/layers/sampler.py", line 512, in _random_sample
   random_samples = random_samples.cpu()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.




The above exception was the direct cause of the following exception:


[36mray::WorkerDict.actor_rollout_generate_sequences()[39m (pid=3175143, ip=10.49.193.113, actor_id=b5a506360c00880da9f130fd01000000, repr=<verl.single_controller.ray.base.WorkerDict object at 0x1521e2b1d340>)
 File "/verl/verl/workers/fsdp_workers.py", line 462, in generate_sequences
   output = self.rollout.generate_sequences(prompts=prompts)
 File "miniconda3/envs/verl/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
   return func(*args, **kwargs)
 File "/verl/verl/workers/rollout/vllm_rollout/vllm_rollout.py", line 184, in generate_sequences
   output = self.inference_engine.generate(
 File "miniconda3/envs/verl/lib/python3.9/site-packages/vllm/utils.py", line 1063, in inner
   return fn(*args, **kwargs)
 File "miniconda3/envs/verl/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 353, in generate
   outputs = self._run_engine(use_tqdm=use_tqdm)
 File "/verl/verl/third_party/vllm/vllm_v_0_6_3/llm.py", line 161, in _run_engine
   outputs = super()._run_engine(use_tqdm=use_tqdm)
 File "miniconda3/envs/verl/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 879, in _run_engine
   step_outputs = self.llm_engine.step()
 File "miniconda3/envs/verl/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 1386, in step
   outputs = self.model_executor.execute_model(
 File "/verl/verl/third_party/vllm/vllm_v_0_6_3/spmd_gpu_executor.py", line 163, in execute_model
   all_outputs = self.worker.execute_model(execute_model_req=execute_model_req)
 File "/verl/verl/third_party/vllm/vllm_v_0_6_3/worker.py", line 267, in execute_model
   return self.model_runner.execute_model(
 File "miniconda3/envs/verl/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
   return func(*args, **kwargs)
 File "miniconda3/envs/verl/lib/python3.9/site-packages/vllm/worker/model_runner_base.py", line 146, in _wrapper
   raise type(err)(f"Error in model execution: "
RuntimeError: Error in model execution: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.




During handling of the above exception, another exception occurred:


[36mray::WorkerDict.actor_rollout_generate_sequences()[39m (pid=3175143, ip=10.49.193.113, actor_id=b5a506360c00880da9f130fd01000000, repr=<verl.single_controller.ray.base.WorkerDict object at 0x1521e2b1d340>)
 File "/verl/verl/single_controller/ray/base.py", line 399, in func
   return getattr(self.worker_dict[key], name)(*args, **kwargs)
 File "/verl/verl/single_controller/base/decorator.py", line 404, in inner
   return func(*args, **kwargs)
 File "/verl/verl/workers/fsdp_workers.py", line 466, in generate_sequences
   output = self.rollout_sharding_manager.postprocess_data(output)
 File "/verl/verl/workers/sharding_manager/fsdp_vllm.py", line 105, in __exit__
   torch.cuda.empty_cache()
 File "miniconda3/envs/verl/lib/python3.9/site-packages/torch/cuda/memory.py", line 170, in empty_cache
   torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


```

**Comment by eric-haibin-lin** [comment]
@youkaichao how to debug vllm problems like this?

**Comment by danielz02** [comment]
I had the same problem as you. In my case, `export VLLM_ATTENTION_BACKEND=XFORMERS` does not actually pass this environment variable to the worker because I started the Ray cluster separately.

https://github.com/volcengine/verl/blob/3fe77fa75b1d50b1ffd70149dd53b84e9bd59a6e/verl/trainer/main_ppo.py#L104

https://github.com/volcengine/verl/blob/3fe77fa75b1d50b1ffd70149dd53b84e9bd59a6e/verl/single_controller/ray/base.py#L253

Alternatively, setting those environment variables when doing `ray start` should also work.

**Comment by ocss884** [comment]
Met the exact same problem, in my case it occurred after 2 steps

vllm==0.6.3
xformers==0.0.27.post2
transformers==4.47.1
torch==2.4.0
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==12.560.30
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.1.105
nvidia-nvtx-cu12==12.1.105

script:
```python
python3 -m verl.trainer.main_ppo \
    data.train_files=$DATA_DIR/train.parquet \
    data.val_files=$DATA_DIR/test.parquet \
    data.train_batch_size=256 \
    data.val_batch_size=1312 \
    data.max_prompt_length=512 \
    data.max_response_length=256 \
    actor_rollout_ref.model.path=Qwen/Qwen2.5-0.5B-Instruct \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=256 \
    actor_rollout_ref.actor.ppo_micro_batch_size=16 \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.grad_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=16 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=16 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    critic.optim.lr=1e-5 \
    critic.model.use_remove_padding=True \
    critic.model.path=Qwen/Qwen2.5-0.5B-Instruct \
    critic.model.enable_gradient_checkpointing=False \
    critic.ppo_micro_batch_size=16 \
    critic.model.fsdp_config.param_offload=False \
    critic.model.fsdp_config.grad_offload=False \
    critic.model.fsdp_config.optimizer_offload=False \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.logger=['console'] \
    +trainer.val_before_train=False \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.save_freq=10 \
    trainer.test_freq=10 \
    trainer.total_epochs=15 2>&1 | tee verl_demo.log
```

**Comment by edchengg** [comment]
> I had the same problem as you. In my case, `export VLLM_ATTENTION_BACKEND=XFORMERS` did not actually pass this environment variable to the worker because the environment variable was not set when I started the Ray cluster separately.
> 
> [verl/verl/trainer/main_ppo.py](https://github.com/volcengine/verl/blob/3fe77fa75b1d50b1ffd70149dd53b84e9bd59a6e/verl/trainer/main_ppo.py#L104)
> 
> Line 104 in [3fe77fa](/volcengine/verl/commit/3fe77fa75b1d50b1ffd70149dd53b84e9bd59a6e)
> 
>  ray.init(runtime_env={'env_vars': {'TOKENIZERS_PARALLELISM': 'true', 'NCCL_DEBUG': 'WARN'}}) 
> [verl/verl/single_controller/ray/base.py](https://github.com/volcengine/verl/blob/3fe77fa75b1d50b1ffd70149dd53b84e9bd59a6e/verl/single_controller/ray/base.py#L253)
> 
> Line 253 in [3fe77fa](/volcengine/verl/commit/3fe77fa75b1d50b1ffd70149dd53b84e9bd59a6e)
> 
>  ray_cls_with_init.update_options({'runtime_env': {'env_vars': env_vars}, 'name': name}) 
> Alternatively, setting those environment variables when doing `ray start` should also work.

Thank you for your help.
After setting the 
export VLLM_ATTENTION_BACKEND=XFORMERS
before ray start command
it works fine now.

**Comment by uygnef** [comment]
this script works for me
```
source activate /opt/miniconda3/envs/verl
pip install -U "ray[data,train,tune,serve]"
MODEL_PATH=/nfs/ofs-llm-ssd/models/Qwen2.5-7B
export VLLM_ATTENTION_BACKEND=XFORMERS
output_dir=/models/Qwen2.5-7B-grpo-verl

if [[ ! -z "$DISTRIBUTED_TASK_ROLE" ]] && [[ "$DISTRIBUTED_TASK_ROLE" == "master" ]];then
  DISTRIBUTED_NODE_RANK_TMP=$VC_TASK_INDEX
  echo "master, node_rank: $DISTRIBUTED_NODE_RANK_TMP"
  ray start --head --port=$PET_MASTER_PORT
  echo "ray start master in port: $PET_MASTER_PORT"

  ray job submit --address="http://127.0.0.1:8265" \
   -- python -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=data/kk/instruct/3ppl \
    data.val_files=data/kk/instruct/3ppl \
    data.train_batch_size=16 \
    data.val_batch_size=16 \
    data.max_prompt_length=400 \
    data.max_response_length=2048 \
    actor_rollout_ref.model.path=$MODEL_PATH\
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=512 \
    actor_rollout_ref.actor.ppo_micro_batch_size=64 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.grad_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=160 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=16 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=160 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.critic_warmup=0 \
    trainer.logger=['wandb'] \
    trainer.project_name='GRPO_logic_KK' \
    trainer.experiment_name='Qwen-7B' \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=2 \
    trainer.default_local_dir=$output_dir \
    trainer.default_hdfs_dir=null \
    trainer.save_freq=50 \
    trainer.test_freq=50 \
    trainer.total_epochs=5
else
  DISTRIBUTED_NODE_RANK_TMP=$(($VC_TASK_INDEX+1))
  echo "worker, node_rank:$DISTRIBUTED_NODE_RANK_TMP"
  ray start --address="$VC_MASTER_HOSTS:$PET_MASTER_PORT"
  echo "ray start worker join master $VC_MASTER_HOSTS:$PET_MASTER_PORT"
  sleep infinity
fi
```

**Comment by Jiahao004** [comment]
> > I had the same problem as you. In my case, `export VLLM_ATTENTION_BACKEND=XFORMERS` did not actually pass this environment variable to the worker because the environment variable was not set when I started the Ray cluster separately.
> > [verl/verl/trainer/main_ppo.py](https://github.com/volcengine/verl/blob/3fe77fa75b1d50b1ffd70149dd53b84e9bd59a6e/verl/trainer/main_ppo.py#L104)
> > Line 104 in [3fe77fa](/volcengine/verl/commit/3fe77fa75b1d50b1ffd70149dd53b84e9bd59a6e)
> > ray.init(runtime_env={'env_vars': {'TOKENIZERS_PARALLELISM': 'true', 'NCCL_DEBUG': 'WARN'}})
> > [verl/verl/single_controller/ray/base.py](https://github.com/volcengine/verl/blob/3fe77fa75b1d50b1ffd70149dd53b84e9bd59a6e/verl/single_controller/ray/base.py#L253)
> > Line 253 in [3fe77fa](/volcengine/verl/commit/3fe77fa75b1d50b1ffd70149dd53b84e9bd59a6e)
> > ray_cls_with_init.update_options({'runtime_env': {'env_vars': env_vars}, 'name': name})
> > Alternatively, setting those environment variables when doing `ray start` should also work.
> 
> Thank you for your help. After setting the export VLLM_ATTENTION_BACKEND=XFORMERS before ray start command it works fine now.

Hi, may I ask what is your new script to set 'VLLM_ATTENTION_BACKEND'?

**Comment by SimonHeye** [comment]
Where did you add the export VLLM_ATTENTION_BACKEND=XFORMERS in which file? I hope you can enlighten me @edchengg
