### ISSUE TITLE
RuntimeError: CUDA error: peer access is not supported between these two devices

### ISSUE THREAD

**Issue by Zzhiter** [volcengine/verl#1874]
## Environment
Script: examples/sglang_multiturn/run_qwen2.5-3b_gsm8k_multiturn.sh

Hardware: Multi-GPU (e.g., 2x H100)

## Error Description
When running the GSM8K multiturn example with tensor_model_parallel_size=2, the training fails with:
RuntimeError: CUDA error: peer access is not supported between these two devices
* Occurs during FSDP weight synchronization.
* GPU memory usage is normal (~7.4/93.0 GB), ruling out OOM.
ray.exceptions.ActorDiedError
* Worker crashes due to the CUDA communication failure.

## Log
```
(WorkerDict pid=261640) kwargs: {'n': 16, 'max_new_tokens': 1024, 'presence_penalty': 0.0, 'frequency_penalty': 0.0, 'repetition_penalty': 1.0, 'temperature': 1.0, 'top_k': -1, 'top_p': 1, 'ignore_eos': False}
(WorkerDict pid=261640) After building sglang_async rollout, memory allocated (GB): 0.92, memory reserved (GB): 2.11, device memory used/total (GB): 7.41/93.00
(WorkerDict pid=261640) After building sharding manager, memory allocated (GB): 0.92, memory reserved (GB): 2.11, device memory used/total (GB): 7.41/93.00
(WorkerDict pid=261640) /.../torch/distributed/fsdp/fully_sharded_data_parallel.py:690: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
(WorkerDict pid=261640)   warnings.warn(
(TaskRunner pid=261066) Saving tensorboard log to tensorboard_log.
(TaskRunner pid=261066) Using LocalLogger is deprecated. The constructor API will change 
(TaskRunner pid=261066) Checkpoint tracker file does not exist: %s /.../checkpoints/gsm8k_async_rl/qwen2.5-3b_function_rm-gsm8k-async-sgl-multi-w-tool-verify-n16/latest_checkpointed_iteration.txt
(TaskRunner pid=261066) Training from scratch
Training Progress:   0%|          | 0/435 [00:00<?, ?it/s]
(WorkerDict pid=261640) [2025-06-05 11:47:44 TP1] Scheduler hit an exception: Traceback (most recent call last):
(WorkerDict pid=261640)   File "/.../sglang/srt/managers/scheduler.py", line 2026, in run_scheduler_process
(WorkerDict pid=261640)     scheduler.event_loop_overlap()
(WorkerDict pid=261640)   File "/.../torch/utils/_contextlib.py", line 116, in decorate_context
(WorkerDict pid=261640)     return func(*args, **kwargs)
(WorkerDict pid=261640)   File "/.../sglang/srt/managers/scheduler.py", line 639, in event_loop_overlap
(WorkerDict pid=261640)     self.process_input_requests(recv_reqs)
(WorkerDict pid=261640)   File "/.../sglang/srt/managers/scheduler.py", line 743, in process_input_requests
(WorkerDict pid=261640)     output = self._request_dispatcher(recv_req)
(WorkerDict pid=261640)   File "/.../sglang/utils.py", line 471, in __call__
(WorkerDict pid=261640)     return fn(obj)
(WorkerDict pid=261640)   File "/.../sglang/srt/managers/scheduler.py", line 1784, in update_weights_from_tensor
(WorkerDict pid=261640)     success, message = self.tp_worker.update_weights_from_tensor(recv_req)
(WorkerDict pid=261640)   File "/.../sglang/srt/managers/tp_worker_overlap_thread.py", line 237, in update_weights_from_tensor
(WorkerDict pid=261640)     success, message = self.worker.update_weights_from_tensor(recv_req)
(WorkerDict pid=261640)   File "/.../sglang/srt/managers/tp_worker.py", line 220, in update_weights_from_tensor
(WorkerDict pid=261640)     success, message = self.model_runner.update_weights_from_tensor(
(WorkerDict pid=261640)   File "/.../sglang/srt/model_executor/model_runner.py", line 647, in update_weights_from_tensor
(WorkerDict pid=261640)     named_tensors = [
(WorkerDict pid=261640)   File "/.../sglang/srt/model_executor/model_runner.py", line 648, in <listcomp>
(WorkerDict pid=261640)     (name, _unwrap_tensor(tensor, tp_rank=self.tp_rank))
(WorkerDict pid=261640)   File "/.../sglang/srt/model_executor/model_runner.py", line 1132, in _unwrap_tensor
(WorkerDict pid=261640)     tensor = tensor.get(tp_rank)
(WorkerDict pid=261640)   File "/.../sglang/srt/model_executor/model_runner.py", line 1144, in get
(WorkerDict pid=261640)     return MultiprocessingSerializer.deserialize(self.values[rank])
(WorkerDict pid=261640)   File "/.../sglang/srt/utils.py", line 1566, in deserialize
(WorkerDict pid=261640)     return ForkingPickler.loads(data)
(WorkerDict pid=261640)   File "/.../sglang/srt/patch_torch.py", line 51, in _rebuild_cuda_tensor_modified
(WorkerDict pid=261640)     return reductions._rebuild_cuda_tensor_original(*args)
(WorkerDict pid=261640)   File "/.../torch/multiprocessing/reductions.py", line 181, in rebuild_cuda_tensor
(WorkerDict pid=261640)     storage = storage_cls._new_shared_cuda(
(WorkerDict pid=261640)   File "/.../torch/storage.py", line 1452, in _new_shared_cuda
(WorkerDict pid=261640)     return torch.UntypedStorage._new_shared_cuda(*args, **kwargs)
(WorkerDict pid=261640) RuntimeError: CUDA error: peer access is not supported between these two devices
(WorkerDict pid=261640) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(WorkerDict pid=261640) 
(WorkerDict pid=261640) [2025-06-05 11:47:44] Received sigquit from a child process. It usually means the child failed.
(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffa06cfce9d6e75fd933979edb06000000 Worker ID: c6877ae445f143cce60956dee8d53ae79d07f94fa92cb9e1b3ac9941 Node ID: 49c3b3e1bd23f357c5688da1dff5967f5faf68a3c8b4c83fa7a53e1c Worker IP address: 10.2.0.22 Worker port: 10115 Worker PID: 261640 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Error executing job with overrides: [...]
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
        class_name: create_colocated_worker_cls.<locals>.WorkerDict
        actor_id: a06cfce9d6e75fd933979edb06000000
        pid: 261640
        name: eNnI1fWorkerDict_0:0
        namespace: 11d2c1aa-d776-436d-8681-91c7138c6010
        ip: 10.2.0.22
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
```

**Comment by Zzhiter** [comment]
This will only happen when using sglang for multi-turn training

**Comment by Cutecodes** [comment]
I also encountered this problem. Have you solved it yet? My environment is 8xRTX4090.

**Comment by zTonyZhao** [comment]
I have encountered the same problem, using 8x4090. Here is my log, hope it could help.

```
(TaskRunner pid=610186) Training from scratch
(TaskRunner pid=610186) test_gen_batch meta info: {'eos_token_id': 151645, 'pad_token_id': 151643, 'recompute_log_prob': False, 'do_sample': False, 'validate': True}
(WorkerDict pid=611035) [2025-07-01 13:15:04 TP1] Cache flushed successfully!
(WorkerDict pid=611035) [2025-07-01 13:15:04 TP0] Cache flushed successfully!
(WorkerDict pid=616095) [2025-07-01 13:15:04 TP0] Cache flushed successfully!
(WorkerDict pid=616093) [2025-07-01 13:15:04 TP1] Cache flushed successfully!
(WorkerDict pid=616093) [2025-07-01 13:15:04 TP0] Cache flushed successfully!
(WorkerDict pid=616097) [2025-07-01 13:15:04 TP1] Cache flushed successfully!
(WorkerDict pid=616095) [2025-07-01 13:15:04 TP1] Cache flushed successfully!
(WorkerDict pid=616097) [2025-07-01 13:15:04 TP0] Cache flushed successfully!
(WorkerDict pid=611035) [2025-07-01 13:15:06 TP1] Scheduler hit an exception: Traceback (most recent call last):
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 2311, in run_scheduler_process
(WorkerDict pid=611035)     scheduler.event_loop_overlap()
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(WorkerDict pid=611035)     return func(*args, **kwargs)
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 662, in event_loop_overlap
(WorkerDict pid=611035)     self.process_input_requests(recv_reqs)
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 889, in process_input_requests
(WorkerDict pid=611035)     output = self._request_dispatcher(recv_req)
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/utils.py", line 471, in __call__
(WorkerDict pid=611035)     return fn(obj)
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 2035, in update_weights_from_tensor
(WorkerDict pid=611035)     success, message = self.tp_worker.update_weights_from_tensor(recv_req)
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 254, in update_weights_from_tensor
(WorkerDict pid=611035)     success, message = self.worker.update_weights_from_tensor(recv_req)
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 255, in update_weights_from_tensor
(WorkerDict pid=611035)     success, message = self.model_runner.update_weights_from_tensor(
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 742, in update_weights_from_tensor
(WorkerDict pid=611035)     named_tensors = [
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 743, in <listcomp>
(WorkerDict pid=611035)     (name, _unwrap_tensor(tensor, tp_rank=self.tp_rank))
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 1296, in _unwrap_tensor
(WorkerDict pid=611035)     tensor = tensor.get(tp_rank)
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 1308, in get
(WorkerDict pid=611035)     return MultiprocessingSerializer.deserialize(self.values[rank])
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/srt/utils.py", line 1672, in deserialize
(WorkerDict pid=611035)     return ForkingPickler.loads(data)
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/sglang/srt/patch_torch.py", line 51, in _rebuild_cuda_tensor_modified
(WorkerDict pid=611035)     return reductions._rebuild_cuda_tensor_original(*args)
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 181, in rebuild_cuda_tensor
(WorkerDict pid=611035)     storage = storage_cls._new_shared_cuda(
(WorkerDict pid=611035)   File "/home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/torch/storage.py", line 1452, in _new_shared_cuda
(WorkerDict pid=611035)     return torch.UntypedStorage._new_shared_cuda(*args, **kwargs)
(WorkerDict pid=611035) RuntimeError: CUDA error: peer access is not supported between these two devices
(WorkerDict pid=611035) CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(WorkerDict pid=611035) For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(WorkerDict pid=611035) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by zTonyZhao** [comment]
After extensive research I seem to locate where the bug is. I have came up with a temporary bugfix and it has passed my test, @Zzhiter @Cutecodes would you kindly help me validate the temporary bugfix?

TL;DR: A temporary workaround is adding line 5,6 below to `srt/utils.py` of SGLang library:

```python
class MultiprocessingSerializer:
    @staticmethod
    def serialize(obj, output_str: bool = False):
        # ADD THESE TWO LINES
        from sglang.srt.patch_torch import monkey_patch_torch_reductions
        monkey_patch_torch_reductions()

        buf = io.BytesIO()
        ForkingPickler(buf).dump(obj)
        ...
```

Tensor transferring in torch.multiprocessing has a bug: When `CUDA_VISIBLE_DEVICES` of subprocess is not the same with that of main process **AND USING CARDS WHICH DO NOT SUPPORT P2P TRANSFERRING, LIKE RTX 4090**, `cuda_device` recorded in the tensor to be transferred will be inconsistant between processes, which leads tensor transferring to fail with error `peer access is not supported between these two devices`.

A bugfix https://github.com/sgl-project/sglang/pull/4565 aims to solve this problem by turning device_id to uuid on serialization and restore on deserialization. However this is only applied to `VerlEngine`, which is no longer used by verl now.

PR #1641 aims to add the patch back to new sglang rollout. However this PR doesn't entirely solve the problem, because multiple subprocesses are introduced(probably by optimization?), and just by adding one line up front does not patch all of them, only those tensors on TP0 are serialized properly, tensors on TP1 are not serialized with patch, which leads to the same error. 

A workaround is to add the patch near serialization, making sure that every process is patched. However this is not a well-made bugfix, since this patch is not needed in every scenario. A more curated commit is needed, and I am currently working on it.

A log of validation with this temporary bugfix is provided below. `{ProcessID} {ThreadID} MONKEY PATCHING` is logged every time a real monkey_patching is taking place. It can be seen that 4 patching in main processes is done up front, with 8 patching in subprocesses is done later. With bugfix removed, only the 4 patching in the front is presented, and the error comes up again.

```
(WorkerDict pid=709128) [2025-07-02 16:15:03] 709128 127233799513920 MONKEY PATCHING
(WorkerDict pid=709128) /home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:690: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
(WorkerDict pid=709128)   warnings.warn(
(WorkerDict pid=709130) [2025-07-02 16:15:03 TP0] max_total_num_tokens=1004638, chunked_prefill_size=8192, max_prefill_tokens=16384, max_running_requests=4097, context_len=32768
(WorkerDict pid=708965) [2025-07-02 16:15:03] 708965 131917163452224 MONKEY PATCHING
(WorkerDict pid=708965) /home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:690: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
(WorkerDict pid=708965)   warnings.warn(
(WorkerDict pid=709130) [2025-07-02 16:15:04] 709130 136181477586752 MONKEY PATCHING
(WorkerDict pid=709130) /home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:690: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
(WorkerDict pid=709130)   warnings.warn(
(WorkerDict pid=709126) [2025-07-02 16:15:04 TP0] max_total_num_tokens=1004638, chunked_prefill_size=8192, max_prefill_tokens=16384, max_running_requests=4097, context_len=32768
(WorkerDict pid=709126) [2025-07-02 16:15:04] 709126 124651000391488 MONKEY PATCHING
(WorkerDict pid=709126) /home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:690: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
(WorkerDict pid=709126)   warnings.warn(
(TaskRunner pid=703215) wandb: Tracking run with wandb version 0.20.1
(TaskRunner pid=703215) wandb: W&B syncing is set to `offline` in this directory. Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
(TaskRunner pid=703215) Checkpoint tracker file does not exist: /home/zhaotianyun/verl/checkpoints/gsm8k_async_rl/qwen2.5-3b_rm-gsm8k-sgl-multiturn-2025-07-02-16-13/latest_checkpointed_iteration.txt
(TaskRunner pid=703215) Training from scratch
(TaskRunner pid=703215) test_gen_batch meta info: {'eos_token_id': 151645, 'pad_token_id': 151643, 'recompute_log_prob': False, 'do_sample': False, 'validate': True}
(WorkerDict pid=709128) [2025-07-02 16:15:08 TP0] Cache flushed successfully!
(WorkerDict pid=708965) [2025-07-02 16:15:08 TP0] Cache flushed successfully!
(WorkerDict pid=709126) [2025-07-02 16:15:08 TP0] Cache flushed successfully!
(WorkerDict pid=709128) [2025-07-02 16:15:08 TP1] Cache flushed successfully!
(WorkerDict pid=708965) [2025-07-02 16:15:08 TP1] Cache flushed successfully!
(WorkerDict pid=709126) [2025-07-02 16:15:08 TP1] Cache flushed successfully!
(WorkerDict pid=709130) [2025-07-02 16:15:09 TP0] Cache flushed successfully!
(WorkerDict pid=709130) [2025-07-02 16:15:09 TP1] Cache flushed successfully!
(WorkerDict pid=708965) [2025-07-02 16:15:10 TP0] 710741 130688479091648 MONKEY PATCHING
(WorkerDict pid=708965) [2025-07-02 16:15:10 TP1] 710742 132641914522560 MONKEY PATCHING
(WorkerDict pid=709126) [2025-07-02 16:15:10 TP0] 710757 137432089971648 MONKEY PATCHING
(WorkerDict pid=709126) [2025-07-02 16:15:10 TP1] 710759 140511678131136 MONKEY PATCHING
(WorkerDict pid=709130) [2025-07-02 16:15:10 TP0] 710756 126513473113024 MONKEY PATCHING
(WorkerDict pid=709130) [2025-07-02 16:15:10 TP1] 710758 126280166915008 MONKEY PATCHING
(WorkerDict pid=709128) [2025-07-02 16:15:10 TP0] 710748 133400138636224 MONKEY PATCHING
(WorkerDict pid=709128) [2025-07-02 16:15:10 TP1] 710749 124807015394240 MONKEY PATCHING
```

**Comment by Cutecodes** [comment]
#

> After extensive research I seem to locate where the bug is. I have came up with a temporary bugfix and it has passed my test, [@Zzhiter](https://github.com/Zzhiter) [@Cutecodes](https://github.com/Cutecodes) would you kindly help me validate the temporary bugfix?
> 
> TL;DR: A temporary workaround is adding line 5,6 below to `srt/utils.py` of SGLang library:
> 
> class MultiprocessingSerializer:
>     @staticmethod
>     def serialize(obj, output_str: bool = False):
>         # ADD THESE TWO LINES
>         from sglang.srt.patch_torch import monkey_patch_torch_reductions
>         monkey_patch_torch_reductions()
> 
>         buf = io.BytesIO()
>         ForkingPickler(buf).dump(obj)
>         ...
> Tensor transferring in torch.multiprocessing has a bug: When `CUDA_VISIBLE_DEVICES` of subprocess is not the same with that of main process **AND USING CARDS WHICH DO NOT SUPPORT P2P TRANSFERRING, LIKE RTX 4090**, `cuda_device` recorded in the tensor to be transferred will be inconsistant between processes, which leads tensor transferring to fail with error `peer access is not supported between these two devices`.
> 
> A bugfix [sgl-project/sglang#4565](https://github.com/sgl-project/sglang/pull/4565) aims to solve this problem by turning device_id to uuid on serialization and restore on deserialization. However this is only applied to `VerlEngine`, which is no longer used by verl now.
> 
> PR [#1641](https://github.com/volcengine/verl/pull/1641) aims to add the patch back to new sglang rollout. However this PR doesn't entirely solve the problem, because multiple subprocesses are introduced(probably by optimization?), and just by adding one line up front does not patch all of them, only those tensors on TP0 are serialized properly, tensors on TP1 are not serialized with patch, which leads to the same error.
> 
> A workaround is to add the patch near serialization, making sure that every process is patched. However this is not a well-made bugfix, since this patch is not needed in every scenario. A more curated commit is needed, and I am currently working on it.
> 
> A log of validation with this temporary bugfix is provided below. `{ProcessID} {ThreadID} MONKEY PATCHING` is logged every time a real monkey_patching is taking place. It can be seen that 4 patching in main processes is done up front, with 8 patching in subprocesses is done later. With bugfix removed, only the 4 patching in the front is presented, and the error comes up again.
> 
> ```
> (WorkerDict pid=709128) [2025-07-02 16:15:03] 709128 127233799513920 MONKEY PATCHING
> (WorkerDict pid=709128) /home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:690: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
> (WorkerDict pid=709128)   warnings.warn(
> (WorkerDict pid=709130) [2025-07-02 16:15:03 TP0] max_total_num_tokens=1004638, chunked_prefill_size=8192, max_prefill_tokens=16384, max_running_requests=4097, context_len=32768
> (WorkerDict pid=708965) [2025-07-02 16:15:03] 708965 131917163452224 MONKEY PATCHING
> (WorkerDict pid=708965) /home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:690: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
> (WorkerDict pid=708965)   warnings.warn(
> (WorkerDict pid=709130) [2025-07-02 16:15:04] 709130 136181477586752 MONKEY PATCHING
> (WorkerDict pid=709130) /home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:690: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
> (WorkerDict pid=709130)   warnings.warn(
> (WorkerDict pid=709126) [2025-07-02 16:15:04 TP0] max_total_num_tokens=1004638, chunked_prefill_size=8192, max_prefill_tokens=16384, max_running_requests=4097, context_len=32768
> (WorkerDict pid=709126) [2025-07-02 16:15:04] 709126 124651000391488 MONKEY PATCHING
> (WorkerDict pid=709126) /home/zhaotianyun/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:690: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
> (WorkerDict pid=709126)   warnings.warn(
> (TaskRunner pid=703215) wandb: Tracking run with wandb version 0.20.1
> (TaskRunner pid=703215) wandb: W&B syncing is set to `offline` in this directory. Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
> (TaskRunner pid=703215) Checkpoint tracker file does not exist: /home/zhaotianyun/verl/checkpoints/gsm8k_async_rl/qwen2.5-3b_rm-gsm8k-sgl-multiturn-2025-07-02-16-13/latest_checkpointed_iteration.txt
> (TaskRunner pid=703215) Training from scratch
> (TaskRunner pid=703215) test_gen_batch meta info: {'eos_token_id': 151645, 'pad_token_id': 151643, 'recompute_log_prob': False, 'do_sample': False, 'validate': True}
> (WorkerDict pid=709128) [2025-07-02 16:15:08 TP0] Cache flushed successfully!
> (WorkerDict pid=708965) [2025-07-02 16:15:08 TP0] Cache flushed successfully!
> (WorkerDict pid=709126) [2025-07-02 16:15:08 TP0] Cache flushed successfully!
> (WorkerDict pid=709128) [2025-07-02 16:15:08 TP1] Cache flushed successfully!
> (WorkerDict pid=708965) [2025-07-02 16:15:08 TP1] Cache flushed successfully!
> (WorkerDict pid=709126) [2025-07-02 16:15:08 TP1] Cache flushed successfully!
> (WorkerDict pid=709130) [2025-07-02 16:15:09 TP0] Cache flushed successfully!
> (WorkerDict pid=709130) [2025-07-02 16:15:09 TP1] Cache flushed successfully!
> (WorkerDict pid=708965) [2025-07-02 16:15:10 TP0] 710741 130688479091648 MONKEY PATCHING
> (WorkerDict pid=708965) [2025-07-02 16:15:10 TP1] 710742 132641914522560 MONKEY PATCHING
> (WorkerDict pid=709126) [2025-07-02 16:15:10 TP0] 710757 137432089971648 MONKEY PATCHING
> (WorkerDict pid=709126) [2025-07-02 16:15:10 TP1] 710759 140511678131136 MONKEY PATCHING
> (WorkerDict pid=709130) [2025-07-02 16:15:10 TP0] 710756 126513473113024 MONKEY PATCHING
> (WorkerDict pid=709130) [2025-07-02 16:15:10 TP1] 710758 126280166915008 MONKEY PATCHING
> (WorkerDict pid=709128) [2025-07-02 16:15:10 TP0] 710748 133400138636224 MONKEY PATCHING
> (WorkerDict pid=709128) [2025-07-02 16:15:10 TP1] 710749 124807015394240 MONKEY PATCHING
> ```

@zTonyZhao I have validated the temporary bugfix and it works well. Thank you very much.

**Comment by Kirrito-k423** [comment]
定时清理检查结论：根据该 issue 的 comments 与 timeline，最近一次非当前运行账号的公开回复或公开引用是 `2025-07-02T11:18:58Z`，来源为 `mentioned`（作者 `staticmethod`，链接：https://github.com/verl-project/verl/issues/1874）。这个时间距离当前定时任务运行日期 2026-07-07 已超过 6 个月。

因此按照社区 issue 定时清理标准关闭此 issue。检查来源包括该 issue 的公开页面 https://github.com/verl-project/verl/issues/1874、comments 列表和 timeline 事件。如果作者或社区成员仍能提供新的复现、证据或需求背景，欢迎重新评论请求重开，或创建新的 issue 并引用本 issue。

---

Scheduled cleanup check: based on this issue's comments and timeline, the latest public reply or public reference from an account other than the current automation account was `2025-07-02T11:18:58Z`. The source was `mentioned` by `staticmethod`: https://github.com/verl-project/verl/issues/1874. This is more than 6 months before the scheduled run date, 2026-07-07.

Therefore, this issue is being closed under the scheduled issue cleanup policy. The checked sources include the public issue page https://github.com/verl-project/verl/issues/1874, the comments list, and timeline events. If the author or community can still provide a fresh reproduction, evidence, or requirement context, please comment to request reopening or file a new issue referencing this one.

This response was generated by a scheduled Codex GPT5.5 issue processing task.
