### ISSUE TITLE
CUDA OOM when doing rollout in GRPO on 8*A6000 gpus

### ISSUE THREAD

**Issue by lyf07** [volcengine/verl#2031]
CUDA OOM happens when actor model is rolling out in GRPO. 
Even for small models like Qwen2.5-1.5B, it still throws out CUDA out of Memory on 8*A6000 gpus, each with 48GB memory.

I've run the `diagnosis.py` and the result is shown as follows:
```
----------Python Info----------
Version      : 3.10.18
Compiler     : GCC 11.2.0
Build        : ('main', 'Jun  5 2025 13:14:17')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 25.1
vllm         : 0.8.3
sglang       : not found.
ray          : 2.46.0
torch        : 2.6.0
----------Platform Info----------
Platform     : Linux-6.5.0-28-generic-x86_64-with-glibc2.35
system       : Linux
release      : 6.5.0-28-generic
version      : #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2
----------Environment----------
CUDA Runtime : 12.4
----------System Info----------
CPU Memory      : 1007.60 GB
GPU Count       : 8
GPU 1   Type    : NVIDIA RTX A6000
GPU 1   Memory  : 47.99 GB
GPU 2   Type    : NVIDIA RTX A6000
GPU 2   Memory  : 47.99 GB
GPU 3   Type    : NVIDIA RTX A6000
GPU 3   Memory  : 47.99 GB
GPU 4   Type    : NVIDIA RTX A6000
GPU 4   Memory  : 47.99 GB
GPU 5   Type    : NVIDIA RTX A6000
GPU 5   Memory  : 47.99 GB
GPU 6   Type    : NVIDIA RTX A6000
GPU 6   Memory  : 47.99 GB
GPU 7   Type    : NVIDIA RTX A6000
GPU 7   Memory  : 47.99 GB
GPU 8   Type    : NVIDIA RTX A6000
GPU 8   Memory  : 47.99 GB
```

Some of the parameters in config is also shown below:
```
python3 -m verl.trainer.main_ppo\
    algorithm.adv_estimator=grpo \
    data.train_files=${train_file_path} \
    data.val_files=${val_file_path} \
    data.train_batch_size=${train_batch_size} \
    data.val_batch_size=128 \
    data.max_prompt_length=1024 \
    data.max_response_length=1024 \
    actor_rollout_ref.model.path=${model_path} \
    actor_rollout_ref.actor.optim.lr=5e-7 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.01 \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.grad_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.tensor_model_parallel_size=4 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.rollout.n=4 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=True \
    algorithm.kl_ctrl.kl_coef=0.0 \
    trainer.val_before_train=False \
    trainer.rollout_data_dir=${rollout_dir} \
    trainer.validation_data_dir=${val_dir} \
    trainer.logger=['wandb'] \
    trainer.experiment_name=${exp_name} \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.default_local_dir=${exp_name} \
    trainer.default_hdfs_dir=null \
    trainer.save_freq=1000 \
    trainer.test_freq=200 \
    trainer.total_epochs=1 $@ 2>&1 | tee grpo.log
```

The error information is:
```
Traceback (most recent call last):
  File "/mnt/data1/yifengliu/qe-lr/verl/trainer/main_ppo.py", line 28, in main
    run_ppo(config)
  File "/mnt/data1/yifengliu/qe-lr/verl/trainer/main_ppo.py", line 46, in run_ppo
    ray.get(runner.run.remote(config))
  File "/mnt/gemini/home/yifengliu/miniconda3/envs/qe-rl/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/mnt/gemini/home/yifengliu/miniconda3/envs/qe-rl/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/mnt/gemini/home/yifengliu/miniconda3/envs/qe-rl/lib/python3.10/site-packages/ray/_private/worker.py", line 2822, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/mnt/gemini/home/yifengliu/miniconda3/envs/qe-rl/lib/python3.10/site-packages/ray/_private/worker.py", line 930, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::TaskRunner.run() (pid=2960610, ip=128.111.28.104, actor_id=aa4689454e79be1bb8cb359301000000, repr=<main_ppo.TaskRunner object at 0x703f611ad990>)
  File "/mnt/data1/yifengliu/qe-lr/verl/trainer/main_ppo.py", line 178, in run
    trainer.fit()
  File "/mnt/data1/yifengliu/qe-lr/verl/trainer/ppo/ray_trainer.py", line 928, in fit
    gen_batch_output = self.actor_rollout_wg.generate_sequences(gen_batch)
  File "/mnt/data1/yifengliu/qe-lr/verl/single_controller/ray/base.py", line 51, in __call__
    output = ray.get(output)
ray.exceptions.RayTaskError(RuntimeError): ray::WorkerDict.actor_rollout_generate_sequences() (pid=2967921, ip=128.111.28.104, actor_id=fc1cd079a07ff16c11efe20e01000000, repr=<verl.single_controller.ray.base.WorkerDict object at 0x749aca312f20>)
  File "/mnt/data1/yifengliu/qe-lr/verl/single_controller/ray/base.py", line 645, in func
    return getattr(self.worker_dict[key], name)(*args, **kwargs)
  File "/mnt/data1/yifengliu/qe-lr/verl/single_controller/base/decorator.py", line 540, in inner
    return func(*args, **kwargs)
  File "/mnt/data1/yifengliu/qe-lr/verl/workers/fsdp_workers.py", line 643, in generate_sequences
    with self.rollout_sharding_manager:
  File "/mnt/data1/yifengliu/qe-lr/verl/utils/debug/performance.py", line 78, in f
    return self.log(decorated_function, *args, **kwargs)
  File "/mnt/data1/yifengliu/qe-lr/verl/utils/debug/performance.py", line 88, in log
    output = func(*args, **kwargs)
  File "/mnt/data1/yifengliu/qe-lr/verl/workers/sharding_manager/fsdp_vllm.py", line 199, in __enter__
    self.inference_engine.wake_up(tags=["kv_cache"])
  File "/mnt/gemini/home/yifengliu/miniconda3/envs/qe-rl/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 1231, in wake_up
    self.llm_engine.wake_up(tags)
  File "/mnt/gemini/home/yifengliu/miniconda3/envs/qe-rl/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 1944, in wake_up
    self.model_executor.wake_up(tags)
  File "/mnt/gemini/home/yifengliu/miniconda3/envs/qe-rl/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 224, in wake_up
    self.collective_rpc("wake_up", kwargs=dict(tags=tags))
  File "/mnt/gemini/home/yifengliu/miniconda3/envs/qe-rl/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
  File "/mnt/gemini/home/yifengliu/miniconda3/envs/qe-rl/lib/python3.10/site-packages/vllm/utils.py", line 2347, in run_method
    return func(*args, **kwargs)
  File "/mnt/gemini/home/yifengliu/miniconda3/envs/qe-rl/lib/python3.10/site-packages/vllm/worker/worker.py", line 140, in wake_up
    allocator.wake_up(tags=tags)
  File "/mnt/gemini/home/yifengliu/miniconda3/envs/qe-rl/lib/python3.10/site-packages/vllm/device_allocator/cumem.py", line 224, in wake_up
    create_and_map(handle)
  File "/mnt/gemini/home/yifengliu/miniconda3/envs/qe-rl/lib/python3.10/site-packages/vllm/device_allocator/cumem.py", line 77, in create_and_map
    python_create_and_map(*allocation_handle)
RuntimeError: CUDA Error: out of memory at /workspace/csrc/cumem_allocator.cpp:62
```

**Comment by SodalimeZero** [comment]
same error

**Comment by lyf07** [comment]
> same error

@SodalimeZero Hi! I'd like to ask what setting you were using in your training? In terms of my case, it turns out to be runnable on OpenRLHF with 4*A6000 gpus. Even increasing the model size to 3B, it's still trainable.

**Comment by SodalimeZero** [comment]
> > same error
> 
> [@SodalimeZero](https://github.com/SodalimeZero) Hi! I'd like to ask what setting you were using in your training? In terms of my case, it turns out to be runnable on OpenRLHF with 4*A6000 gpus. Even increasing the model size to 3B, it's still trainable.

I trained Qwen2.5-14B using DAPO on 2 * 8 H100.
But in fact, I can train Qwen3-14B using 1 * 8 A100 (80G) (is running and not oom).
I am also confused.

**Comment by lyf07** [comment]
> > > same error
> > 
> > 
> > [@SodalimeZero](https://github.com/SodalimeZero) Hi! I'd like to ask what setting you were using in your training? In terms of my case, it turns out to be runnable on OpenRLHF with 4*A6000 gpus. Even increasing the model size to 3B, it's still trainable.
> 
> I trained Qwen2.5-14B using DAPO on 2 * 8 H100. But in fact, I can train Qwen3-14B using 1 * 8 A100 (80G) (is running and not oom). I am also confused.

Oh, I see. It seems to be super weird.
Have you checked other OOM issues under this repo? Will those issues resolve your problem?
Some of them suggest updating vllm to a certain version or even increasing the micro_batch_size. None of them seems to work in my case.

**Comment by SodalimeZero** [comment]
> > > > same error
> > > 
> > > 
> > > [@SodalimeZero](https://github.com/SodalimeZero) Hi! I'd like to ask what setting you were using in your training? In terms of my case, it turns out to be runnable on OpenRLHF with 4*A6000 gpus. Even increasing the model size to 3B, it's still trainable.
> > 
> > 
> > I trained Qwen2.5-14B using DAPO on 2 * 8 H100. But in fact, I can train Qwen3-14B using 1 * 8 A100 (80G) (is running and not oom). I am also confused.
> 
> Oh, I see. It seems to be super weird. Have you checked other OOM issues under this repo? Will those issues resolve your problem? Some of them suggest updating vllm to a certain version or even increasing the micro_batch_size. None of them seems to work in my case.

Yes, I tried some methods, such as adjusting the parameter `sp_size` to 1, but it didn't work.
Also I tried two VLLM versions `0.7.3` and `0.8.5`, but neither worked.

I think this may be the reason: https://github.com/vllm-project/vllm/issues/15254.
But it may be solved in issue https://github.com/volcengine/verl/pull/987?

**Comment by lyf07** [comment]
> > > > > same error
> > > > 
> > > > 
> > > > [@SodalimeZero](https://github.com/SodalimeZero) Hi! I'd like to ask what setting you were using in your training? In terms of my case, it turns out to be runnable on OpenRLHF with 4*A6000 gpus. Even increasing the model size to 3B, it's still trainable.
> > > 
> > > 
> > > I trained Qwen2.5-14B using DAPO on 2 * 8 H100. But in fact, I can train Qwen3-14B using 1 * 8 A100 (80G) (is running and not oom). I am also confused.
> > 
> > 
> > Oh, I see. It seems to be super weird. Have you checked other OOM issues under this repo? Will those issues resolve your problem? Some of them suggest updating vllm to a certain version or even increasing the micro_batch_size. None of them seems to work in my case.
> 
> Yes, I tried some methods, such as adjusting the parameter `sp_size` to 1, but it didn't work. Also I tried two VLLM versions `0.7.3` and `0.8.5`, but neither worked.
> 
> I think this may be the reason: [vllm-project/vllm#15254](https://github.com/vllm-project/vllm/issues/15254). But it may be solved in issue [#987](https://github.com/volcengine/verl/pull/987)?

Thank you very much for your discussion and information!
Maybe it's best for us to wait for someone to address our concerns :)

**Comment by skpig** [comment]
same issue here

**Comment by yiwei-chenn** [comment]
Same issue here :( 
Did anyone solve this problem?

**Comment by CatIIIIIIII** [comment]
same issue

**Comment by CatIIIIIIII** [comment]
> same issue

I solve it by setting gpu_utilization from 0.9 to 0.6

**Comment by A1waysBeenHere** [comment]
Wondering if you guys using `export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`, which cannot work properly with vLLM v1 engine. If you set it `True`, the vLLM offload maynot work, and it led OOM issue in my case.

**Comment by waylonli** [comment]
Same issue.

**Comment by luckyyangrun** [comment]
Same issue.

**Comment by LQBDD** [comment]
same issue

**Comment by xjtupy** [comment]
@lyf07 I have the same problem, have you found a solution?

**Comment by lyf07** [comment]
> [@lyf07](https://github.com/lyf07) I have the same problem, have you found a solution?

No, I finally turn to OpenRLHF.

**Comment by Clementine24** [comment]
same issue, anyone had ever solved it?

**Comment by Kirrito-k423** [comment]
### 中文
根据本次定时任务对 comments 和 timeline 的检查，这个 issue 命中默认超时关闭规则：最近一次非当前运行账号（Kirrito-k423）的公开回复或公开引用是 2025-10-21T09:57:33Z，已经超过 6 个月。证据：latest_non_self_reply_or_reference_at=2025-10-21T09:57:33Z; kind=comment; actor=Clementine24; reference=https://github.com/verl-project/verl/issues/2031#issuecomment-3425720448。检查来源：https://api.github.com/repos/verl-project/verl/issues/2031/comments 和 https://api.github.com/repos/verl-project/verl/issues/2031/timeline。因此按定时清理标准先关闭；如果作者或社区成员仍能提供新的复现、证据或需求背景，可以继续评论请求重开或创建新 issue。

### English
In this scheduled pass, I checked the issue comments and timeline. This issue matches the default stale-issue closure rule: the latest public reply or public reference from an account other than the current runner (Kirrito-k423) was at 2025-10-21T09:57:33Z, which is more than 6 months ago. Evidence: latest_non_self_reply_or_reference_at=2025-10-21T09:57:33Z; kind=comment; actor=Clementine24; reference=https://github.com/verl-project/verl/issues/2031#issuecomment-3425720448. Checked sources: https://api.github.com/repos/verl-project/verl/issues/2031/comments and https://api.github.com/repos/verl-project/verl/issues/2031/timeline. I am closing it under the scheduled cleanup rule. If the author or community can provide a fresh reproduction, evidence, or requirement context, please comment to request reopening or open a new issue.

This response was generated by a scheduled Codex GPT5.5 issue processing task.
