### ISSUE TITLE
During the PPO training, 8 machines can train normally, but a CUDA out-of-memory (OOM) error occurs when using 16 machines.

### ISSUE THREAD

**Issue by qinger521** [volcengine/verl#2588]
When I use ray_trainer to train a 72B model with PPO, the training proceeds normally with 8 machines. However, when I scale up to 16 machines, a CUDA Out of Memory (OOM) error occurs at the line with self.rollout_sharding_manager in fsdp_worker.py, indicating that the error happens before the rollout process.

Here are my training scripts for 8-machine and 16-machine setups:

8-machine：
`NNODES=8

max_prompt_length=$((1024 * 4))
max_response_length=6144
# rollout size
train_prompt_bsz=1024
n_resp_per_prompt=1

train_prompt_mini_bsz=256
valid_batch_size=128
ppo_micro_batch_size_per_gpu=4
sp_size=1
use_dynamic_bsz=True
actor_ppo_max_token_len=$((max_prompt_length + max_response_length))
infer_ppo_max_token_len=$((max_prompt_length + max_response_length))
offload=True
gen_tp=8

ray job submit --no-wait --runtime-env="${RUNTIME_ENV}" \
    --working-dir "${WORKING_DIR}" \
    -- python3 -m verl.trainer.main_ppo \
    data.train_files="${TRAIN_FILE_LIST}" \
    data.val_files="${TEST_FILE}" \
    data.prompt_key=prompt \
    data.truncation='left' \
    data.return_raw_chat=True \
    data.max_prompt_length=${max_prompt_length} \
    data.max_response_length=${max_response_length} \
    data.train_batch_size=${train_prompt_bsz} \
    data.valid_batch_size=${valid_batch_size} \
    algorithm.adv_estimator=${adv_estimator} \
    algorithm.kl_ctrl.kl_coef=${kl_coef} \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.path="${MODEL_PATH}" \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.n=${n_resp_per_prompt} \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.80 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=${gen_tp} \
    actor_rollout_ref.rollout.enable_chunked_prefill=True \
    actor_rollout_ref.rollout.max_num_batched_tokens=$((max_prompt_length + max_response_length)) \
    actor_rollout_ref.rollout.temperature=${temperature} \
    actor_rollout_ref.rollout.top_p=${top_p} \
    actor_rollout_ref.rollout.top_k="${top_k}" \
    actor_rollout_ref.rollout.val_kwargs.top_k="${top_k}" \
    actor_rollout_ref.rollout.val_kwargs.top_p="${top_p}" \
    actor_rollout_ref.rollout.val_kwargs.temperature="${temperature}" \
    actor_rollout_ref.actor.use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.actor.use_kl_loss=${use_kl_loss} \
    actor_rollout_ref.actor.kl_loss_coef=${kl_loss_coef} \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=${actor_ppo_max_token_len} \
    actor_rollout_ref.actor.optim.lr=5e-7 \
    actor_rollout_ref.actor.optim.warmup_style=${warmup_style} \
    actor_rollout_ref.actor.optim.lr_warmup_steps=10 \
    actor_rollout_ref.actor.ppo_mini_batch_size=${train_prompt_mini_bsz} \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=${ppo_micro_batch_size_per_gpu} \
    actor_rollout_ref.actor.fsdp_config.param_offload=${offload} \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=${offload} \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.grad_clip=1.0 \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=${sp_size} \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
    actor_rollout_ref.ref.fsdp_config.param_offload=${offload} \
    actor_rollout_ref.ref.ulysses_sequence_parallel_size=${sp_size} \
    actor_rollout_ref.actor.fsdp_config.fsdp_size=-1 \
    critic.optim.lr=9e-6 \
    critic.optim.warmup_style=${warmup_style} \
    critic.model.use_remove_padding=True \
    critic.optim.lr_warmup_steps_ratio=0.03 \
    critic.model.path="${REWARD_MODEL}" \
    critic.ulysses_sequence_parallel_size=${sp_size} \
    critic.model.enable_gradient_checkpointing=True \
    critic.ppo_micro_batch_size_per_gpu=${ppo_micro_batch_size_per_gpu} \
    critic.model.fsdp_config.param_offload=True \
    critic.model.fsdp_config.optimizer_offload=True \
    reward_model.enable=True \
    reward_model.model.path="${REWARD_MODEL}" \
    reward_model.model.use_remove_padding=True \
    reward_model.model.fsdp_config.param_offload=True \
    reward_model.ulysses_sequence_parallel_size=${sp_size} \
    reward_model.micro_batch_size_per_gpu=${ppo_micro_batch_size_per_gpu} \
    reward_model.if_remove_system_message=True \
    trainer.logger=['console','tensorboard'] \
    trainer.project_name="${project_name}" \
    trainer.experiment_name="${exp_name}" \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes="${NNODES}" \
    trainer.save_freq=10 \
    trainer.total_epochs=3 \
    trainer.default_local_dir="${CKPTS_DIR}" \
    trainer.resume_mode=auto \
    trainer.test_freq=10
`

16-machine：
`NNODES=16

max_prompt_length=$((1024 * 4))
max_response_length=6144
# rollout size
train_prompt_bsz=1024
n_resp_per_prompt=1

train_prompt_mini_bsz=256
valid_batch_size=128
ppo_micro_batch_size_per_gpu=2
sp_size=1
use_dynamic_bsz=True
actor_ppo_max_token_len=$((max_prompt_length + max_response_length))
infer_ppo_max_token_len=$((max_prompt_length + max_response_length))
offload=True
gen_tp=8`

The configuration for the 16-machine setup is nearly identical to that of the 8-machine setup, except that I adjusted `ppo_micro_batch_size_per_gpu` to align it with the `train_prompt_mini_bsz` used in the 8-machine training.

The error message is as follows:

<img width="1782" height="94" alt="Image" src="https://github.com/user-attachments/assets/f5929643-8eff-42b5-b960-9d1381d117d4" />

<img width="646" height="94" alt="Image" src="https://github.com/user-attachments/assets/a2dfecbb-fcc5-40fc-94bc-edd71ecaf046" />

**Comment by qinger521** [comment]
The issue has been resolved. The probable cause is that as the number of machines increases, the model state and communication traffic may grow, leading to higher GPU pressure. Under such circumstances, the value of `actor_rollout_ref.rollout.gpu_memory_utilization` should be reduced.
