### ISSUE TITLE
[BUG]  Fatal Python error: none_dealloc: deallocating None

### ISSUE THREAD

**Issue by Jacoblincc** [volcengine/verl#2833]
我在DAPO训练的时候经常会在中途碰到这个错误导致训练中断。
完整的报错日志如下：
```
Fatal Python error: none_dealloc: deallocating None
[36m(WorkerDict pid=2361411)[0m Python runtime state: initialized
[36m(WorkerDict pid=2361411)[0m 
[36m(WorkerDict pid=2361411)[0m Thread 0x00007f25cb9ff640 (most recent call first):
[36m(WorkerDict pid=2361411)[0m   <no Python frame>
[36m(WorkerDict pid=2361411)[0m 
[36m(WorkerDict pid=2361411)[0m Thread 0x00007f271a9ff640 (most recent call first):
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/threading.py", line 324 in wait
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/threading.py", line 600 in wait
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/tqdm/_monitor.py", line 60 in run
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/threading.py", line 966 in _bootstrap
[36m(WorkerDict pid=2361411)[0m 
[36m(WorkerDict pid=2361411)[0m Thread 0x00007f26a83d8640 (most recent call first):
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/torch/_inductor/compile_worker/subproc_pool.py", line 55 in _recv_msg
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/torch/_inductor/compile_worker/subproc_pool.py", line 191 in _read_thread
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/threading.py", line 946 in run
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/threading.py", line 966 in _bootstrap
[36m(WorkerDict pid=2361411)[0m 
[36m(WorkerDict pid=2361411)[0m Thread 0x00007f27c67fc640 (most recent call first):
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/threading.py", line 324 in wait
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/threading.py", line 600 in wait
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/tqdm/_monitor.py", line 60 in run
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/threading.py", line 966 in _bootstrap
[36m(WorkerDict pid=2361411)[0m 
[36m(WorkerDict pid=2361411)[0m Current thread 0x00007f5adb324740 (most recent call first):
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/vllm/device_allocator/cumem.py", line 206 in sleep
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/vllm/v1/worker/gpu_worker.py", line 93 in sleep
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/vllm/utils/__init__.py", line 2736 in run_method
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 57 in collective_rpc
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 207 in sleep
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 313 in sleep
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/vllm/v1/engine/core_client.py", line 256 in sleep
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/vllm/v1/engine/llm_engine.py", line 278 in sleep
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 1375 in sleep
[36m(WorkerDict pid=2361411)[0m   File "/data01/linxiang/verl/verl/workers/sharding_manager/fsdp_vllm.py", line 216 in __exit__
[36m(WorkerDict pid=2361411)[0m   File "/data01/linxiang/verl/verl/utils/debug/performance.py", line 88 in log
[36m(WorkerDict pid=2361411)[0m   File "/data01/linxiang/verl/verl/utils/debug/performance.py", line 78 in f
[36m(WorkerDict pid=2361411)[0m   File "/data01/linxiang/verl/verl/workers/fsdp_workers.py", line 700 in generate_sequences
[36m(WorkerDict pid=2361411)[0m   File "/data01/linxiang/verl/verl/single_controller/base/decorator.py", line 540 in inner
[36m(WorkerDict pid=2361411)[0m   File "/data01/linxiang/verl/verl/single_controller/ray/base.py", line 705 in func
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463 in _resume_span
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/ray/_private/function_manager.py", line 689 in actor_method_executor
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/ray/_private/worker.py", line 953 in main_loop
[36m(WorkerDict pid=2361411)[0m   File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/ray/_private/workers/default_worker.py", line 330 in <module>
[36m(WorkerDict pid=2361411)[0m 
[36m(WorkerDict pid=2361411)[0m Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, uvloop.loop, ray._raylet, numpy._core._multiarray_umath, numpy.linalg._umath_linalg, pyarrow.lib, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pyarrow._compute, pandas._libs.ops, pandas._libs.hashing, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.internals, pandas._libs.indexing, pandas._libs.index, pandas._libs.writers, pandas._libs.join, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, torch._C, torch._C._dynamo.autograd_compiler, torch._C._dynamo.eval_frame, torch._C._dynamo.guards, torch._C._dynamo.utils, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, regex._regex, markupsafe._speedups, PIL._imaging, sklearn.__check_build._check_build, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg._matfuncs_expm, scipy.linalg._linalg_pythran, scipy.linalg.cython_blas, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize._cython_nnls, scipy._lib._uarray._uarray, scipy.linalg._decomp_interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.optimize._direct, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.interpolate._fitpack, scipy.interpolate._dfitpack, scipy.interpolate._dierckx, scipy.interpolate._ppoly, scipy.interpolate._interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.interpolate._bspl, scipy.special.cython_special, scipy.stats._stats, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._biasedurn, scipy.stats._stats_pythran, scipy.stats._levy_stable.levyst, scipy.stats._ansari_swilk_statistics, scipy.stats._mvn, scipy.stats._rcont.rcont, scipy.ndimage._nd_image, scipy.ndimage._rank_filter_1d, _ni_label, scipy.ndimage._ni_label, sklearn.utils._isfinite, sklearn.utils.sparsefuncs_fast, sklearn.utils.murmurhash, sklearn.utils._openmp_helpers, sklearn.metrics.cluster._expected_mutual_info_fast, sklearn.preprocessing._csr_polynomial_expansion, sklearn.preprocessing._target_encoder_fast, sklearn.metrics._dist_metrics, sklearn.metrics._pairwise_distances_reduction._datasets_pair, sklearn.utils._cython_blas, sklearn.metrics._pairwise_distances_reduction._base, sklearn.metrics._pairwise_distances_reduction._middle_term_computer, sklearn.utils._heap, sklearn.utils._sorting, sklearn.metrics._pairwise_distances_reduction._argkmin, sklearn.metrics._pairwise_distances_reduction._argkmin_classmode, sklearn.utils._vector_sentinel, sklearn.metrics._pairwise_distances_reduction._radius_neighbors, sklearn.metrics._pairwise_distances_reduction._radius_neighbors_classmode, sklearn.metrics._pairwise_fast, PIL._imagingft, av._core, av.logging, av.bytesource, av.buffer, av.audio.format, av.error, av.dictionary, av.container.pyio, av.utils, av.option, av.descriptor, av.format, av.stream, av.container.streams, av.sidedata.motionvectors, av.sidedata.sidedata, av.opaque, av.packet, av.container.input, av.container.output, av.container.core, av.codec.context, av.video.format, av.video.reformatter, av.plane, av.video.plane, av.video.frame, av.video.stream, av.codec.hwaccel, av.codec.codec, av.frame, av.audio.layout, av.audio.plane, av.audio.frame, av.audio.stream, av.filter.pad, av.filter.link, av.filter.context, av.filter.graph, av.filter.filter, av.filter.loudnorm, av.audio.resampler, av.audio.codeccontext, av.audio.fifo, av.bitstream, av.video.codeccontext, pyarrow._json, msgspec._core, sentencepiece._sentencepiece, zmq.backend.cython._zmq, pybase64._pybase64, _cffi_backend, multidict._multidict, yarl._quoting_c, propcache._helpers_c, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket.mask, aiohttp._websocket.reader_c, frozenlist._frozenlist, vllm.cumem_allocator, cuda_utils, numba.core.typeconv._typeconv, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.typing.builtins.itertools, numba.cpython.builtins.math, numba.core.runtime._nrt_python, numba.np.ufunc._internal, numba.experimental.jitclass._box, __triton_launcher (total: 255)
[33m(raylet)[0m A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff344cf5a83e3d998b085fd1e601000000 Worker ID: dadb7bf66533e877eadba0d7343c3fa641756166c0d847b63ca52f8a Node ID: 554339e87227a9edc205ed339a913cb11717d292af4f94889ac9753a Worker IP address: 10.0.30.111 Worker port: 33443 Worker PID: 2361411 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Error executing job with overrides: ['+LXWJE_max_step=700', 'data.train_files=/data01/linxiang/datasets/AVQA/train_qa_updated.jsonl', 'data.val_files=/data01/linxiang/datasets/Merge_COT/dapo_merge_all_0618_val.jsonl', 'data.prompt_key=prompt', 'data.truncation=left', 'data.max_prompt_length=512', 'data.max_response_length=1536', 'data.gen_batch_size=64', 'data.train_batch_size=16', 'actor_rollout_ref.rollout.n=8', 'algorithm.adv_estimator=grpo', 'algorithm.use_kl_in_reward=False', 'algorithm.kl_ctrl.kl_coef=0.0', 'algorithm.filter_groups.max_num_gen_batches=0', 'actor_rollout_ref.actor.use_kl_loss=False', 'actor_rollout_ref.actor.kl_loss_coef=0.0', 'actor_rollout_ref.actor.clip_ratio_low=0.2', 'actor_rollout_ref.actor.clip_ratio_high=0.28', 'actor_rollout_ref.actor.clip_ratio_c=10.0', 'algorithm.filter_groups.enable=True', 'algorithm.filter_groups.metric=seq_final_reward', 'actor_rollout_ref.model.use_remove_padding=False', 'actor_rollout_ref.actor.use_dynamic_bsz=False', 'actor_rollout_ref.ref.log_prob_use_dynamic_bsz=False', 'actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=False', 'actor_rollout_ref.actor.ppo_max_token_len_per_gpu=2048', 'actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=2048', 'actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=2048', 'actor_rollout_ref.model.path=/data01/linxiang/ft_qwen2audio/exp/model_full_v6/qwen2-audio-7b-instruct/v0-20250603-150803/Qwen2-Audio-7b-instruct', 'actor_rollout_ref.model.enable_gradient_checkpointing=True', 'actor_rollout_ref.actor.optim.lr=1e-6', 'actor_rollout_ref.actor.optim.lr_warmup_steps=10', 'actor_rollout_ref.actor.optim.weight_decay=0.1', 'actor_rollout_ref.actor.ppo_mini_batch_size=16', 'actor_rollout_ref.actor.fsdp_config.param_offload=True', 'actor_rollout_ref.actor.fsdp_config.optimizer_offload=True', 'actor_rollout_ref.actor.entropy_coeff=0', 'actor_rollout_ref.actor.grad_clip=1.0', 'actor_rollout_ref.actor.loss_agg_mode=seq-mean-token-mean', 'actor_rollout_ref.actor.ulysses_sequence_parallel_size=1', 'actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=16', 'actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=16', 'actor_rollout_ref.rollout.gpu_memory_utilization=0.5', 'actor_rollout_ref.rollout.tensor_model_parallel_size=1', 'actor_rollout_ref.rollout.enable_chunked_prefill=True', 'actor_rollout_ref.rollout.max_num_batched_tokens=2048', 'actor_rollout_ref.rollout.temperature=1.0', 'actor_rollout_ref.rollout.top_p=1.0', 'actor_rollout_ref.rollout.top_k=-1', 'actor_rollout_ref.rollout.val_kwargs.temperature=1.0', 'actor_rollout_ref.rollout.val_kwargs.top_p=0.7', 'actor_rollout_ref.rollout.val_kwargs.top_k=-1', 'actor_rollout_ref.rollout.val_kwargs.do_sample=True', 'actor_rollout_ref.rollout.val_kwargs.n=1', 'actor_rollout_ref.rollout.enforce_eager=False', 'actor_rollout_ref.rollout.free_cache_engine=False', 'actor_rollout_ref.ref.fsdp_config.param_offload=True', 'actor_rollout_ref.ref.ulysses_sequence_parallel_size=1', 'actor_rollout_ref.actor.fsdp_config.fsdp_size=-1', 'reward_model.reward_manager=dapo', 'reward_model.overlong_buffer.enable=False', 'reward_model.overlong_buffer.len=2048', 'reward_model.overlong_buffer.penalty_factor=1.0', 'trainer.logger=[console]', 'trainer.project_name=DAPO', 'trainer.experiment_name=DAPO-SFT-base-AVQA-v14_8gpu_seqmean_bzs16', 'trainer.n_gpus_per_node=8', 'trainer.nnodes=1', 'trainer.val_before_train=False', 'trainer.test_freq=9999', 'trainer.save_freq=10', 'trainer.total_epochs=5', 'trainer.default_local_dir=/data01/linxiang/DAPO/exp/DAPO-SFT-base-AVQA-v14_8gpu_seqmean_bzs16', 'trainer.resume_mode=auto']
Traceback (most recent call last):
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data01/linxiang/verl/recipe/dapo/main_dapo.py", line 264, in <module>
    main()
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/data01/linxiang/verl/recipe/dapo/main_dapo.py", line 82, in main
    run_ppo(config)
  File "/data01/linxiang/verl/recipe/dapo/main_dapo.py", line 121, in run_ppo
    ray.get(runner.run.remote(config))
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/ray/_private/worker.py", line 2849, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/linxiang/miniconda3/envs/dapo/lib/python3.10/site-packages/ray/_private/worker.py", line 937, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ActorDiedError): [36mray::TaskRunner.run()[39m (pid=2360441, ip=10.0.30.111, actor_id=8aa8e2b6d30e7aafe939e34c01000000, repr=<main_dapo.TaskRunner object at 0x7f276d7d34f0>)
  File "/data01/linxiang/verl/recipe/dapo/main_dapo.py", line 260, in run
    trainer.fit(config.LXWJE_max_step)
  File "/data01/linxiang/verl/recipe/dapo/dapo_ray_trainer.py", line 138, in fit
    gen_batch_output = self.actor_rollout_wg.generate_sequences(gen_batch)
  File "/data01/linxiang/verl/verl/single_controller/ray/base.py", line 111, in __call__
    output = ray.get(output)
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
	class_name: create_colocated_worker_cls.<locals>.WorkerDict
	actor_id: 344cf5a83e3d998b085fd1e601000000
	pid: 2361411
	name: mRXiLVWorkerDict_0:1
	namespace: badf3ca2-b40d-4c2f-82c4-2c93d3f46abf
	ip: 10.0.30.111
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

```
环境如下：
```
Package                           Version
--------------------------------- -------------
accelerate                        1.8.1
aiohappyeyeballs                  2.6.1
aiohttp                           3.12.13
aiosignal                         1.4.0
airportsdata                      20250706
annotated-types                   0.7.0
antlr4-python3-runtime            4.9.3
anyio                             4.9.0
astor                             0.8.1
async-timeout                     5.0.1
attrs                             25.3.0
audioread                         3.0.1
av                                15.0.0
blake3                            1.0.5
cachetools                        6.1.0
certifi                           2025.7.9
cffi                              1.17.1
charset-normalizer                3.4.2
click                             8.2.1
cloudpickle                       3.1.1
codetiming                        1.4.0
compressed-tensors                0.10.2
cupy-cuda12x                      13.4.1
datasets                          3.6.0
decorator                         5.2.1
decord                            0.6.0
deepspeed                         0.16.3
depyf                             0.18.0
dill                              0.3.8
diskcache                         5.6.3
distro                            1.9.0
dnspython                         2.7.0
docker-pycreds                    0.4.0
einops                            0.8.1
email_validator                   2.2.0
exceptiongroup                    1.3.0
fastapi                           0.116.0
fastapi-cli                       0.0.8
fastapi-cloud-cli                 0.1.2
fastrlock                         0.8.3
filelock                          3.18.0
frozenlist                        1.7.0
fsspec                            2025.3.0
gguf                              0.17.1
gitdb                             4.0.12
GitPython                         3.1.44
h11                               0.16.0
hf-xet                            1.1.5
hjson                             3.1.0
httpcore                          1.0.9
httptools                         0.6.4
httpx                             0.28.1
huggingface-hub                   0.33.2
hydra-core                        1.3.2
idna                              3.10
importlib_metadata                8.7.0
interegular                       0.3.3
Jinja2                            3.1.6
jiter                             0.10.0
joblib                            1.5.1
jsonschema                        4.24.0
jsonschema-specifications         2025.4.1
lark                              1.2.2
latex2sympy2_extended             1.10.1
lazy_loader                       0.4
librosa                           0.11.0
llguidance                        0.7.30
llvmlite                          0.44.0
lm-format-enforcer                0.10.11
markdown-it-py                    3.0.0
MarkupSafe                        3.0.2
math-verify                       0.7.0
mdurl                             0.1.2
mistral_common                    1.6.3
modelscope                        1.28.0
mpmath                            1.3.0
msgpack                           1.1.1
msgspec                           0.19.0
multidict                         6.6.3
multiprocess                      0.70.16
nest-asyncio                      1.6.0
networkx                          3.4.2
ninja                             1.11.1.4
numba                             0.61.2
numpy                             2.2.6
nvidia-cublas-cu12                12.6.4.1
nvidia-cuda-cupti-cu12            12.6.80
nvidia-cuda-nvrtc-cu12            12.6.77
nvidia-cuda-runtime-cu12          12.6.77
nvidia-cudnn-cu12                 9.5.1.17
nvidia-cufft-cu12                 11.3.0.4
nvidia-cufile-cu12                1.11.1.6
nvidia-curand-cu12                10.3.7.77
nvidia-cusolver-cu12              11.7.1.2
nvidia-cusparse-cu12              12.5.4.2
nvidia-cusparselt-cu12            0.6.3
nvidia-ml-py                      12.575.51
nvidia-nccl-cu12                  2.26.2
nvidia-nvjitlink-cu12             12.6.85
nvidia-nvtx-cu12                  12.6.77
omegaconf                         2.3.0
openai                            1.90.0
opencv-python-headless            4.12.0.88
orjson                            3.10.18
outlines                          0.1.11
outlines_core                     0.1.26
packaging                         25.0
pandas                            2.3.1
partial-json-parser               0.2.1.1.post6
peft                              0.14.0
pillow                            11.3.0
pip                               25.1
platformdirs                      4.3.8
pooch                             1.8.2
prometheus_client                 0.22.1
prometheus-fastapi-instrumentator 7.1.0
propcache                         0.3.2
protobuf                          5.29.5
psutil                            7.0.0
py-cpuinfo                        9.0.0
pyarrow                           20.0.0
pybase64                          1.4.1
pycountry                         24.6.1
pycparser                         2.22
pydantic                          2.11.7
pydantic_core                     2.33.2
Pygments                          2.19.2
python-dateutil                   2.9.0.post0
python-dotenv                     1.1.1
python-json-logger                3.3.0
python-multipart                  0.0.20
pytz                              2025.2
PyYAML                            6.0.2
pyzmq                             27.0.0
qwen-omni-utils                   0.0.8
ray                               2.47.1
referencing                       0.36.2
regex                             2024.11.6
requests                          2.32.4
rich                              14.0.0
rich-toolkit                      0.14.8
rignore                           0.5.1
rpds-py                           0.26.0
safetensors                       0.5.3
scikit-learn                      1.7.0
scipy                             1.15.3
sentence-transformers             5.0.0
sentencepiece                     0.2.0
sentry-sdk                        2.32.0
setproctitle                      1.3.6
setuptools                        78.1.1
shellingham                       1.5.4
six                               1.17.0
smmap                             5.0.2
sniffio                           1.3.1
soundfile                         0.12.1
soxr                              0.5.0.post1
starlette                         0.46.2
sympy                             1.14.0
tabulate                          0.9.0
tensordict                        0.8.3
threadpoolctl                     3.6.0
tiktoken                          0.9.0
tokenizers                        0.21.2
torch                             2.7.0
torchaudio                        2.7.0
torchdata                         0.11.0
torchvision                       0.22.0
tqdm                              4.67.1
transformers                      4.53.1
triton                            3.3.0
trl                               0.15.2
typer                             0.16.0
typing_extensions                 4.14.1
typing-inspection                 0.4.1
tzdata                            2025.2
urllib3                           2.5.0
uvicorn                           0.35.0
uvloop                            0.21.0
vllm                              0.9.2
wandb                             0.19.8
watchfiles                        1.1.0
websockets                        15.0.1
wheel                             0.45.1
xformers                          0.0.30
xgrammar                          0.1.19
xxhash                            3.5.0
yarl                              1.20.1
zipp                              3.23.0
```
使用8张80g显存gpu，cuda版本12.4
运行脚本如下：
```
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
GPU_NUM=8
project_name='DAPO'
exp_name='DAPO'

adv_estimator=grpo

save_freq=10
test_freq=9999

use_kl_in_reward=False
kl_coef=0.0
use_kl_loss=False
kl_loss_coef=0.0

clip_ratio_low=0.2
clip_ratio_high=0.28

max_prompt_length=512 # 2048 1536
max_response_length=1536 # 2536 20480 1536

enable_overlong_buffer=False
overlong_buffer_len=$((512 * 4))
overlong_penalty_factor=1.0

loss_agg_mode="seq-mean-token-mean"


filter_groups_metric="seq_final_reward"  
max_num_gen_batches=0    
enable_filter_groups=True

gen_prompt_bsz=64 
train_prompt_bsz=16 
train_prompt_mini_bsz=16 
n_resp_per_prompt=8 
micro_batch_size_per_gpu=16 
epoch=5

MODEL_PATH=${MODEL_PATH:-"/data01/"}

CKPTS_DIR=${CKPTS_DIR:-"/data01/"}

TRAIN_FILE=${TRAIN_FILE:-"/data01/linxiang/datasets/AVQA/train_qa_updated.jsonl"}
TEST_FILE=${TEST_FILE:-"/data01/linxiang/datasets/Merge_COT/dapo_merge_all_0618_val.jsonl"}

temperature=1.0 
top_p=1.0
top_k=-1 
val_top_p=0.7


sp_size=1 
use_dynamic_bsz=False 
actor_ppo_max_token_len=$((max_prompt_length + max_response_length))
infer_ppo_max_token_len=$((max_prompt_length + max_response_length))
offload=True 
gen_tp=1

export RAY_DISABLE_WORKER_RESTART=1 

export VLLM_USE_V1=1

export HYDRA_FULL_ERROR=1

export RAY_DEDUP_LOGS=0

export VLLM_USE_MODELSCOPE=True

python3 -m recipe.dapo.main_dapo \
    +LXWJE_max_step=${max_step} \
    data.train_files="${TRAIN_FILE}" \
    data.val_files="${TEST_FILE}" \
    data.prompt_key=prompt \
    data.truncation='left' \
    data.max_prompt_length=${max_prompt_length} \
    data.max_response_length=${max_response_length} \
    data.gen_batch_size=${gen_prompt_bsz} \
    data.train_batch_size=${train_prompt_bsz} \
    actor_rollout_ref.rollout.n=${n_resp_per_prompt} \
    algorithm.adv_estimator=${adv_estimator} \
    algorithm.use_kl_in_reward=${use_kl_in_reward} \
    algorithm.kl_ctrl.kl_coef=${kl_coef} \
    algorithm.filter_groups.max_num_gen_batches=${max_num_gen_batches} \
    actor_rollout_ref.actor.use_kl_loss=${use_kl_loss} \
    actor_rollout_ref.actor.kl_loss_coef=${kl_loss_coef} \
    actor_rollout_ref.actor.clip_ratio_low=${clip_ratio_low} \
    actor_rollout_ref.actor.clip_ratio_high=${clip_ratio_high} \
    actor_rollout_ref.actor.clip_ratio_c=10.0 \
    algorithm.filter_groups.enable=${enable_filter_groups} \
    algorithm.filter_groups.metric=${filter_groups_metric} \
    actor_rollout_ref.model.use_remove_padding=False \
    actor_rollout_ref.actor.use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=${actor_ppo_max_token_len} \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
    actor_rollout_ref.model.path="${MODEL_PATH}" \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps=10 \
    actor_rollout_ref.actor.optim.weight_decay=0.1 \
    actor_rollout_ref.actor.ppo_mini_batch_size=${train_prompt_mini_bsz} \
    actor_rollout_ref.actor.fsdp_config.param_offload=${offload} \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=${offload} \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.grad_clip=1.0 \
    actor_rollout_ref.actor.loss_agg_mode=${loss_agg_mode} \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=${sp_size} \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=${micro_batch_size_per_gpu} \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=${micro_batch_size_per_gpu} \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=${gen_tp} \
    actor_rollout_ref.rollout.enable_chunked_prefill=True \
    actor_rollout_ref.rollout.max_num_batched_tokens=$((max_prompt_length + max_response_length)) \
    actor_rollout_ref.rollout.temperature=${temperature} \
    actor_rollout_ref.rollout.top_p=${top_p} \
    actor_rollout_ref.rollout.top_k="${top_k}" \
    actor_rollout_ref.rollout.val_kwargs.temperature=${temperature} \
    actor_rollout_ref.rollout.val_kwargs.top_p=${val_top_p} \
    actor_rollout_ref.rollout.val_kwargs.top_k=${top_k} \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.n=1 \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.ref.fsdp_config.param_offload=${offload} \
    actor_rollout_ref.ref.ulysses_sequence_parallel_size=${sp_size} \
    actor_rollout_ref.actor.fsdp_config.fsdp_size=-1 \
    reward_model.reward_manager=dapo \
    reward_model.overlong_buffer.enable=${enable_overlong_buffer} \
    reward_model.overlong_buffer.len=${overlong_buffer_len} \
    reward_model.overlong_buffer.penalty_factor=${overlong_penalty_factor} \
    trainer.logger=['console'] \
    trainer.project_name="${project_name}" \
    trainer.experiment_name="${exp_name}" \
    trainer.n_gpus_per_node=${GPU_NUM} \
    trainer.nnodes=1 \
    trainer.val_before_train=False \
    trainer.test_freq=${test_freq} \
    trainer.save_freq=${save_freq} \
    trainer.total_epochs=${epoch} \
    trainer.default_local_dir="${CKPTS_DIR}" \
    trainer.resume_mode=auto 
```
会是oom的原因吗？？训练中断后重启训练可以正常的继续走一段，然后会在下一个随机的step又报错。

**Comment by Jnnndjjsnxbhhunheng** [comment]
same 我也是 grpo 请问您解决了吗

**Comment by jasonyux** [comment]
I also encountered a similar issue with GRPO. In my case the error seems to be caused by vllm.generate instead of sleep

```python
(WorkerDict pid=4049462) Current thread 0x00007ffff7c88740 (most recent call first):                                                                                                                                                                                            
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/vllm/core/scheduler.py", line 794 in _schedule_running                                                                                                          
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/vllm/core/scheduler.py", line 1259 in _schedule_default                                                                                                         
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/vllm/core/scheduler.py", line 1460 in _schedule                                                                                                                 
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/vllm/core/scheduler.py", line 1501 in schedule                                                                                                                  
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 1356 in step                                                                                                                   
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 1423 in _run_engine                                                                                                              
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 473 in generate                                                                                                                  
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/vllm/utils.py", line 1196 in inner                                                                                                                              
(WorkerDict pid=4049462)   File "/home/root/verl-agent/verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py", line 288 in generate_sequences                                                                                                                      
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116 in decorate_context                                                                                                       
(WorkerDict pid=4049462)   File "/home/root/verl-agent/verl/utils/debug/performance.py", line 90 in log                                                                                                                                                             
(WorkerDict pid=4049462)   File "/home/root/verl-agent/verl/utils/debug/performance.py", line 80 in f                                                                                                                                                               
(WorkerDict pid=4049462)   File "/home/root/verl-agent/verl/workers/fsdp_workers.py", line 696 in generate_sequences                                                                                                                                                
(WorkerDict pid=4049462)   File "/home/root/verl-agent/verl/single_controller/base/decorator.py", line 534 in inner                                                                                                                                                 
(WorkerDict pid=4049462)   File "/home/root/verl-agent/verl/single_controller/ray/base.py", line 645 in func                                                                                                                                                        
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463 in _resume_span                                                                                                   
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/ray/_private/function_manager.py", line 689 in actor_method_executor                                                                                            
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/ray/_private/worker.py", line 946 in main_loop                                                                                                                  
(WorkerDict pid=4049462)   File "/home/root/miniconda3/envs/verl-agent/lib/python3.10/site-packages/ray/_private/workers/default_worker.py", line 330 in <module>  
```

**Comment by Zhang-Henry** [comment]
我觉得可能是因为actor_rollout_ref.actor.fsdp_config.param_offload=True导致的内存OOM吧，试下False？

**Comment by chenhaiq** [comment]
使用 gpu_memory_utilization=0.3 可以解决吗?

**Comment by Jnnndjjsnxbhhunheng** [comment]
还是错误了，我也是这样，训练几步就开始出错

**error:**
(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: fffffffffffffffff3dc48db937e668ed2cfb72d01000000 Worker ID: 18442d335e0cb62b67409cfda6920d0823d6bc84d78a7c1cb8a88cc9 Node ID: 3efe4170731fea06082c9ab34f914db09d8f28a7735625db0d4a7b2b Worker IP address: 10.96.200.252 Worker port: 20231 Worker PID: 77820 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Error executing job with overrides: ['algorithm.adv_estimator=grpo', 'data.train_files=/root/paddlejob/workspace/env_run/data/nq_search/train.parquet', 'data.val_files=/root/paddlejob/workspace/env_run/data/nq_search/test.parquet', 'trainer.rollout_data_dir=/root/paddlejob/workspace/env_run/rag_data/logs0', 'data.train_batch_size=128', 'data.max_prompt_length=4096', 'data.max_response_length=512', 'actor_rollout_ref.model.path=/root/paddlejob/workspace/env_run/model/Qwen3-4B', 'actor_rollout_ref.model.use_remove_padding=True', 'actor_rollout_ref.model.enable_gradient_checkpointing=True', 'actor_rollout_ref.actor.optim.lr=1e-6', 'actor_rollout_ref.actor.ppo_mini_batch_size=32', 'actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=8', 'actor_rollout_ref.actor.use_kl_loss=True', 'actor_rollout_ref.actor.kl_loss_coef=0.001', 'actor_rollout_ref.actor.kl_loss_type=low_var_kl', 'actor_rollout_ref.actor.fsdp_config.param_offload=True', 'actor_rollout_ref.actor.fsdp_config.optimizer_offload=True', 'actor_rollout_ref.actor.state_masking=True', 'actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8', 'actor_rollout_ref.rollout.tensor_model_parallel_size=1', 'actor_rollout_ref.rollout.name=vllm', 'actor_rollout_ref.rollout.gpu_memory_utilization=0.3', 'actor_rollout_ref.rollout.n=4', 'actor_rollout_ref.rollout.max_turns=4', 'actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=8', 'actor_rollout_ref.ref.fsdp_config.param_offload=False', 'actor_rollout_ref.rollout.enforce_eager=False', 'actor_rollout_ref.rollout.free_cache_engine=False', 'actor_rollout_ref.env.name=reward_rollout', 'actor_rollout_ref.env.mcp_mode=stdio', 'actor_rollout_ref.env.tool_manager=qwen3', 'actor_rollout_ref.env.enable_thinking=True', 'actor_rollout_ref.env.config_path=envs/configs/mcp_tools.pydata', 'actor_rollout_ref.env.use_process_reward=False', 'reward_rollout.if_use_reward_rollout=True', 'reward_rollout.rollout.tensor_model_parallel_size=4', 'reward_rollout.rollout.gpu_memory_utilization=0.3', 'reward_rollout.rollout.model_name=/root/paddlejob/workspace/env_run/model/Qwen3-14B', 'reward_rollout.rollout.free_cache_engine=False', 'reward_rollout.rollout.response_length=2048', 'reward_model.reward_manager=parallel', 'algorithm.kl_ctrl.kl_coef=0.001', 'trainer.critic_warmup=0', 'trainer.logger=[tensorboard]', 'trainer.project_name=GRPO_search', 'trainer.experiment_name=search_with_thinking', 'trainer.n_gpus_per_node=8', 'trainer.nnodes=1', 'trainer.val_before_train=False', 'trainer.default_local_dir=/root/paddlejob/workspace/env_run/rag_data/results0', 'trainer.default_hdfs_dir=null', 'trainer.save_freq=5', 'trainer.test_freq=100', 'trainer.total_epochs=1']
Traceback (most recent call last):
  File "/root/paddlejob/workspace/env_run/RL-Factory/verl/trainer/main_ppo.py", line 30, in main
    run_ppo(config)
  File "/root/paddlejob/workspace/env_run/RL-Factory/verl/trainer/main_ppo.py", line 49, in run_ppo
    ray.get(runner.run.remote(config))
  File "/root/miniconda3/envs/rlagent/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/rlagent/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/rlagent/lib/python3.10/site-packages/ray/_private/worker.py", line 2822, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/root/miniconda3/envs/rlagent/lib/python3.10/site-packages/ray/_private/worker.py", line 930, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ActorDiedError): ray::TaskRunner.run() (pid=73290, ip=10.96.200.252, actor_id=2b86a7a55b1c8f224dbebe8501000000, repr=<main_ppo.TaskRunner object at 0x7ef3067a8070>)
  File "/root/paddlejob/workspace/env_run/RL-Factory/verl/trainer/main_ppo.py", line 248, in run
    trainer.fit()
  File "/root/paddlejob/workspace/env_run/RL-Factory/verl/trainer/ppo/ray_trainer.py", line 1081, in fit
    gen_batch_output = self.actor_rollout_wg.generate_sequences_loop(gen_batch)
  File "/root/paddlejob/workspace/env_run/RL-Factory/verl/single_controller/ray/base.py", line 51, in __call__
    output = ray.get(output)
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
        class_name: create_colocated_worker_cls.<locals>.WorkerDict
        actor_id: f3dc48db937e668ed2cfb72d01000000
        pid: 77820
        name: BlqMCYWorkerDict_0:7
        namespace: 03a241f0-aa24-466f-ba68-7bb5c728adc9
        ip: 10.96.200.252
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.


**scripts:**

python3 -m verl.trainer.main_ppo\
 17     algorithm.adv_estimator=grpo\
 18     data.train_files=/root/paddlejob/workspace/env_run/data/nq_search/train.parquet\
 19     data.val_files=/root/paddlejob/workspace/env_run/data/nq_search/test.parquet\
 20     trainer.rollout_data_dir=/root/paddlejob/workspace/env_run/rag_data/logs0\
 21     data.train_batch_size=128\
 22     data.max_prompt_length=4096\
 23     data.max_response_length=512\
 24     actor_rollout_ref.model.path=$MODEL_PATH\
 25     actor_rollout_ref.model.use_remove_padding=True\
 26     actor_rollout_ref.model.enable_gradient_checkpointing=True\
 27     actor_rollout_ref.actor.optim.lr=1e-6\
 28     actor_rollout_ref.actor.ppo_mini_batch_size=32\
 29     actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=8\
 30     actor_rollout_ref.actor.use_kl_loss=True\
 31     actor_rollout_ref.actor.kl_loss_coef=0.001\
 32     actor_rollout_ref.actor.kl_loss_type=low_var_kl\
 33     actor_rollout_ref.actor.fsdp_config.param_offload=True\
 34     actor_rollout_ref.actor.fsdp_config.optimizer_offload=True\
 35     actor_rollout_ref.actor.state_masking=True\
 36     actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8\
 37     actor_rollout_ref.rollout.tensor_model_parallel_size=1\
 38     actor_rollout_ref.rollout.name=vllm\
 39     actor_rollout_ref.rollout.gpu_memory_utilization=0.3\
 40     actor_rollout_ref.rollout.n=4\
 41     actor_rollout_ref.rollout.max_turns=4\
 42     actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=8\
 43     actor_rollout_ref.ref.fsdp_config.param_offload=False\
 44     actor_rollout_ref.rollout.enforce_eager=False\
 45     actor_rollout_ref.rollout.free_cache_engine=False\
 46     actor_rollout_ref.env.name=reward_rollout\
 47     actor_rollout_ref.env.mcp_mode=stdio\
 48     actor_rollout_ref.env.tool_manager=qwen3\
 49     actor_rollout_ref.env.enable_thinking=True\
 50     actor_rollout_ref.env.config_path=envs/configs/mcp_tools.pydata\
 51     actor_rollout_ref.env.use_process_reward=False\
 52     reward_rollout.if_use_reward_rollout=True\
 53     reward_rollout.rollout.tensor_model_parallel_size=4\
 54     reward_rollout.rollout.gpu_memory_utilization=0.3\
 55     reward_rollout.rollout.model_name=$REWARD_MODEL_PATH\
 56     reward_rollout.rollout.free_cache_engine=False\
 57     reward_rollout.rollout.response_length=2048\
 58     reward_model.reward_manager=parallel\
 59    algorithm.kl_ctrl.kl_coef=0.001\
 60     trainer.critic_warmup=0\
 61     trainer.logger=['tensorboard']\
 62     trainer.project_name='GRPO_search'\
 63     trainer.experiment_name='search_with_thinking'\
 64     trainer.n_gpus_per_node=8\
 65     trainer.nnodes=1\
 66     trainer.val_before_train=False\
 67     trainer.default_local_dir=$RESULT_DIR\
 68     trainer.default_hdfs_dir=null\
 69     trainer.save_freq=5\
 70     trainer.test_freq=100\
 71     trainer.total_epochs=1 $@ 2>&1 | tee grpo.log


**GPU state:**  
Thu Aug  7 20:10:03 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A800-SXM...  On   | 00000000:4B:00.0 Off |                    0 |
| N/A   29C    P0    75W / 400W |  23896MiB / 81920MiB |     99%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A800-SXM...  On   | 00000000:51:00.0 Off |                    0 |
| N/A   32C    P0    76W / 400W |  24360MiB / 81920MiB |     99%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A800-SXM...  On   | 00000000:6A:00.0 Off |                    0 |
| N/A   33C    P0    76W / 400W |  24360MiB / 81920MiB |     99%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A800-SXM...  On   | 00000000:6F:00.0 Off |                    0 |
| N/A   30C    P0    73W / 400W |  23954MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A800-SXM...  On   | 00000000:8D:00.0 Off |                    0 |
| N/A   30C    P0    73W / 400W |  23850MiB / 81920MiB |     99%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A800-SXM...  On   | 00000000:92:00.0 Off |                    0 |
| N/A   33C    P0    75W / 400W |  24360MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A800-SXM...  On   | 00000000:C9:00.0 Off |                    0 |
| N/A   34C    P0    73W / 400W |  24140MiB / 81920MiB |     99%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A800-SXM...  On   | 00000000:CF:00.0 Off |                    0 |
| N/A   31C    P0    78W / 400W |  23826MiB / 81920MiB |     99%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     79719      C   ray::WorkerDict                  1932MiB |

**Comment by glennccc** [comment]
这个问题我发现超多人遇到，就没有项目维护的人来修一下吗

**Comment by jasonyux** [comment]
I managed to resolve this by changing to `vllm==0.9.0`. not sure if this will solve other peoples issues.

**Comment by Jnnndjjsnxbhhunheng** [comment]
> I managed to resolve this by changing to `vllm==0.9.0`. not sure if this will solve other peoples issues.

thanks bro but it did not work

**Comment by Jnnndjjsnxbhhunheng** [comment]
> I managed to resolve this by changing to `vllm==0.9.0`. not sure if this will solve other peoples issues.

What is your environment?

**Comment by Jacoblincc** [comment]
> 使用 gpu_memory_utilization=0.3 可以解决吗?

不行，仍然报相同错误

**Comment by PuppetCQ** [comment]
> > 使用 gpu_memory_utilization=0.3 可以解决吗?
> 
> 不行，仍然报相同错误

我在ms-swift中看见一个相同的问题，他的解释是由于vllm内存管理的bug导致的，所以需要禁用 sleep_level 或使用服务器模式。但是我不确定在verl中如何结局

**Comment by Humputer** [comment]
我调了一下bs、bs per gpu、lr、rollout n等参数，可以正常跑了，感觉可能是不合适超参导致没训好，出现溢出或cuda越界等问题，然后被ray包装成了这个错误

**Comment by Jnnndjjsnxbhhunheng** [comment]
> 我调了一下bs、bs per gpu、lr、rollout n等参数，可以正常跑了，感觉可能是不合适超参导致没训好，出现溢出或cuda越界等问题，然后被ray包装成了这个错误

可以分享一下参数吗？都是往小调吗？谢谢

**Comment by Humputer** [comment]
> > 我调了一下bs、bs per gpu、lr、rollout n等参数，可以正常跑了，感觉可能是不合适超参导致没训好，出现溢出或cuda越界等问题，然后被ray包装成了这个错误
> 
> 可以分享一下参数吗？都是往小调吗？谢谢

是的，都往小调了点

**Comment by Jacoblincc** [comment]
> > > 我调了一下bs、bs per gpu、lr、rollout n等参数，可以正常跑了，感觉可能是不合适超参导致没训好，出现溢出或cuda越界等问题，然后被ray包装成了这个错误
> > 
> > 
> > 可以分享一下参数吗？都是往小调吗？谢谢
> 
> 是的，都往小调了点

是的，参数会有影响，但是我尝试过将batchsize都调到最小，用4卡仍然会在训练到一定阶段后报错，而且是固定的step位置报错。

**Comment by disperaller** [comment]
问下qwen 2.5 7b的版本用megatron训练dapo 用一个单节点8* a800(80g)的跑 怎么样能不报oom呢 max_prompt_length: 9000, max_response_length: 14000

**Comment by xuelei123-xgb** [comment]
https://www.aidoczh.com/ray/ray-core/patterns/ray-get-too-many-objects.html.  看到了ray里面提到的这个问题，不知道是不是能work

**Comment by Zhenyu-Bo** [comment]
我在 vllm 中找到了类似的 issue，这个 PR 可能有帮助：https://github.com/vllm-project/vllm/pull/23477

**Comment by Kirrito-k423** [comment]
中文：感谢提供日志。当前证据显示，这个崩溃主要发生在 vLLM 的 CuMem / sleep / generate 路径上；原始栈里出现的旧 `verl/workers/sharding_manager/fsdp_vllm.py` 后续已被相关 PR 重构、废弃并清理。同时，verl 已合入过 vLLM sleep level=2 相关修复，vLLM 上游也合入了 CUDA pluggable allocator callback lifetime 的修复。因此目前还不能安全判断这是当前 main 上仍然存在的同一个 verl bug，也不建议仅凭现有信息关闭。

为了继续定位，请补充：1) verl commit/release、vLLM、PyTorch、CUDA、Ray 的精确版本；2) 是否能在当前 verl main 或包含 #3082/#3285/#4361 的版本，并使用包含 vllm-project/vllm#23477 的 vLLM 版本时复现；3) 完整启动命令和配置，尤其是 `rollout_mode`、`free_cache_engine`、sleep level / EP、`gpu_memory_utilization`、batch size / rollout n；4) Ray worker 日志中 fatal error 前后的 CUDA OOM、illegal memory access 或 segfault 记录。

English: Thanks for the logs. The current evidence points mainly to the vLLM CuMem / sleep / generate path. The old `verl/workers/sharding_manager/fsdp_vllm.py` path shown in the original stack has since been refactored, deprecated, and cleaned up. verl has also merged vLLM sleep-level related fixes, and upstream vLLM merged a CUDA pluggable allocator callback lifetime fix. So, with the information currently available, it is not safe to conclude that this is still the same bug on current verl main, and I would not recommend closing it based only on the current evidence.

To continue debugging, please provide: 1) exact verl commit/release plus vLLM, PyTorch, CUDA, and Ray versions; 2) whether it still reproduces on current verl main, or a version including #3082/#3285/#4361, together with a vLLM version that includes vllm-project/vllm#23477; 3) the full launch command/config, especially `rollout_mode`, `free_cache_engine`, sleep level / EP, `gpu_memory_utilization`, batch size, and rollout n; 4) Ray worker logs around the fatal error, including any CUDA OOM, illegal memory access, or segfault messages.

This response was generated by a scheduled Codex GPT5.5 issue processing task.

**Comment by wannanfeng** [comment]
try `export VLLM_USE_CUMEM_ALLOCATOR=0`
I think it can be resolved.
