### ISSUE TITLE
RuntimeError: CUDA error: invalid device oridinal

### ISSUE THREAD

**Issue by as12138** [volcengine/verl#306]
when I run examples/grpo_trainer/run_qwen2-7b.sh ，I encountered this problem.

vllm==0.7.1
cuda==12.4
device: 8xA100 80G

**Comment by ki-ljl** [comment]
I also encountered this problem, how did you solve it?

**Comment by as12138** [comment]
you can follow verl/docs/README_vllm0.7.md.
Note that if you are installing stable versions of vLLM (Option2), you need to make some tiny patches manually on vllm (/path/to/site-packages/vllm after installation) after the above steps:

vllm/distributed/parallel_state.py: Remove the assertion below:
if (world_size
        != tensor_model_parallel_size * pipeline_model_parallel_size):
    raise RuntimeError(
        f"world_size ({world_size}) is not equal to "
        f"tensor_model_parallel_size ({tensor_model_parallel_size}) x "
        f"pipeline_model_parallel_size ({pipeline_model_parallel_size})")
vllm/executor/uniproc_executor.py: change local_rank = rank to local_rank = int(os.environ["LOCAL_RANK"])
vllm/model_executor/model_loader/weight_utils.py: remove the torch.cuda.empty_cache() in pt_weights_iterator
These modifications have already been merged into the main branch of vLLM. Thus nightly vLLM or building vLLM from source do not need these patches.

**Comment by ki-ljl** [comment]
Thank you very much, I solved this problem by reinstalling the 0.5.4 version of vllm
