### ISSUE TITLE
fail to train lora grpo for Qwen3-30B-A3B on 4xH800 80G

### ISSUE THREAD

**Issue by skepsun** [volcengine/verl#3299]
With the same configuration, it is possible to train Qwen3-32B. The shell script is:
```
#!/bin/bash

set -e

# 配置参数
model_path="/d2/models/Qwen3-30B-A3B"
train_files="/d2/datasets/verl/gsm8k/train.parquet"
val_files="/d2/datasets/verl/gsm8k/test.parquet"

# 模型和训练参数
max_prompt_length=512
max_response_length=512

# 性能优化参数 - 支持32B/30B模型在4卡上训练
nproc_per_gpu=16 # 32√ → 64× → 48× → 40√ → 44√ → 46× → 45×
nnodes=1
ngpu_per_node=4
total_procs=$(( nproc_per_gpu * nnodes * ngpu_per_node ))
mini_batch_size=$(( total_procs ))

# GPU配置
export CUDA_VISIBLE_DEVICES=2,3,4,5


# 启动GRPO训练
python3 -m verl.trainer.main_ppo \
    ray_init.num_cpus=32 \
    algorithm.adv_estimator=grpo \
    data.train_files=${train_files} \
    data.val_files=${val_files} \
    data.train_batch_size=${total_procs} \
    data.val_batch_size=${total_procs} \
    data.max_prompt_length=${max_prompt_length} \
    data.max_response_length=${max_response_length} \
    data.filter_overlong_prompts=True \
    data.filter_overlong_prompts_workers=12 \
    data.truncation='error' \
    actor_rollout_ref.model.path=${model_path} \
    actor_rollout_ref.model.use_shm=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.model.lora_rank=8 \
    actor_rollout_ref.model.lora_alpha=32 \
    actor_rollout_ref.model.target_modules=all-linear \
    actor_rollout_ref.actor.optim.lr=3e-5 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=${mini_batch_size} \
    actor_rollout_ref.actor.ppo_micro_batch_size=${mini_batch_size} \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.fsdp_config.fsdp_size=-1 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=${mini_batch_size} \
    actor_rollout_ref.ref.log_prob_micro_batch_size=${mini_batch_size} \
    actor_rollout_ref.actor.entropy_coeff=0.001 \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.tensor_model_parallel_size=4 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.3 \
    actor_rollout_ref.rollout.n=5 \
    actor_rollout_ref.rollout.max_num_seqs=512 \
    actor_rollout_ref.rollout.max_model_len=1536 \
    actor_rollout_ref.rollout.max_num_batched_tokens=1536 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.temperature=0.7 \
    actor_rollout_ref.rollout.top_p=0.8 \
    actor_rollout_ref.rollout.top_k=20 \
    actor_rollout_ref.rollout.load_format=safetensors \
    actor_rollout_ref.rollout.layered_summon=True \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=1 \
    algorithm.kl_ctrl.kl_coef=0.001 \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.log_val_generations=5 \
    trainer.logger=['console','swanlab'] \
    trainer.project_name='verl' \
    trainer.experiment_name='qwen3_30b_grpo' \
    trainer.val_before_train=True \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.save_freq=100 \
    trainer.test_freq=5 \
    trainer.total_epochs=15 $@

echo "GRPO训练完成！"
echo "训练数据: ${train_files}"
echo "验证数据: ${val_files}"
echo "基础模型: ${model_path}"
```

Logs:
```
Training Progress:   0%|          | 0/1740 [00:00<?, ?it/s]
(WorkerDict pid=3040889) /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:680: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html . [repeated 3x across cluster]
(WorkerDict pid=3040889)   warnings.warn( [repeated 3x across cluster]
(WorkerDict pid=3038961) WARNING 09-02 12:10:08 [tokenizer.py:314] No tokenizer found in /simon-stub-path, using base model tokenizer instead. (Exception: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '/simon-stub-path'.)
(WorkerDict pid=3040888) WARNING 09-02 12:10:08 [tokenizer.py:314] No tokenizer found in /simon-stub-path, using base model tokenizer instead. (Exception: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '/simon-stub-path'.)
(WorkerDict pid=3038961) [rank0]:[E902 12:41:26.037831704 ProcessGroupNCCL.cpp:632] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1683564, OpType=_ALLGATHER_BASE, NumelIn=155780160, NumelOut=623120640, Timeout(ms)=1800000) ran for 1800001 milliseconds before timing out.
(WorkerDict pid=3038961) [rank0]:[E902 12:41:26.038503874 ProcessGroupNCCL.cpp:2271] [PG ID 0 PG GUID 0(default_pg) Rank 0]  failure detected by watchdog at work sequence id: 1683564 PG status: last enqueued work: 1683570, last completed work: 1683563
(WorkerDict pid=3038961) [rank0]:[E902 12:41:26.038545569 ProcessGroupNCCL.cpp:670] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
(WorkerDict pid=3038961) [rank0]:[E902 12:41:26.038626281 ProcessGroupNCCL.cpp:2106] [PG ID 0 PG GUID 0(default_pg) Rank 0] First PG on this rank to signal dumping.
(WorkerDict pid=3040887) [rank1]:[E902 12:41:27.597130947 ProcessGroupNCCL.cpp:1746] [PG ID 0 PG GUID 0(default_pg) Rank 1] Received a dump signal due to a collective timeout from this local rank and we will try our best to dump the debug info. Last enqueued NCCL work: 1683570, last completed NCCL work: 1683563.This is most likely caused by incorrect usages of collectives, e.g., wrong sizes used across ranks, the order of collectives is not same for all ranks or the scheduled collective, for some reason, didn't run. Additionally, this can be caused by GIL deadlock or other reasons such as network errors or bugs in the communications library (e.g. NCCL), etc.
(WorkerDict pid=3040887) [rank1]:[E902 12:41:27.597517452 ProcessGroupNCCL.cpp:1536] [PG ID 0 PG GUID 0(default_pg) Rank 1] ProcessGroupNCCL preparing to dump debug info. Include stack trace: 1
(WorkerDict pid=3040887) [rank1]:[E902 12:41:27.598726029 ProcessGroupNCCL.cpp:684] [Rank 1] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
(WorkerDict pid=3040887) [rank1]:[E902 12:41:27.598772289 ProcessGroupNCCL.cpp:698] [Rank 1] To avoid data inconsistency, we are taking the entire process down.
(WorkerDict pid=3040887) [rank1]:[E902 12:41:27.603525644 ProcessGroupNCCL.cpp:1899] [PG ID 0 PG GUID 0(default_pg) Rank 1] Process group watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1683564, OpType=_ALLGATHER_BASE, NumelIn=155780160, NumelOut=623120640, Timeout(ms)=1800000) ran for 1800039 milliseconds before timing out.
(WorkerDict pid=3040887) Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:635 (most recent call first):
(WorkerDict pid=3040887) frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f91119785e8 in /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libc10.so)
(WorkerDict pid=3040887) frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x23d (0x7f90b807da6d in /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=3040887) frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0xc80 (0x7f90b807f7f0 in /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=3040887) frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f90b8080efd in /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=3040887) frame #4: <unknown function> + 0xd8198 (0x7fc085fdf198 in /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6)
(WorkerDict pid=3040887) frame #5: <unknown function> + 0x94b43 (0x7fc088552b43 in /lib/x86_64-linux-gnu/libc.so.6)
(WorkerDict pid=3040887) frame #6: <unknown function> + 0x126a00 (0x7fc0885e4a00 in /lib/x86_64-linux-gnu/libc.so.6)
(WorkerDict pid=3040887)
(WorkerDict pid=3040887) [2025-09-02 12:41:27,124 E 3040887 3041483] logging.cc:118: Unhandled exception: N3c1016DistBackendErrorE. what(): [PG ID 0 PG GUID 0(default_pg) Rank 1] Process group watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1683564, OpType=_ALLGATHER_BASE, NumelIn=155780160, NumelOut=623120640, Timeout(ms)=1800000) ran for 1800039 milliseconds before timing out.
(WorkerDict pid=3040887) Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:635 (most recent call first):
(WorkerDict pid=3040887) frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f91119785e8 in /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libc10.so)
(WorkerDict pid=3040887) frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x23d (0x7f90b807da6d in /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=3040887) frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0xc80 (0x7f90b807f7f0 in /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=3040887) frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f90b8080efd in /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=3040887) frame #4: <unknown function> + 0xd8198 (0x7fc085fdf198 in /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6)
(WorkerDict pid=3040887) frame #5: <unknown function> + 0x94b43 (0x7fc088552b43 in /lib/x86_64-linux-gnu/libc.so.6)
(WorkerDict pid=3040887) frame #6: <unknown function> + 0x126a00 (0x7fc0885e4a00 in /lib/x86_64-linux-gnu/libc.so.6)
(WorkerDict pid=3040887)
(WorkerDict pid=3040887) Exception raised from ncclCommWatchdog at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1905 (most recent call first):
(WorkerDict pid=3040887) frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f91119785e8 in /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libc10.so)
(WorkerDict pid=3040887) frame #1: <unknown function> + 0x11b4abe (0x7f90b804fabe in /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=3040887) frame #2: <unknown function> + 0xe07bed (0x7f90b7ca2bed in /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=3040887) frame #3: <unknown function> + 0xd8198 (0x7fc085fdf198 in /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6)
(WorkerDict pid=3040887) frame #4: <unknown function> + 0x94b43 (0x7fc088552b43 in /lib/x86_64-linux-gnu/libc.so.6)
(WorkerDict pid=3040887) frame #5: <unknown function> + 0x126a00 (0x7fc0885e4a00 in /lib/x86_64-linux-gnu/libc.so.6)
(WorkerDict pid=3040887)
(WorkerDict pid=3040887) [2025-09-02 12:41:27,148 E 3040887 3041483] logging.cc:125: Stack trace:
(WorkerDict pid=3040887)  /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/ray/_raylet.so(+0x150e11a) [0x7fc08760211a] ray::operator<<()
(WorkerDict pid=3040887) /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/ray/_raylet.so(+0x1511022) [0x7fc087605022] ray::TerminateHandler()
(WorkerDict pid=3040887) /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6(+0xbb6bb) [0x7fc085fc26bb] __cxxabiv1::__terminate()
(WorkerDict pid=3040887) /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6(_ZSt10unexpectedv+0) [0x7fc085fbc0e3] std::unexpected()
(WorkerDict pid=3040887) /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6(+0xbb6b4) [0x7fc085fc26b4] __cxxabiv1::__terminate()
(WorkerDict pid=3040887) /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so(+0xe07c7b) [0x7f90b7ca2c7b] c10d::ProcessGroupNCCL::ncclCommWatchdog()
(WorkerDict pid=3040887) /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6(+0xd8198) [0x7fc085fdf198] execute_native_thread_routine
(WorkerDict pid=3040887) /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7fc088552b43]
(WorkerDict pid=3040887) /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7fc0885e4a00]
(WorkerDict pid=3040887)
(WorkerDict pid=3040887) *** SIGABRT received at time=1756788087 on cpu 103 ***
(WorkerDict pid=3040887) PC: @     0x7fc088554a7c  (unknown)  pthread_kill
(WorkerDict pid=3040887)     @     0x7fc088500520  (unknown)  (unknown)
(WorkerDict pid=3040887) [2025-09-02 12:41:27,149 E 3040887 3041483] logging.cc:474: *** SIGABRT received at time=1756788087 on cpu 103 ***
(WorkerDict pid=3040887) [2025-09-02 12:41:27,149 E 3040887 3041483] logging.cc:474: PC: @     0x7fc088554a7c  (unknown)  pthread_kill
(WorkerDict pid=3040887) [2025-09-02 12:41:27,149 E 3040887 3041483] logging.cc:474:     @     0x7fc088500520  (unknown)  (unknown)
(WorkerDict pid=3040887) Fatal Python error: Aborted
(WorkerDict pid=3040887)
(WorkerDict pid=3040887)
(WorkerDict pid=3040887) Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, yaml._yaml, _brotli, zstandard.backend_c, charset_normalizer.md, simplejson._speedups, requests.packages.charset_normalizer.md, requests.packages.chardet.md, uvloop.loop, ray._raylet, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pyarrow.lib, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pyarrow._compute, pandas._libs.ops, pandas._libs.hashing, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.internals, pandas._libs.indexing, pandas._libs.index, pandas._libs.writers, pandas._libs.join, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, torch._C, torch._C._dynamo.autograd_compiler, torch._C._dynamo.eval_frame, torch._C._dynamo.guards, torch._C._dynamo.utils, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, regex._regex, markupsafe._speedups, PIL._imaging, sklearn.__check_build._check_build, lz4._version, lz4.frame._frame, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg._matfuncs_expm, scipy.linalg._linalg_pythran, scipy.linalg.cython_blas, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize._cython_nnls, scipy._lib._uarray._uarray, scipy.linalg._decomp_interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.optimize._direct, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.interpolate._fitpack, scipy.interpolate._dfitpack, scipy.interpolate._dierckx, scipy.interpolate._ppoly, scipy.interpolate._interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.interpolate._bspl, scipy.special.cython_special, scipy.stats._stats, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._biasedurn, scipy.stats._stats_pythran, scipy.stats._levy_stable.levyst, scipy.stats._ansari_swilk_statistics, scipy.stats._mvn, scipy.stats._rcont.rcont, scipy.ndimage._nd_image, scipy.ndimage._rank_filter_1d, _ni_label, scipy.ndimage._ni_label, sklearn.utils._isfinite, sklearn.utils.sparsefuncs_fast, sklearn.utils.murmurhash, sklearn.utils._openmp_helpers, sklearn.metrics.cluster._expected_mutual_info_fast, sklearn.preprocessing._csr_polynomial_expansion, sklearn.preprocessing._target_encoder_fast, sklearn.metrics._dist_metrics, sklearn.metrics._pairwise_distances_reduction._datasets_pair, sklearn.utils._cython_blas, sklearn.metrics._pairwise_distances_reduction._base, sklearn.metrics._pairwise_distances_reduction._middle_term_computer, sklearn.utils._heap, sklearn.utils._sorting, sklearn.metrics._pairwise_distances_reduction._argkmin, sklearn.metrics._pairwise_distances_reduction._argkmin_classmode, sklearn.utils._vector_sentinel, sklearn.metrics._pairwise_distances_reduction._radius_neighbors, sklearn.metrics._pairwise_distances_reduction._radius_neighbors_classmode, sklearn.metrics._pairwise_fast, PIL._imagingft, av._core, av.logging, av.bytesource, av.buffer, av.audio.format, av.error, av.dictionary, av.container.pyio, av.utils, av.option, av.descriptor, av.format, av.stream, av.container.streams, av.sidedata.motionvectors, av.sidedata.sidedata, av.opaque, av.packet, av.container.input, av.container.output, av.container.core, av.codec.context, av.video.format, av.video.reformatter, av.plane, av.video.plane, av.video.frame, av.video.stream, av.codec.hwaccel, av.codec.codec, av.frame, av.audio.layout, av.audio.plane, av.audio.frame, av.audio.stream, av.filter.link, av.filter.context, av.filter.graph, av.filter.filter, av.filter.loudnorm, av.audio.resampler, av.audio.codeccontext, av.audio.fifo, av.bitstream, av.video.codeccontext, nvtx._lib.lib, nvtx._lib.profiler, pyarrow._json, greenlet._greenlet, __original_module__thread, __original_module_select, __original_module_time, _cffi_backend, cuda_utils, zmq.backend.cython._zmq, msgspec._core, _cbor2, setproctitle._setproctitle, pybase64._pybase64, multidict._multidict, yarl._quoting_c, propcache._helpers_c, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket.mask, aiohttp._websocket.reader_c, frozenlist._frozenlist, sentencepiece._sentencepiece, numba.core.typeconv._typeconv, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.typing.builtins.itertools, numba.cpython.builtins.math, numba.core.runtime._nrt_python, numba.np.ufunc._internal, numba.experimental.jitclass._box, vllm.cumem_allocator, __triton_launcher (total: 268)
(WorkerDict pid=3040889)
(WorkerDict pid=3040889)
(WorkerDict pid=3040889)
(WorkerDict pid=3040889) /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6(+0xbb6bb) [0x7f4bedceb6bb] __cxxabiv1::__terminate()
(WorkerDict pid=3040889) /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6(+0xbb6b4) [0x7f4bedceb6b4] __cxxabiv1::__terminate()
(WorkerDict pid=3040889) /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so(+0xe07c7b) [0x7f1c1fca2c7b] c10d::ProcessGroupNCCL::ncclCommWatchdog()
(WorkerDict pid=3040889) /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7f4bf027bb43]
(WorkerDict pid=3040889) /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7f4bf030da00]
(WorkerDict pid=3040889)
(WorkerDict pid=3040889)
(WorkerDict pid=3040889)
(WorkerDict pid=3040888)
(WorkerDict pid=3040888)
(WorkerDict pid=3040888)
(WorkerDict pid=3040888) /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6(+0xbb6bb) [0x7f31837cf6bb] __cxxabiv1::__terminate()
(WorkerDict pid=3040888) /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6(+0xbb6b4) [0x7f31837cf6b4] __cxxabiv1::__terminate()
(WorkerDict pid=3040888) /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so(+0xe07c7b) [0x7f01b3ca2c7b] c10d::ProcessGroupNCCL::ncclCommWatchdog()
(WorkerDict pid=3040888) /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7f3185d5fb43]
(WorkerDict pid=3040888) /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7f3185df1a00]
(WorkerDict pid=3040888)
(WorkerDict pid=3040888)
(WorkerDict pid=3040888)
(WorkerDict pid=3038961)
(WorkerDict pid=3038961)
(WorkerDict pid=3038961)
(WorkerDict pid=3038961) /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6(+0xbb6bb) [0x7f89ab0926bb] __cxxabiv1::__terminate()
(WorkerDict pid=3038961) /home/hujie/.conda/envs/verl/bin/../lib/libstdc++.so.6(+0xbb6b4) [0x7f89ab0926b4] __cxxabiv1::__terminate()
(WorkerDict pid=3038961) /home/hujie/.conda/envs/verl/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so(+0xe07c7b) [0x7f59dd1f8c7b] c10d::ProcessGroupNCCL::ncclCommWatchdog()
(WorkerDict pid=3038961) /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7f89ad622b43]
(WorkerDict pid=3038961) /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7f89ad6b4a00]
(WorkerDict pid=3038961)
(WorkerDict pid=3038961)
(WorkerDict pid=3038961)
(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff034662ef278df365cc2c60cf01000000 Worker ID: 552d6571f0045c76698d4ef2a221bfebd4e62e61460535417a847c8e Node ID: 09bb8705326b4e20b3d946d2ddc748a5f5bff7da5263edfa0d59c26d Worker IP address: 172.27.33.105 Worker port: 41117 Worker PID: 3040889 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
(WorkerDict pid=3040887) WARNING 09-02 12:10:08 [tokenizer.py:314] No tokenizer found in /simon-stub-path, using base model tokenizer instead. (Exception: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '/simon-stub-path'.) [repeated 2x across cluster]
Error executing job with overrides: ['ray_init.num_cpus=32', 'algorithm.adv_estimator=grpo', 'data.train_files=/d2/datasets/verl/gsm8k/train.parquet', 'data.val_files=/d2/datasets/verl/gsm8k/test.parquet', 'data.train_batch_size=64', 'data.val_batch_size=64', 'data.max_prompt_length=512', 'data.max_response_length=512', 'data.filter_overlong_prompts=True', 'data.filter_overlong_prompts_workers=12', 'data.truncation=error', 'actor_rollout_ref.model.path=/d2/models/Qwen3-30B-A3B', 'actor_rollout_ref.model.use_shm=True', 'actor_rollout_ref.model.enable_gradient_checkpointing=True', 'actor_rollout_ref.model.lora_rank=8', 'actor_rollout_ref.model.lora_alpha=32', 'actor_rollout_ref.model.target_modules=all-linear', 'actor_rollout_ref.actor.optim.lr=3e-5', 'actor_rollout_ref.model.use_remove_padding=True', 'actor_rollout_ref.actor.ppo_mini_batch_size=64', 'actor_rollout_ref.actor.ppo_micro_batch_size=64', 'actor_rollout_ref.actor.use_kl_loss=True', 'actor_rollout_ref.actor.kl_loss_coef=0.001', 'actor_rollout_ref.actor.kl_loss_type=low_var_kl', 'actor_rollout_ref.actor.fsdp_config.fsdp_size=-1', 'actor_rollout_ref.rollout.log_prob_micro_batch_size=64', 'actor_rollout_ref.ref.log_prob_micro_batch_size=64', 'actor_rollout_ref.actor.entropy_coeff=0.001', 'actor_rollout_ref.actor.fsdp_config.param_offload=True', 'actor_rollout_ref.actor.fsdp_config.optimizer_offload=True', 'actor_rollout_ref.rollout.tensor_model_parallel_size=4', 'actor_rollout_ref.rollout.name=vllm', 'actor_rollout_ref.rollout.gpu_memory_utilization=0.3', 'actor_rollout_ref.rollout.n=5', 'actor_rollout_ref.rollout.max_num_seqs=512', 'actor_rollout_ref.rollout.max_model_len=1536', 'actor_rollout_ref.rollout.max_num_batched_tokens=1536', 'actor_rollout_ref.rollout.enable_chunked_prefill=False', 'actor_rollout_ref.rollout.temperature=0.7', 'actor_rollout_ref.rollout.top_p=0.8', 'actor_rollout_ref.rollout.top_k=20', 'actor_rollout_ref.rollout.load_format=safetensors', 'actor_rollout_ref.rollout.layered_summon=True', 'actor_rollout_ref.ref.fsdp_config.param_offload=True', 'actor_rollout_ref.actor.ulysses_sequence_parallel_size=1', 'algorithm.kl_ctrl.kl_coef=0.001', 'algorithm.use_kl_in_reward=False', 'trainer.critic_warmup=0', 'trainer.log_val_generations=5', 'trainer.logger=[console,swanlab]', 'trainer.project_name=verl', 'trainer.experiment_name=qwen3_30b_grpo', 'trainer.val_before_train=True', 'trainer.n_gpus_per_node=4', 'trainer.nnodes=1', 'trainer.save_freq=100', 'trainer.test_freq=5', 'trainer.total_epochs=15']
Traceback (most recent call last):
  File "/home/hujie/.conda/envs/verl/lib/python3.10/site-packages/verl/trainer/main_ppo.py", line 40, in main
    run_ppo(config)
  File "/home/hujie/.conda/envs/verl/lib/python3.10/site-packages/verl/trainer/main_ppo.py", line 74, in run_ppo
    ray.get(runner.run.remote(config))
  File "/home/hujie/.conda/envs/verl/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/hujie/.conda/envs/verl/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/hujie/.conda/envs/verl/lib/python3.10/site-packages/ray/_private/worker.py", line 2882, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/hujie/.conda/envs/verl/lib/python3.10/site-packages/ray/_private/worker.py", line 968, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ActorDiedError): ray::TaskRunner.run() (pid=3037511, ip=172.27.33.105, actor_id=eeddfd7075253a88f3f41f2601000000, repr=<main_ppo.TaskRunner object at 0x7f62b6831e10>)
  File "/home/hujie/.conda/envs/verl/lib/python3.10/site-packages/verl/trainer/main_ppo.py", line 241, in run
    trainer.fit()
  File "/home/hujie/.conda/envs/verl/lib/python3.10/site-packages/verl/trainer/ppo/ray_trainer.py", line 1228, in fit
    old_log_prob = self.actor_rollout_wg.compute_log_prob(batch)
  File "/home/hujie/.conda/envs/verl/lib/python3.10/site-packages/verl/single_controller/ray/base.py", line 50, in __call__
    output = ray.get(output)
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
        class_name: create_colocated_worker_cls.<locals>.WorkerDict
        actor_id: 034662ef278df365cc2c60cf01000000
        pid: 3040889
        name: JGBDlvWorkerDict_0:3
        namespace: 3105f052-42ca-4c5f-ace5-45ccfb9bf67a
        ip: 172.27.33.105
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

```

Tried to derease batch size, increase NCCL timeout but not work.
```
Related package infos:
Name: torch
Version: 2.7.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /home/hujie/.conda/envs/verl/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-cufile-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, bitsandbytes, compressed-tensors, deepspeed, FlagEmbedding, flash_attn, flashinfer-python, hdm2, lmdeploy, megatron-core, megatron-energon, nvidia-modelopt, nvidia-resiliency-ext, outlines, peft, sentence-transformers, tensordict, timm, torchaudio, torchdata, torchprofile, torchvision, transformer_engine_torch, vllm, xformers, xgrammar
---
Name: verl
Version: 0.5.0
Summary: verl: Volcano Engine Reinforcement Learning for LLM
Home-page: https://github.com/volcengine/verl
Author: Bytedance - Seed - MLSys
Author-email: zhangchi.usc1992@bytedance.com, gmsheng@connect.hku.hk
License: Apache-2.0
Location: /home/hujie/.conda/envs/verl/lib/python3.10/site-packages
Requires: accelerate, codetiming, datasets, dill, hydra-core, numpy, packaging, pandas, peft, pyarrow, pybind11, pylatexenc, ray, tensordict, torchdata, transformers, wandb
Required-by:
---
Name: vllm
Version: 0.10.1.1
Summary: A high-throughput and memory-efficient inference and serving engine for LLMs
Home-page: https://github.com/vllm-project/vllm
Author: vLLM Team
Author-email:
License-Expression: Apache-2.0
Location: /home/hujie/.conda/envs/verl/lib/python3.10/site-packages
Requires: aiohttp, blake3, cachetools, cbor2, cloudpickle, compressed-tensors, depyf, diskcache, einops, fastapi, filelock, gguf, lark, llguidance, lm-format-enforcer, mistral_common, msgspec, ninja, numba, numpy, openai, openai-harmony, opencv-python-headless, outlines_core, partial-json-parser, pillow, prometheus-fastapi-instrumentator, prometheus_client, protobuf, psutil, py-cpuinfo, pybase64, pydantic, python-json-logger, pyyaml, pyzmq, ray, regex, requests, scipy, sentencepiece, setproctitle, tiktoken, tokenizers, torch, torchaudio, torchvision, tqdm, transformers, typing_extensions, watchfiles, xformers, xgrammar
Required-by:
```

**Comment by skepsun** [comment]
swanlab: https://swanlab.cn/@skepsun/verl/runs/9sxjo54i93axroqke562c/chart

**Comment by skepsun** [comment]
solved. VLLM partially support MOE: 
```
For MoE models, vLLM currently does not support fused MoE LoRA inference. Please ensure that the loaded LoRA model does not contain expert weights.
```
set `target_modules` to attention modules instead of `all-linear`:
```
actor_rollout_ref.model.target_modules=[q_proj,k_proj,v_proj,o_proj] \
```

**Comment by HuazhangHu** [comment]
> solved. VLLM partially support MOE:
> 
> ```
> For MoE models, vLLM currently does not support fused MoE LoRA inference. Please ensure that the loaded LoRA model does not contain expert weights.
> ```
> 
> set `target_modules` to attention modules instead of `all-linear`:
> 
> ```
> actor_rollout_ref.model.target_modules=[q_proj,k_proj,v_proj,o_proj] \
> ```

  File "/usr/local/lib/python3.10/dist-packages/omegaconf/nodes.py", line 194, in _validate_and_convert_impl
    raise ValidationError("Cannot convert '$VALUE_TYPE' to string: '$VALUE'")
omegaconf.errors.ValidationError: Cannot convert 'ListConfig' to string: '['q_proj', 'k_proj', 'v_proj']'
    full_key: target_modules
    object_type=HFModelConfig

**Comment by idelise** [comment]
> > solved. VLLM partially support MOE:
> > ```
> > For MoE models, vLLM currently does not support fused MoE LoRA inference. Please ensure that the loaded LoRA model does not contain expert weights.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > set `target_modules` to attention modules instead of `all-linear`:
> > ```
> > actor_rollout_ref.model.target_modules=[q_proj,k_proj,v_proj,o_proj] \
> > ```
> 
> File "/usr/local/lib/python3.10/dist-packages/omegaconf/nodes.py", line 194, in _validate_and_convert_impl raise ValidationError("Cannot convert '$VALUE_TYPE' to string: '$VALUE'") omegaconf.errors.ValidationError: Cannot convert 'ListConfig' to string: '['q_proj', 'k_proj', 'v_proj']' full_key: target_modules object_type=HFModelConfig

I also encountered the same problem. Has it been resolved?

**Comment by DisdanceReality** [comment]
> > > 解决。VLLM 部分支持 MOE：
> > > ```
> > > For MoE models, vLLM currently does not support fused MoE LoRA inference. Please ensure that the loaded LoRA model does not contain expert weights.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 将 `target_modules` 设置为注意力模块而不是`全线性 `：
> > > ```
> > > actor_rollout_ref.model.target_modules=[q_proj,k_proj,v_proj,o_proj] \
> > > ```
> > 
> > 
> > 文件 “/usr/local/lib/python3.10/dist-packages/omegaconf/nodes.py”，第 194 行，_validate_and_convert_impl 引发 ValidationError（“无法将 '$VALUE_TYPE' 转换为字符串： '$VALUE'”） omegaconf.errors.ValidationError： 无法将 'ListConfig' 转换为字符串： '['q_proj'， 'k_proj'， 'v_proj']' full_key： target_modules object_type=HFModelConfig
> 
> 我也遇到了同样的问题。解决了吗？

我也是

**Comment by 1stprinciple** [comment]
This is not a vllm issue.

You encounter this error during  _old_log_prob = self.actor_rollout_wg.compute_log_prob(batch)_

**Comment by mengdongwei** [comment]
> > > > 解决。VLLM 部分支持 MOE：
> > > > ```
> > > > For MoE models, vLLM currently does not support fused MoE LoRA inference. Please ensure that the loaded LoRA model does not contain expert weights.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 将 `target_modules` 设置为注意力模块而不是`全线性 `：
> > > > ```
> > > > actor_rollout_ref.model.target_modules=[q_proj,k_proj,v_proj,o_proj] \
> > > > ```
> > > 
> > > 
> > > 文件 “/usr/local/lib/python3.10/dist-packages/omegaconf/nodes.py”，第 194 行，_validate_and_convert_impl 引发 ValidationError（“无法将 '$VALUE_TYPE' 转换为字符串： '$VALUE'”） omegaconf.errors.ValidationError： 无法将 'ListConfig' 转换为字符串： '['q_proj'， 'k_proj'， 'v_proj']' full_key： target_modules object_type=HFModelConfig
> > 
> > 
> > 我也遇到了同样的问题。解决了吗？
> 
> 我也是

我也遇到了这个问题，我的verl版本是0.11.0

**Comment by yjwjy** [comment]
@mengdongwei @DisdanceReality @HuazhangHu @idelise 
This error is because OmegaConf does not support Unions of container types (such as Union[str, list[str]]). Use the Any type instead to allow OmegaConf to accept either strings or lists
Change the type to Any to avoid OmegaConf's strict type checking:

file: verl/verl/workers/config/model.py
**
    target_modules: Any = "all-linear"
**

This works for me
