### ISSUE TITLE
NCCL Communication Timeout Issue

### ISSUE THREAD

**Issue by yanghan-shanda** [volcengine/verl#3324]
I encountered this training blockage issue during single-machine multi-GPU training. The process becomes blocked at this stage, whereas single-GPU training proceeds without issues. After prolonged waiting, an error is raised:Traceback (most recent call last): File "/home/yh/verl/recipe/one_step_off_policy/main_ppo.py", line 38, in main run_ppo(config) File "/home/yh/verl/recipe/one_step_off_policy/main_ppo.py", line 68, in run_ppo ray.get(runner.run.remote(config)) File "/home/yh/anaconda3/envs/torch/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper return fn(*args, **kwargs) File "/home/yh/anaconda3/envs/torch/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper return func(*args, **kwargs) File "/home/yh/anaconda3/envs/torch/lib/python3.10/site-packages/ray/_private/worker.py", line 2882, in get values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout) File "/home/yh/anaconda3/envs/torch/lib/python3.10/site-packages/ray/_private/worker.py", line 968, in get_objects raise value.as_instanceof_cause() ray.exceptions.RayTaskError(NcclError): ray::TaskRunner.run() (pid=1384013, ip=192.168.2.232, actor_id=bdf52bc9f94ea0446931bb6501000000, repr=<main_ppo.TaskRunner object at 0x716ba32553c0>) File "/home/yh/verl/recipe/one_step_off_policy/main_ppo.py", line 236, in run trainer.init_workers() File "/home/yh/verl/recipe/one_step_off_policy/ray_trainer.py", line 269, in init_workers self.sync_rollout_weights() File "/home/yh/verl/recipe/one_step_off_policy/ray_trainer.py", line 285, in sync_rollout_weights ray.get(self.rollout_wg.sync_rollout_weights()) ray.exceptions.RayTaskError(NcclError): ray::WorkerDict.rollout_sync_rollout_weights() (pid=1411792, ip=192.168.2.232, actor_id=4c5d0503d0f8cf3add8de7ec01000000, repr=<verl.single_controller.ray.base.WorkerDict object at 0x700f404ac970>) File "/home/yh/verl/verl/single_controller/ray/base.py", line 701, in func return getattr(self.worker_dict[key], name)(*args, **kwargs) File "/home/yh/verl/verl/single_controller/base/decorator.py", line 430, in inner return func(*args, **kwargs) File "/home/yh/verl/recipe/one_step_off_policy/fsdp_workers.py", line 89, in sync_rollout_weights collective.broadcast(tensor, src_rank=0, group_name="actor_rollout") File "/home/yh/anaconda3/envs/torch/lib/python3.10/site-packages/ray/util/collective/collective.py", line 429, in broadcast g.broadcast([tensor], opts) File "/home/yh/anaconda3/envs/torch/lib/python3.10/site-packages/ray/util/collective/collective_group/nccl_collective_group.py", line 269, in broadcast self._collective(tensors, tensors, collective_fn) File "/home/yh/anaconda3/envs/torch/lib/python3.10/site-packages/ray/util/collective/collective_group/nccl_collective_group.py", line 604, in _collective comms = self._get_nccl_collective_communicator(key, devices) File "/home/yh/anaconda3/envs/torch/lib/python3.10/site-packages/ray/util/collective/collective_group/nccl_collective_group.py", line 451, in _get_nccl_collective_communicator nccl_util.groupEnd() File "cupy_backends/cuda/libs/nccl.pyx", line 210, in cupy_backends.cuda.libs.nccl.groupEnd File "cupy_backends/cuda/libs/nccl.pyx", line 243, in cupy_backends.cuda.libs.nccl.groupEnd File "cupy_backends/cuda/libs/nccl.pyx", line 129, in cupy_backends.cuda.libs.nccl.check_status cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_UNHANDLED_CUDA_ERROR: unhandled cuda error (run with NCCL_DEBUG=INFO for details) Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace. (raylet) It looks like you're creating a detached actor in an anonymous namespace. In order to access this actor in the future, you will need to explicitly connect to this namespace with ray.init(namespace="329db01d-d866-485e-b117-e66f2ba0a125", ...)
<img width="1245" height="209" alt="Image" src="https://github.com/user-attachments/assets/5504e128-1c93-4bc3-8664-5b4a41b425ec" />
My GPU situation is
<img width="655" height="680" alt="Image" src="https://github.com/user-attachments/assets/d9e27de5-9387-4dfc-8649-520c57813256" />
Has anyone else encountered a similar issue? How should it be resolved?

**Comment by edc3000** [comment]
解决了吗

**Comment by yanghan-shanda** [comment]
> 解决了吗
解决了，你可以看一下issue#3379

**Comment by Kirrito-k423** [comment]
English:
This issue is being closed under the scheduled stale-issue cleanup rule.

Evidence checked:
- Issue: https://github.com/verl-project/verl/issues/3324
- Comments API: https://api.github.com/repos/verl-project/verl/issues/3324/comments
- Timeline API: https://api.github.com/repos/verl-project/verl/issues/3324/timeline
- Latest public reply or public reference from an account other than the current scheduled task account (`Kirrito-k423`): 2025-09-14T06:40:33Z
- Current run date: 2026-07-18; that latest non-self public activity is more than 6 months old.

Because the most recent non-self public reply/reference is older than 6 months, this issue meets the scheduled cleanup standard and is being closed. If the author or community can still provide a current reproduction, new evidence, or additional requirement context, please comment with those details and ask maintainers to reopen, or open a new issue with updated information.

中文：
本 issue 按定时清理规则关闭。

已检查的证据：
- Issue 页面：https://github.com/verl-project/verl/issues/3324
- Comments API：https://api.github.com/repos/verl-project/verl/issues/3324/comments
- Timeline API：https://api.github.com/repos/verl-project/verl/issues/3324/timeline
- 最近一次由当前定时任务账号（`Kirrito-k423`）之外账号产生的公开回复或公开引用时间：2025-09-14T06:40:33Z
- 本轮运行日期：2026-07-18；该最近非本人公开互动已经超过 6 个月。

由于最近一次非本人公开回复/引用已经超过 6 个月，本 issue 命中定时清理标准，因此关闭。如果作者或社区成员仍能提供当前版本的复现、新证据或更完整的需求背景，请继续评论并请求维护者重开，或用更新后的信息创建新 issue。

This response was generated by a scheduled Codex GPT5.5 issue processing task.
