### ISSUE TITLE
Multi-GPU training deadlocks at initialization while single-GPU starts correctly

### ISSUE THREAD

**Issue by YANGZHOU66666** [volcengine/verl#3350]
I cloned verl repository and followed the official installation guides. When using the command below, the training process worked well:
```
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=$HOME/data/gsm8k/train.parquet \
 data.val_files=$HOME/data/gsm8k/test.parquet \
 data.train_batch_size=256 \
 data.max_prompt_length=512 \
 data.max_response_length=256 \
 actor_rollout_ref.model.path=/root/autodl-tmp/Qwen3-4B-Instruct-2507 \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=16 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
 actor_rollout_ref.rollout.name=vllm \
 actor_rollout_ref.rollout.n=4 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-5 \
 critic.model.path=/root/autodl-tmp/Qwen3-4B-Instruct-2507 \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 algorithm.adv_estimator=grpo \
 trainer.logger=console \
 trainer.val_before_train=False \
 trainer.n_gpus_per_node=1 \
 trainer.nnodes=1 \
 trainer.save_freq=10 \
 trainer.test_freq=10 \
 trainer.total_epochs=15 2>&1 | tee verl_demo.log
```
However, after I set the n_gpus_per_node=4:
```
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=$HOME/data/gsm8k/train.parquet \
 data.val_files=$HOME/data/gsm8k/test.parquet \
 data.train_batch_size=256 \
 data.max_prompt_length=512 \
 data.max_response_length=256 \
 actor_rollout_ref.model.path=/root/autodl-tmp/Qwen3-4B-Instruct-2507 \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=16 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
 actor_rollout_ref.rollout.name=vllm \
 actor_rollout_ref.rollout.n=4 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-5 \
 critic.model.path=/root/autodl-tmp/Qwen3-4B-Instruct-2507 \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 algorithm.adv_estimator=grpo \
 trainer.logger=console \
 trainer.val_before_train=False \
 trainer.n_gpus_per_node=4 \
 trainer.nnodes=1 \
 trainer.save_freq=10 \
 trainer.test_freq=10 \
 trainer.total_epochs=15 2>&1 | tee verl_demo.log
```
The process got stuck. GPU states and logs were as follows:

<img width="473" height="446" alt="Image" src="https://github.com/user-attachments/assets/9af3f4e9-24fa-4da5-b739-65f70c4943fc" />

<img width="2015" height="1083" alt="Image" src="https://github.com/user-attachments/assets/db7e77e2-b994-4b12-bc07-f55ae3a6444e" />

What is the problem?

**Comment by YANGZHOU66666** [comment]
**[Solution]** I tried to run the same arguments on the same model on H20 * 2, with the same environment. And it succeeded!!!
It seemed that Verl can not support training on more than 1 A100/A800 well. (I used A800*4 at the beginning)

**Comment by jongwooko** [comment]
same issue here.. for NVIDIA Corporation AD102GL [RTX 6000 Ada Generation]

but I don't know why...

**Comment by yipenguin** [comment]
Hello, have you solved the problem? I have encountered the same issue. My environment is 8*H20. The program runs normally when I set trainer.n_gpus_per_node to 1/2/4, but it will have this problem when trainer.n_gpus_per_node is set to 8.

**Comment by YANGZHOU66666** [comment]
> Hello, have you solved the problem? I have encountered the same issue. My environment is 8*H20. The program runs normally when I set trainer.n_gpus_per_node to 1/2/4, but it will have this problem when trainer.n_gpus_per_node is set to 8.

Sorry, I have not (at least on A800×4). After changing from A800×4 to H20×2, my work ran successfully...
I heard about setting `CUDA_DEVICE_MAX_CONNECTIONS=1` may work, maybe you could try it.

**Comment by yipenguin** [comment]
> > Hello, have you solved the problem? I have encountered the same issue. My environment is 8*H20. The program runs normally when I set trainer.n_gpus_per_node to 1/2/4, but it will have this problem when trainer.n_gpus_per_node is set to 8.
> 
> Sorry, I have not (at least on A800×4). After changing from A800×4 to H20×2, my work ran successfully... I heard about setting `CUDA_DEVICE_MAX_CONNECTIONS=1` may work, maybe you could try it.

Thank you for your reply and suggestions. I solved this problem by setting the environment variable `export NCCL_P2P_DISABLE=1`. Maybe you could try it.

**Comment by axhiao** [comment]
Setting `export NCCL_P2P_DISABLE=1` also sloved my problem. But this also could slow down the training.

**Comment by Kirrito-k423** [comment]
中文：

从目前公开信息看，这个问题更像是特定多卡拓扑 / NCCL P2P / Ray rank-to-GPU 初始化相关的卡住，而不是单纯的 verl 不支持多 GPU。原因是：同一命令单卡可启动，多名用户在 H20、RTX 6000 Ada、A800 等环境上复现；并且本 issue 中已有用户反馈 `export NCCL_P2P_DISABLE=1` 后 8*H20 可以继续运行：https://github.com/verl-project/verl/issues/3350#issuecomment-3298633456 ，后续也有用户确认该 workaround 有效但可能变慢：https://github.com/verl-project/verl/issues/3350#issuecomment-4078924567 。相似 issue 也有同样反馈，例如 #3445 和 #597。

建议先在启动脚本最前面尝试：

```bash
export NCCL_P2P_DISABLE=1
export HYDRA_FULL_ERROR=1
export RAY_DEDUP_LOGS=0
export NCCL_DEBUG=INFO
```

如果 `NCCL_P2P_DISABLE=1` 能解决，说明问题大概率在 NCCL P2P/设备拓扑路径上，但这可能带来性能下降。为了判断是否需要 verl 侧修复、文档补充，还是环境/NCCL 拓扑问题，请补充：verl commit/version、PyTorch/CUDA/NCCL/driver/Ray/vLLM 版本、GPU 型号与数量、`nvidia-smi topo -m`、完整启动命令、完整卡住前后的 worker 日志，以及设置 `NCCL_P2P_DISABLE=1` 前后的对比结果。

English:

Based on the public evidence so far, this looks more like a topology / NCCL P2P / Ray rank-to-GPU initialization issue than a general lack of multi-GPU support in verl. The same command starts on single GPU, several users reproduced similar hangs on H20, RTX 6000 Ada, and A800 setups, and one user in this issue reported that `export NCCL_P2P_DISABLE=1` made the 8*H20 run proceed: https://github.com/verl-project/verl/issues/3350#issuecomment-3298633456 . Another later comment confirmed the same workaround, with the caveat that training may become slower: https://github.com/verl-project/verl/issues/3350#issuecomment-4078924567 . Similar reports exist in #3445 and #597.

Please try adding this before launching:

```bash
export NCCL_P2P_DISABLE=1
export HYDRA_FULL_ERROR=1
export RAY_DEDUP_LOGS=0
export NCCL_DEBUG=INFO
```

If `NCCL_P2P_DISABLE=1` fixes the hang, that strongly points to the NCCL P2P/device-topology path, though it may reduce performance. To decide whether this needs a verl-side fix, a documentation note, or environment/NCCL topology tuning, please share the verl commit/version, PyTorch/CUDA/NCCL/driver/Ray/vLLM versions, GPU model/count, `nvidia-smi topo -m`, the full launch command, full worker logs around the hang, and a before/after comparison with `NCCL_P2P_DISABLE=1`.

This response was generated by a scheduled Codex GPT5.5 issue processing task.
