### ISSUE TITLE
Bug: GRPO training with Megatron+SGLang hangs at second rollout step due to NCCL timeout

### ISSUE THREAD

**Issue by ZiLaoTou** [volcengine/verl#3873]
**Describe the bug**
When conducting DAPO training for a large model (Qwen/Qwen3-VL-235B-A22B-Instruct) using a hybrid strategy of Megatron for training and SGLang for inference (`rollout`), the process hangs indefinitely during the second iteration.

The first step completes successfully, including:
1.  **Rollout**: `generate_sequences` with SGLang (`gen_tp=16`) works as expected.
2.  **Actor Update**: `update_actor` with Megatron (e.g., `train_tp=4`, `train_pp=8`, `train_ep=8`, `train_etp=8`) also works correctly.
3.  Metrics are calculated and logged.

However, when the second iteration begins, the process gets stuck at the `generate_sequences` (rollout) step. After a long wait, it eventually crashes with an `NCCL operation timeout` and a `ray.exceptions.ActorDiedError`.

**Expected behavior**
The training process should seamlessly transition between the SGLang rollout phase and the Megatron update phase for all subsequent DAPO steps without hanging or crashing.

**Screenshots or Logs**
The key error from the log is a collective operation timeout during an `ALLREDUCE` operation, which points to a distributed deadlock:
```
[rank3]:[E1023 02:44:30.941975491 ProcessGroupNCCL.cpp:632] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=26, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1200000) ran for 1200007 milliseconds before timing out.
```

### System Info

----------Python Info----------
Version      : 3.10.12
Compiler     : GCC 11.4.0
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 25.1.1
vllm         : 0.10.0
sglang       : 0.4.9.post6
ray          : 2.47.1
torch        : 2.7.1
----------verl Info-----------
Version      : 0.5.0.dev
Commit Hash  : None
----------Platform Info----------
Platform     : Linux-5.10.134-16.3.al8.x86_64-x86_64-with-glibc2.35
system       : Linux
node         : master-0
release      : 5.10.134-16.3.al8.x86_64
----------Environment----------
CUDA Runtime : 12.6
CUDA Compiler : Cuda compilation tools, release 12.6, V12.6.20
----------System Info----------
CPU Memory      : 1536.00 GB
GPU      : 128*NVIDIA A800-80GB
`NNODES=16`, `n_gpus_per_node=8`

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Set up the environment for Qwen/Qwen3-VL-235B-A22B-Instruct training using the `verl` framework.
2. Use the provided execution script (`run.sh` below) which defines a Megatron+SGLang hybrid engine.
3. Launch the training job.
4. Observe that the first DAPO step completes successfully and logs metrics.
5. The program will hang at the beginning of the second DAPO step's rollout phase and eventually crash.

---

### Supporting Materials

<details>
<summary><b>Start Command</b></summary>

```bash
/bin/bash recipe/dapo/run.sh
```

</details>

<details>
<summary><b>Execution Script (<code>run.sh</code>)</b></summary>

```bash

# Resource info
export NNODES=${NNODES}
export NODE_RANK=${RANK}

# DAPO train and test dataset
TRAIN_FILE="./data/dapo-math-17k.parquet"
TEST_FILE="['./data/aime-2024.parquet']"


project_name='DAPO'
exp_name='Qwen3-235B-Instruct-megatron'

adv_estimator=grpo
use_kl_in_reward=False
kl_coef=0.0
use_kl_loss=True
kl_loss_coef=0.001

clip_ratio_low=0.2
clip_ratio_high=0.28

max_prompt_length=$((1024 * 1))
max_response_length=$((1024 * 4))
enable_overlong_buffer=True
overlong_buffer_len=$((1024 * 1))
overlong_penalty_factor=1.0

loss_agg_mode="token-mean"

train_prompt_bsz=32 # must be > n_gpus. need to fix
n_resp_per_prompt=8
train_prompt_mini_bsz=16  # mini_bsz * n >= micro_bsz * pp * dp


# Algorithm
temperature=1.0
top_p=1.0
top_k=-1 # 0 for HF rollout, -1 for vLLM rollout
val_top_p=0.7

# Performance Related Parameter
use_dynamic_bsz=True
actor_ppo_max_token_len=$(((max_prompt_length + max_response_length) * 10 / 10))
infer_ppo_max_token_len=$(((max_prompt_length + max_response_length) * 1))
offload=True
gen_tp=16
train_tp=4
train_ep=8
train_etp=1
train_pp=8

optimizer_offload_fraction=0.5

MEGATRON_RECOMPUTE_GRANULARITY=${MEGATRON_RECOMPUTE_GRANULARITY:-selective}
MEGATRON_RECOMPUTE_MODULES=${MEGATRON_RECOMPUTE_MODULES:-'["core_attn","moe"]'}

python3 -m verl.trainer.main_ppo \
    --config-path=config \
    --config-name='ppo_megatron_trainer.yaml' \
    data.train_files="${TRAIN_FILE}" \
    data.val_files="${TEST_FILE}" \
    data.prompt_key=prompt \
    data.truncation='left' \
    data.max_prompt_length=${max_prompt_length} \
    data.max_response_length=${max_response_length} \
    data.train_batch_size=${train_prompt_bsz} \
    actor_rollout_ref.rollout.n=${n_resp_per_prompt} \
    algorithm.adv_estimator=${adv_estimator} \
    algorithm.use_kl_in_reward=${use_kl_in_reward} \
    algorithm.kl_ctrl.kl_coef=${kl_coef} \
    actor_rollout_ref.actor.use_kl_loss=${use_kl_loss} \
    actor_rollout_ref.actor.kl_loss_coef=${kl_loss_coef} \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.clip_ratio_low=${clip_ratio_low} \
    actor_rollout_ref.actor.clip_ratio_high=${clip_ratio_high} \
    actor_rollout_ref.actor.clip_ratio_c=10.0 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=${actor_ppo_max_token_len} \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
    actor_rollout_ref.model.path="${MODEL_PATH}" \
    actor_rollout_ref.model.use_fused_kernels=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps=10 \
    actor_rollout_ref.actor.optim.weight_decay=0.1 \
    +actor_rollout_ref.actor.megatron.override_transformer_config.num_layers_in_first_pipeline_stage=8 \
    +actor_rollout_ref.actor.megatron.override_transformer_config.num_layers_in_last_pipeline_stage=8 \
    +actor_rollout_ref.actor.optim.override_optimizer_config.optimizer_offload_fraction=${optimizer_offload_fraction} \
    +actor_rollout_ref.actor.optim.override_optimizer_config.overlap_cpu_optimizer_d2h_h2d=True \
    +actor_rollout_ref.actor.optim.override_optimizer_config.use_precision_aware_optimizer=True \
    +actor_rollout_ref.actor.optim.override_optimizer_config.optimizer_cpu_offload=True \
    +actor_rollout_ref.actor.checkpoint.save_contents=['model'] \
    actor_rollout_ref.actor.ppo_mini_batch_size=${train_prompt_mini_bsz} \
    actor_rollout_ref.actor.megatron.param_offload=${offload} \
    actor_rollout_ref.actor.megatron.optimizer_offload=${offload} \
    actor_rollout_ref.actor.megatron.grad_offload=${offload} \
    actor_rollout_ref.actor.megatron.pipeline_model_parallel_size=${train_pp} \
    actor_rollout_ref.actor.megatron.tensor_model_parallel_size=${train_tp} \
    actor_rollout_ref.actor.megatron.expert_model_parallel_size=${train_ep} \
    actor_rollout_ref.actor.megatron.expert_tensor_parallel_size=${train_etp} \
    actor_rollout_ref.actor.megatron.dist_checkpointing_path=${MCORE_MODEL_PATH} \
    actor_rollout_ref.actor.megatron.use_dist_checkpointing=True \
    actor_rollout_ref.actor.megatron.override_transformer_config.recompute_granularity=${MEGATRON_RECOMPUTE_GRANULARITY} \
    actor_rollout_ref.actor.megatron.override_transformer_config.recompute_modules=${MEGATRON_RECOMPUTE_MODULES} \
    actor_rollout_ref.actor.optim.clip_grad=1.0 \
    actor_rollout_ref.actor.loss_agg_mode=${loss_agg_mode} \
    actor_rollout_ref.rollout.name=sglang \
    actor_rollout_ref.rollout.load_format=dummy_megatron \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=${gen_tp} \
    actor_rollout_ref.rollout.enable_chunked_prefill=True \
    actor_rollout_ref.rollout.max_num_batched_tokens=$((max_prompt_length + max_response_length)) \
    actor_rollout_ref.rollout.temperature=${temperature} \
    actor_rollout_ref.rollout.top_p=${top_p} \
    actor_rollout_ref.rollout.top_k=${top_k} \
    actor_rollout_ref.nccl_timeout=1200 \
    actor_rollout_ref.rollout.val_kwargs.temperature=${temperature} \
    actor_rollout_ref.rollout.val_kwargs.top_p=${val_top_p} \
    actor_rollout_ref.rollout.val_kwargs.top_k=${top_k} \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.n=1 \
    actor_rollout_ref.ref.megatron.pipeline_model_parallel_size=${train_pp} \
    actor_rollout_ref.ref.megatron.tensor_model_parallel_size=${train_tp} \
    actor_rollout_ref.ref.megatron.expert_model_parallel_size=${train_ep} \
    actor_rollout_ref.ref.megatron.expert_tensor_parallel_size=${train_etp} \
    actor_rollout_ref.ref.megatron.param_offload=${offload} \
    actor_rollout_ref.ref.megatron.dist_checkpointing_path=${MCORE_MODEL_PATH} \
    actor_rollout_ref.ref.megatron.use_dist_checkpointing=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.apply_rope_fusion=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.masked_softmax_fusion=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.bias_activation_fusion=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.bias_dropout_fusion=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.gradient_accumulation_fusion=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.deallocate_pipeline_outputs=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.persist_layer_norm=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.moe_grouped_gemm=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.moe_permute_fusion=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.moe_router_dtype=fp32 \
    reward_model.reward_manager=dapo \
    +reward_model.reward_kwargs.overlong_buffer_cfg.enable=${enable_overlong_buffer} \
    +reward_model.reward_kwargs.overlong_buffer_cfg.len=${overlong_buffer_len} \
    +reward_model.reward_kwargs.overlong_buffer_cfg.penalty_factor=${overlong_penalty_factor} \
    +reward_model.reward_kwargs.overlong_buffer_cfg.log=False \
    +reward_model.reward_kwargs.max_resp_len=${max_response_length} \
    trainer.logger=['console','tensorboard'] \
    trainer.project_name="${project_name}" \
    trainer.experiment_name="${exp_name}" \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes="${NNODES}" \
    trainer.val_before_train=False \
    trainer.test_freq=5 \
    trainer.save_freq=5 \
    trainer.total_epochs=1 \
    trainer.default_local_dir="${CKPTS_DIR}" \
    trainer.resume_mode=auto \
    trainer.rollout_data_dir=${OUTPUT_DIR}/rollout_data \
    +trainer.validation_data_dir=${OUTPUT_DIR}/validation_data \
    trainer.total_training_steps=30 \
```

</details>

<details>
<summary><b>Full Error Log</b></summary>

```
... (First step logs are successful) ...
(TaskRunner pid=152455) step:1 - global_seqlen/min:1309 - ... (a lot of metrics) ... - perf/throughput:8.499546086538803
(TaskRunner pid=152455) 
Training Progress:   3%|▎         | 1/30 [10:37<5:08:06, 637.47s/it]

... (many NCCL timeout errors from different ranks) ...

(WorkerDict pid=97397, ip=33.97.231.144) [rank3]:[E1023 02:44:30.941975491 ProcessGroupNCCL.cpp:632] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=26, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1200000) ran for 1200007 milliseconds before timing out.
(WorkerDict pid=97397, ip=33.97.231.144) [rank3]:[E1023 02:44:30.942078991 ProcessGroupNCCL.cpp:2271] [PG ID 0 PG GUID 0(default_pg) Rank 3]  failure detected by watchdog at work sequence id: 26 PG status: last enqueued work: 26, last completed work: 126

... (Stack traces pointing to ProcessGroupNCCL and ncclCommWatchdog) ...

(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff84d3bef8f04b6a19420178852d000000 Worker ID: 2c6142b276944f69acb1aee309bcc8a9c7dd2275773d4704ab7c45d6 Node ID: 35eb5cb186733bfa7442ac7c1c71baaa9988b610bc9782b1ecbd0db1 Worker IP address: 33.97.254.40 Worker port: 10285 Worker PID: 97740 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Traceback (most recent call last):
  File "/root/code/verl/trainer/main_ppo.py", line 40, in main
    run_ppo(config)
  File "/root/code/verl/trainer/main_ppo.py", line 83, in run_ppo
    ray.get(runner.run.remote(config))
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2849, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 937, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ActorDiedError): ray::TaskRunner.run() (pid=152455, ip=33.97.250.234, actor_id=81024db9b74e72c47c0f3bf82d000000, repr=<main_ppo.TaskRunner object at 0x7fbea0e29030>)
  File "/root/code/verl/trainer/main_ppo.py", line 285, in run
    trainer.fit()
  File "/root/code/verl/trainer/ppo/ray_trainer.py", line 1127, in fit
    gen_batch_output = self.actor_rollout_wg.generate_sequences(gen_batch)
  File "/root/code/verl/single_controller/ray/base.py", line 48, in __call__
    output = ray.get(output)
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
	class_name: create_colocated_worker_cls.<locals>.WorkerDict
	actor_id: 84d3bef8f04b6a19420178852d000000
	pid: 97740
	name: kFyD68WorkerDict_15:3
	namespace: 215c60be-fa10-44e6-bfda-1c47f6516cda
	ip: 33.97.254.40
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
```

</details>

**Comment by chenyangh** [comment]
I had a similar issue. Have you tried increasing the NCCL timeout? It worked for me
```
actor_rollout_ref.nccl_timeout=7200 \
# critic.nccl_timeout=7200 \
# reward_model.nccl_timeout=7200
```

**Comment by nicknign** [comment]
hello， have you ever solved this problem？I meet the similar issue recently on training gspo on Qwen3-235B. I run with the latest version verl0.6.1, the timeout problem is occured after a few training steps. It seems is hanging on function load_Megatron_to_gpu.

**Comment by ZiLaoTou** [comment]
@chenyangh Yes, I tried it, but it didn't work.

**Comment by ZiLaoTou** [comment]
@nicknign Sorry, not at all. Maybe you can try switching to a new version.

**Comment by Kirrito-k423** [comment]
中文：感谢提供详细报告。这个 issue 不建议现在关闭：原始日志显示第二轮 `generate_sequences` 期间出现 NCCL `ALLREDUCE` timeout，后续你也确认把 `actor_rollout_ref.nccl_timeout` 提高到 7200 仍无效；同时还有用户在 verl 0.6.1 的 Qwen3-235B/GSPO 场景报告类似卡在 `load_Megatron_to_gpu` 的现象。

为了继续定位，请补充基于当前 main 或最新 release 的复现信息：1. verl commit/release，以及 sglang / torch / CUDA / NCCL / Ray / driver 版本；2. 完整启动命令和解析后的 Hydra 配置，尤其是 Megatron TP/PP/EP/ETP/CP、rollout TP/DP、`rollout.name`、`rollout.mode`、`load_format`、`free_cache_engine`、`nccl_timeout`；3. 设置 `_VERL_LOGGING_LEVEL=DEBUG` 后，从第一轮 `update_actor` 结束、`update_weights` / `load_Megatron_to_gpu` 到第二轮 `generate_sequences` 卡住前后的文本日志；4. NCCL watchdog 的完整 rank traceback 和各节点 Ray worker 日志；5. 同一配置下 vLLM 是否正常，以及是否能用当前 `examples/grpo_trainer/run_qwen3_vl_235b_a22b_megatron.sh` 或最小改动脚本复现。

English: Thanks for the detailed report. I would not close this issue now: the original log shows an NCCL `ALLREDUCE` timeout during the second `generate_sequences`, increasing `actor_rollout_ref.nccl_timeout` to 7200 was reported not to help, and another user reported a similar Qwen3-235B/GSPO hang around `load_Megatron_to_gpu` on verl 0.6.1.

For further debugging, please provide a reproduction on current main or the latest release: 1. verl commit/release plus sglang / torch / CUDA / NCCL / Ray / driver versions; 2. the full launch command and resolved Hydra config, especially Megatron TP/PP/EP/ETP/CP, rollout TP/DP, `rollout.name`, `rollout.mode`, `load_format`, `free_cache_engine`, and `nccl_timeout`; 3. text logs with `_VERL_LOGGING_LEVEL=DEBUG` from the end of the first `update_actor`, through `update_weights` / `load_Megatron_to_gpu`, to the second `generate_sequences` hang; 4. the full NCCL watchdog rank traceback and Ray worker logs from all nodes; 5. whether vLLM works under the same setup, and whether this reproduces with the current `examples/grpo_trainer/run_qwen3_vl_235b_a22b_megatron.sh` or a minimal modification of it.

This response was generated by a scheduled Codex GPT5.5 issue processing task.
