### ISSUE TITLE
Error: Failed to initialize the TMA descriptor 700

### ISSUE THREAD

**Issue by DBMing** [volcengine/verl#4006]
verl 0.6.0  The following error message appears intermittently during training.
```
[36m(WorkerDict pid=82555)[0m TMA Desc Addr:   0x7f4e2736b080
[36m(WorkerDict pid=82555)[0m format         9
[36m(WorkerDict pid=82555)[0m dim            4
[36m(WorkerDict pid=82555)[0m gmem_address   0xa9bdcd0000
[36m(WorkerDict pid=82555)[0m globalDim      (128,415,2,1,1)
[36m(WorkerDict pid=82555)[0m globalStrides  (2,2048,1024,0,0)
[36m(WorkerDict pid=82555)[0m boxDim         (64,128,1,1,1)
[36m(WorkerDict pid=82555)[0m elementStrides (1,1,1,1,1)
[36m(WorkerDict pid=82555)[0m interleave     0
[36m(WorkerDict pid=82555)[0m swizzle        3
[36m(WorkerDict pid=82555)[0m l2Promotion    2
[36m(WorkerDict pid=82555)[0m oobFill        0
[36m(WorkerDict pid=82555)[0m Error: Failed to initialize the TMA descriptor 700
[36m(WorkerDict pid=82555)[0m TMA Desc Addr:   0x7f4e2736b080
[36m(WorkerDict pid=82555)[0m format         9
[36m(WorkerDict pid=82555)[0m dim            4
[36m(WorkerDict pid=82555)[0m gmem_address   0xa46a000000
[36m(WorkerDict pid=82555)[0m globalDim      (128,16,2,61647,1)
[36m(WorkerDict pid=82555)[0m globalStrides  (2,512,256,8192,0)
[36m(WorkerDict pid=82555)[0m boxDim         (64,128,1,1,1)
[36m(WorkerDict pid=82555)[0m elementStrides (1,1,1,1,1)
[36m(WorkerDict pid=82555)[0m interleave     0
[36m(WorkerDict pid=82555)[0m swizzle        3
[36m(WorkerDict pid=82555)[0m l2Promotion    2
[36m(WorkerDict pid=82555)[0m oobFill        0
[36m(WorkerDict pid=82555)[0m Error: Failed to initialize the TMA descriptor 700
[36m(WorkerDict pid=82555)[0m TMA Desc Addr:   0x7f4e2736b080
[36m(WorkerDict pid=82555)[0m format         9
[36m(WorkerDict pid=82555)[0m dim            4
[36m(WorkerDict pid=82555)[0m gmem_address   0xa48819e000
[36m(WorkerDict pid=82555)[0m globalDim      (128,16,2,61647,1)
[36m(WorkerDict pid=82555)[0m globalStrides  (2,512,256,8192,0)
[36m(WorkerDict pid=82555)[0m boxDim         (64,128,1,1,1)
[36m(WorkerDict pid=82555)[0m elementStrides (1,1,1,1,1)
[36m(WorkerDict pid=82555)[0m interleave     0
[36m(WorkerDict pid=82555)[0m swizzle        3
[36m(WorkerDict pid=82555)[0m l2Promotion    2
[36m(WorkerDict pid=82555)[0m oobFill        0
[36m(WorkerDict pid=82555)[0m Error: Failed to initialize the TMA descriptor 700
[36m(WorkerDict pid=82555)[0m TMA Desc Addr:   0x7f4e2736b080
[36m(WorkerDict pid=82555)[0m format         9
[36m(WorkerDict pid=82555)[0m dim            4
[36m(WorkerDict pid=82555)[0m gmem_address   0xa46a000000
[36m(WorkerDict pid=82555)[0m globalDim      (128,16,2,61647,1)
[36m(WorkerDict pid=82555)[0m globalStrides  (2,512,256,8192,0)
[36m(WorkerDict pid=82555)[0m boxDim         (64,128,1,1,1)
[36m(WorkerDict pid=82555)[0m elementStrides (1,1,1,1,1)
[36m(WorkerDict pid=82555)[0m interleave     0
[36m(WorkerDict pid=82555)[0m swizzle        3
[36m(WorkerDict pid=82555)[0m l2Promotion    2
[36m(WorkerDict pid=82555)[0m oobFill        0
[36m(WorkerDict pid=82555)[0m Error: Failed to initialize the TMA descriptor 700
[36m(WorkerDict pid=82555)[0m TMA Desc Addr:   0x7f4e2736b080
[36m(WorkerDict pid=82555)[0m format         9
[36m(WorkerDict pid=82555)[0m dim            4
[36m(WorkerDict pid=82555)[0m gmem_address   0xa48819e000
[36m(WorkerDict pid=82555)[0m globalDim      (128,16,2,61647,1)
[36m(WorkerDict pid=82555)[0m globalStrides  (2,512,256,8192,0)
[36m(WorkerDict pid=82555)[0m boxDim         (64,128,1,1,1)
[36m(WorkerDict pid=82555)[0m elementStrides (1,1,1,1,1)
[36m(WorkerDict pid=82555)[0m interleave     0
[36m(WorkerDict pid=82555)[0m swizzle        3
[36m(WorkerDict pid=82555)[0m l2Promotion    2
[36m(WorkerDict pid=82555)[0m oobFill        0
[36m(WorkerDict pid=82555)[0m Error: Failed to initialize the TMA descriptor 700
[36m(WorkerDict pid=82555)[0m CUDA error (/workspace/.deps/vllm-flash-attn-src/hopper/flash_fwd_launch_template.h:191): an illegal memory access was encountered
[36m(WorkerDict pid=82558)[0m l2Promotion    2
[36m(WorkerDict pid=82558)[0m l2Promotion    2
[36m(WorkerDict pid=82558)[0m l2Promotion    2
[36m(WorkerDict pid=82558)[0m l2Promotion    2
[36m(WorkerDict pid=82558)[0m l2Promotion    2
```

then the error message below is being repeated, but training has not stopped.

```
[36m(WorkerDict pid=134586)[0m [rank7]:[W1104 07:52:01.751088784 TCPStore.cpp:125] [c10d] recvValue failed on SocketImpl(fd=90, addr=[train-kubeflow-72-46805-20251104102107-master-0]:49384, remote=[train-kubeflow-72-46805-20251104102107-master-0]:32991): Connection reset by peer[32m [repeated 6x across cluster][0m
[36m(WorkerDict pid=134586)[0m Exception raised from recvBytes at /pytorch/torch/csrc/distributed/c10d/Utils.hpp:679 (most recent call first):[32m [repeated 6x across cluster][0m
[36m(WorkerDict pid=134580)[0m frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x7f4f5c6d2eb0 in /usr/local/lib/python3.12/dist-packages/torch/lib/libc10.so)[32m [repeated 35x across cluster][0m
[36m(WorkerDict pid=134580)[0m frame #8: <unknown function> + 0x129c3c (0x7f4f92abdc3c in /usr/lib/x86_64-linux-gnu/libc.so.6)[32m [repeated 210x across cluster][0m
[36m(WorkerDict pid=134580)[0m frame #4: c10d::TCPStore::check(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) + 0x30e (0x7f2003dfe18e in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cpu.so)[32m [repeated 35x across cluster][0m
[36m(WorkerDict pid=134580)[0m frame #5: c10d::ProcessGroupNCCL::HeartbeatMonitor::runLoop() + 0x398 (0x7f1fc32e3b18 in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cuda.so)[32m [repeated 35x across cluster][0m
[36m(WorkerDict pid=134586)[0m [rank7]:[W1104 07:52:01.755413688 ProcessGroupNCCL.cpp:1783] [PG ID 0 PG GUID 0(default_pg) Rank 7] Failed to check the "should dump" flag on TCPStore, (maybe TCPStore server has shut down too early), with error: Connection reset by peer[32m [repeated 6x across cluster]
```

**Comment by DBMing** [comment]
scripts
```
#!/usr/bin/env bash
set -x
ulimit -n 65535
export VLLM_ALLREDUCE_USE_SYMM_MEM=0 
export VLLM_USE_FLASH_ATTN=0
export VLLM_ATTENTION_BACKEND=TORCH_SDPA
# pip install shortuuid uuid



engine="vllm"
gpu_memory_utilization=0.6
train_prompt_bsz=32
n_resp_per_prompt=5
train_prompt_mini_bsz=16
train_prompt_micro_bsz=1
num_workers=8
max_assistant_turns=20
max_parallel_calls=5
nnodes=1
n_gpus_per_node=8
test_freq=20
save_freq=100
total_epochs=1

# Algorithm
temperature=0.6
top_p=0.95

# Performance Related Parameter
sp_size=2
offload=True
gen_tp=4

use_dynamic_bsz=True
max_prompt_length=$((1024 * 5))
max_response_length=$((1024 * 27))
actor_ppo_max_token_len=$(((max_prompt_length + max_response_length)))
infer_ppo_max_token_len=$(((max_prompt_length + max_response_length)))

use_kl_in_reward=False
use_kl_loss=True
kl_loss_coef=0.001


mkdir -p ${logdir}
mkdir -p ${modeldir}
logpath="${logdir}/master.log"


python3 -m verl.trainer.main_ppo \
    --config-path="$CONFIG_PATH" \
    --config-name='xxxx' \
    algorithm.adv_estimator=grpo \
    data.train_batch_size=${train_prompt_bsz} \
    data.val_batch_size=64 \
    data.max_prompt_length=${max_prompt_length} \
    data.max_response_length=${max_response_length} \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    data.return_raw_chat=True \
    data.image_key=images \
    actor_rollout_ref.model.path=${MODEL_PATH} \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=${train_prompt_mini_bsz} \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=${train_prompt_micro_bsz} \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=${actor_ppo_max_token_len} \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
    actor_rollout_ref.actor.use_kl_loss=${use_kl_loss} \
    actor_rollout_ref.actor.kl_loss_coef=${kl_loss_coef} \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=${offload} \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=${offload} \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=${train_prompt_micro_bsz} \
    actor_rollout_ref.rollout.tensor_model_parallel_size=${gen_tp} \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=${sp_size} \
    actor_rollout_ref.rollout.mode=async \
    actor_rollout_ref.rollout.name=${engine} \
    +actor_rollout_ref.rollout.engine_kwargs.vllm.disable_mm_preprocessor_cache=True \
    actor_rollout_ref.rollout.max_num_batched_tokens=$(((max_prompt_length + max_response_length))) \
    +actor_rollout_ref.rollout.engine_kwargs.vllm.max_model_len=$((1024 * 32)) \
    actor_rollout_ref.rollout.gpu_memory_utilization=${gpu_memory_utilization} \
    actor_rollout_ref.rollout.n=${n_resp_per_prompt} \
    actor_rollout_ref.rollout.temperature=${temperature} \
    actor_rollout_ref.rollout.top_p=${top_p} \
    actor_rollout_ref.rollout.agent.num_workers=${num_workers} \
    actor_rollout_ref.rollout.val_kwargs.temperature=${temperature} \
    actor_rollout_ref.rollout.val_kwargs.top_p=${top_p}\
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.n=1 \
    actor_rollout_ref.rollout.multi_turn.max_assistant_turns=${max_assistant_turns} \
    actor_rollout_ref.rollout.multi_turn.max_parallel_calls=${max_parallel_calls} \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=${train_prompt_micro_bsz} \
    actor_rollout_ref.ref.fsdp_config.param_offload=${offload} \
    algorithm.use_kl_in_reward=${use_kl_in_reward} \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name=${project_name} \
    trainer.experiment_name=${exp_name} \
    trainer.n_gpus_per_node=${n_gpus_per_node} \
    trainer.nnodes=${nnodes} \
    trainer.save_freq=${save_freq} \
    trainer.test_freq=${test_freq} \
    trainer.val_before_train=False \
    trainer.default_local_dir=${modeldir} \
    data.train_files=${train_files} \
    data.val_files=${val_files} \
    +data.add_now_time=True \
    +data.log_path=${logdir} \
    trainer.total_epochs=${total_epochs} 2>&1 | tee -a ${logpath}
```

**Comment by mantle2048** [comment]
hi, may I ask if there is any follow-up for this? I found that turning on the eager mode can run normally, but it will increase inference time

**Comment by DBMing** [comment]
> hi, may I ask if there is any follow-up for this? I found that turning on the eager mode can run normally, but it will increase inference time

Indeed, experiments showed that setting `actor_rollout_ref.rollout.enforce_eager=True` allows the program to run normally, but it does slow down the generation process. No other solution has been found yet.

**Comment by Necolizer** [comment]
Hi, I encountered the same error when using vLLM. Would switching to SGLang help?

**Comment by Kirrito-k423** [comment]
中文：我不建议把 SGLang 当作这个问题的确定修复，但可以作为一个有价值的对照实验。当前 issue 里的直接证据指向 vLLM / vllm-flash-attn Hopper TMA 路径：原始日志在 `/workspace/.deps/vllm-flash-attn-src/hopper/flash_fwd_launch_template.h:191` 报 illegal memory access；同一线程里也有用户确认 `actor_rollout_ref.rollout.enforce_eager=True` 可以正常运行但会降低生成速度。verl 当前支持把 rollout backend 切到 `actor_rollout_ref.rollout.name=sglang`，所以可以尝试 SGLang；但公开上游 issue 里也存在 SGLang/FlashInfer 的 TMA descriptor 报错，因此它不是可保证的 workaround。

建议先做三组最小对照：1. 当前 vLLM backend + `actor_rollout_ref.rollout.enforce_eager=True`；2. 升级到包含 vLLM TMA/stride 相关修复的较新 vLLM 版本后复测；3. 切到 `actor_rollout_ref.rollout.name=sglang` 后复测同一数据和同一 batch/sequence 配置。如果仍然复现，请补充完整的 verl commit/version、vLLM 或 SGLang 版本、GPU 型号、CUDA/driver/PyTorch 版本，以及是否启用了 prefix caching / CUDA graph / chunked prefill。

English: I would not treat SGLang as a confirmed fix for this issue, but it is a useful comparison run. The direct evidence in this thread points to the vLLM / vllm-flash-attn Hopper TMA path: the original log fails at `/workspace/.deps/vllm-flash-attn-src/hopper/flash_fwd_launch_template.h:191` with an illegal memory access, and another user confirmed that `actor_rollout_ref.rollout.enforce_eager=True` lets the job run, with slower generation. Current verl supports switching the rollout backend to `actor_rollout_ref.rollout.name=sglang`, so testing SGLang is reasonable; however, public upstream reports also show TMA descriptor failures in SGLang/FlashInfer paths, so it is not a guaranteed workaround.

Suggested minimal comparisons: 1. current vLLM backend with `actor_rollout_ref.rollout.enforce_eager=True`; 2. retest after upgrading to a newer vLLM that includes TMA/stride-related fixes; 3. retest the same workload with `actor_rollout_ref.rollout.name=sglang`. If it still reproduces, please share the exact verl commit/version, vLLM or SGLang version, GPU model, CUDA/driver/PyTorch versions, and whether prefix caching / CUDA graph / chunked prefill is enabled.

This response was generated by a scheduled Codex GPT5.5 issue processing task.
