### ISSUE TITLE
下面问题怎么解？最新版本verl，qwen3vl-30B-megatron

### ISSUE THREAD

**Issue by Feng0w0** [volcengine/verl#4301]
### System Info

(pid=2784599) WARNING 11-26 17:04:27 [api_server.py:1213] LoRA dynamic loading & unloading is enabled in the API server. This should ONLY be used for local development!
(pid=2784601) WARNING 11-26 17:04:28 [api_server.py:1213] LoRA dynamic loading & unloading is enabled in the API server. This should ONLY be used for local development!
(pid=2784599) /data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/megatron/core/models/backends.py:21: UserWarning: Apex is not installed. Falling back to Torch Norm
(pid=2784599)   warnings.warn("Apex is not installed. Falling back to Torch Norm")
(pid=2784599) /data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/megatron/core/models/gpt/gpt_layer_specs.py:67: UserWarning: Apex is not installed. Falling back to Torch Norm
(pid=2784599)   warnings.warn("Apex is not installed. Falling back to Torch Norm")
(vLLMHttpServer pid=2784599) ['serve',
(vLLMHttpServer pid=2784599)  '/home/l00937981/verl/ckpt/Qwen3-VL-30B-A3B-Instruct',
(vLLMHttpServer pid=2784599)  '--dtype',
(vLLMHttpServer pid=2784599)  'bfloat16',
(vLLMHttpServer pid=2784599)  '--load_format',
(vLLMHttpServer pid=2784599)  'dummy',
(vLLMHttpServer pid=2784599)  '--max_model_len',
(vLLMHttpServer pid=2784599)  '3072',
(vLLMHttpServer pid=2784599)  '--max_num_seqs',
(vLLMHttpServer pid=2784599)  '1024',
(vLLMHttpServer pid=2784599)  '--enable_chunked_prefill',
(vLLMHttpServer pid=2784599)  '--max_num_batched_tokens',
(vLLMHttpServer pid=2784599)  '8192',
(vLLMHttpServer pid=2784599)  '--enable_prefix_caching',
(vLLMHttpServer pid=2784599)  '--enable_sleep_mode',
(vLLMHttpServer pid=2784599)  '--disable_custom_all_reduce',
(vLLMHttpServer pid=2784599)  '--gpu_memory_utilization',
(vLLMHttpServer pid=2784599)  '0.7',
(vLLMHttpServer pid=2784599)  '--disable_log_stats',
(vLLMHttpServer pid=2784599)  '--tensor_parallel_size',
(vLLMHttpServer pid=2784599)  '4',
(vLLMHttpServer pid=2784599)  '--seed',
(vLLMHttpServer pid=2784599)  '0',
(vLLMHttpServer pid=2784599)  '--override_generation_config',
(vLLMHttpServer pid=2784599)  '{"temperature": 1.0, "top_k": -1, "top_p": 1, "repetition_penalty": 1.0, '
(vLLMHttpServer pid=2784599)  '"max_new_tokens": 2048}',
(vLLMHttpServer pid=2784599)  '--disable_mm_preprocessor_cache']
(vLLMHttpServer pid=2784599) INFO:2025-11-26 17:04:30,548:vLLMHttpServer, replica_rank: 0, master address: 90.91.103.34, master port: 41055, data parallel master port: 39285
(vLLMHttpServer pid=2784599) INFO:2025-11-26 17:04:30,565:override_generation_config: {'temperature': 1.0, 'top_k': -1, 'top_p': 1, 'repetition_penalty': 1.0, 'max_new_tokens': 2048}
(vLLMHttpServer pid=2784601) Using blocking ray.get inside async actor. This blocks the event loop. Please use `await` on object ref with asyncio.gather if you want to yield execution to the event loop instead.
(vLLMHttpServer pid=2784601) INFO:2025-11-26 17:04:30,589:replica_rank=1, node_rank=0, nnodes=1, get worker zmq addresses: ['ipc:///tmp/verl_vllm_zmq_2744998_root.ipc', 'ipc:///tmp/verl_vllm_zmq_2745011_root.ipc', 'ipc:///tmp/verl_vllm_zmq_2745004_root.ipc', 'ipc:///tmp/verl_vllm_zmq_2745018_root.ipc']
(vLLMHttpServer pid=2784601) WARNING 11-26 17:04:30 [__init__.py:1750] argument 'disable_mm_preprocessor_cache' is deprecated
(vLLMHttpServer pid=2784601) WARNING 11-26 17:04:30 [arg_utils.py:970] `--disable-mm-preprocessor-cache` is deprecated and will be removed in v0.13. Please use `--mm-processor-cache-gb 0` instead.
(vLLMHttpServer pid=2784601) `torch_dtype` is deprecated! Use `dtype` instead!
(vLLMHttpServer pid=2784601) WARNING 11-26 17:04:32 [__init__.py:3036] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: In a Ray actor and can only be spawned
(vLLMHttpServer pid=2784599) WARNING 11-26 17:04:42 [api_server.py:1213] LoRA dynamic loading & unloading is enabled in the API server. This should ONLY be used for local development!
(vLLMHttpServer pid=2784599) WARNING 11-26 17:04:30 [__init__.py:1750] argument 'disable_mm_preprocessor_cache' is deprecated
(vLLMHttpServer pid=2784599) WARNING 11-26 17:04:30 [arg_utils.py:970] `--disable-mm-preprocessor-cache` is deprecated and will be removed in v0.13. Please use `--mm-processor-cache-gb 0` instead.
(vLLMHttpServer pid=2784599) WARNING 11-26 17:04:32 [__init__.py:3036] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: In a Ray actor and can only be spawned
(vLLMHttpServer pid=2784601) WARNING 11-26 17:04:42 [api_server.py:1213] LoRA dynamic loading & unloading is enabled in the API server. This should ONLY be used for local development!
(vLLMHttpServer pid=2784599) /data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/megatron/core/models/backends.py:21: UserWarning: Apex is not installed. Falling back to Torch Norm [repeated 3x across cluster]
(vLLMHttpServer pid=2784599)   warnings.warn("Apex is not installed. Falling back to Torch Norm") [repeated 3x across cluster]
(vLLMHttpServer pid=2784601) INFO:2025-11-26 17:04:30,522:vLLMHttpServer, replica_rank: 1, master address: 90.91.103.34, master port: 34849, data parallel master port: 41699
(vLLMHttpServer pid=2784601) INFO:2025-11-26 17:04:30,542:override_generation_config: {'temperature': 1.0, 'top_k': -1, 'top_p': 1, 'repetition_penalty': 1.0, 'max_new_tokens': 2048}
(vLLMHttpServer pid=2784599) Using blocking ray.get inside async actor. This blocks the event loop. Please use `await` on object ref with asyncio.gather if you want to yield execution to the event loop instead.
(vLLMHttpServer pid=2784599) INFO:2025-11-26 17:04:30,609:replica_rank=0, node_rank=0, nnodes=1, get worker zmq addresses: ['ipc:///tmp/verl_vllm_zmq_2744959_root.ipc', 'ipc:///tmp/verl_vllm_zmq_2744971_root.ipc', 'ipc:///tmp/verl_vllm_zmq_2744981_root.ipc', 'ipc:///tmp/verl_vllm_zmq_2744988_root.ipc']
(vLLMHttpServer pid=2784599) `torch_dtype` is deprecated! Use `dtype` instead!
(WorkerDict pid=2744971) NCCL version 2.27.3+cuda12.9
(WorkerDict pid=2744971) [Gloo] Rank 1 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
(WorkerDict pid=2744981) WARNING 11-26 17:04:50 [topk_topp_sampler.py:66] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
(WorkerDict pid=2745004) WARNING 11-26 17:04:44 [api_server.py:1213] LoRA dynamic loading & unloading is enabled in the API server. This should ONLY be used for local development! [repeated 8x across cluster]
(WorkerDict pid=2745004) NCCL version 2.27.3+cuda12.9 [repeated 7x across cluster]
(WorkerDict pid=2745011) [Gloo] Rank 1 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3 [repeated 47x across cluster]
(WorkerDict pid=2744981) ERROR:2025-11-26 17:05:09,481:vLLMAsyncRollout _loop_forever error: CUDNN_BACKEND_TENSOR_DESCRIPTOR cudnnFinalize failedptrDesc->finalize() cudnn_status: CUDNN_STATUS_SUBLIBRARY_LOADING_FAILED
(WorkerDict pid=2744981) Traceback (most recent call last):
(WorkerDict pid=2744981)   File "/home/l00937981/verl/verl/verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py", line 585, in _loop_forever
(WorkerDict pid=2744981)     result = await self._execute_method(method, *args, **kwargs)
(WorkerDict pid=2744981)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/home/l00937981/verl/verl/verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py", line 627, in _execute_method
(WorkerDict pid=2744981)     return self.inference_engine.execute_method(method, *args, **kwargs)
(WorkerDict pid=2744981)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 276, in execute_method
(WorkerDict pid=2744981)     raise e
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 267, in execute_method
(WorkerDict pid=2744981)     return run_method(self, method, args, kwargs)
(WorkerDict pid=2744981)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/vllm/utils/__init__.py", line 3122, in run_method
(WorkerDict pid=2744981)     return func(*args, **kwargs)
(WorkerDict pid=2744981)            ^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(WorkerDict pid=2744981)     return func(*args, **kwargs)
(WorkerDict pid=2744981)            ^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/vllm/v1/worker/gpu_worker.py", line 263, in determine_available_memory
(WorkerDict pid=2744981)     self.model_runner.profile_run()
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/vllm/v1/worker/gpu_model_runner.py", line 3361, in profile_run
(WorkerDict pid=2744981)     self.model.get_multimodal_embeddings(
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/vllm/model_executor/models/qwen3_vl.py", line 1381, in get_multimodal_embeddings
(WorkerDict pid=2744981)     video_embeddings = self._process_video_input(multimodal_input)
(WorkerDict pid=2744981)                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/vllm/model_executor/models/qwen3_vl.py", line 1335, in _process_video_input
(WorkerDict pid=2744981)     video_embeds = self.visual(pixel_values_videos,
(WorkerDict pid=2744981)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(WorkerDict pid=2744981)     return self._call_impl(*args, **kwargs)
(WorkerDict pid=2744981)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(WorkerDict pid=2744981)     return forward_call(*args, **kwargs)
(WorkerDict pid=2744981)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/vllm/model_executor/models/qwen3_vl.py", line 492, in forward
(WorkerDict pid=2744981)     hidden_states = self.patch_embed(hidden_states)
(WorkerDict pid=2744981)                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(WorkerDict pid=2744981)     return self._call_impl(*args, **kwargs)
(WorkerDict pid=2744981)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(WorkerDict pid=2744981)     return forward_call(*args, **kwargs)
(WorkerDict pid=2744981)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/vllm/model_executor/models/qwen3_vl.py", line 119, in forward
(WorkerDict pid=2744981)     x = self.proj(x).view(L, self.hidden_size)
(WorkerDict pid=2744981)         ^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(WorkerDict pid=2744981)     return self._call_impl(*args, **kwargs)
(WorkerDict pid=2744981)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(WorkerDict pid=2744981)     return forward_call(*args, **kwargs)
(WorkerDict pid=2744981)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 717, in forward
(WorkerDict pid=2744981)     return self._conv_forward(input, self.weight, self.bias)
(WorkerDict pid=2744981)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(WorkerDict pid=2744981)   File "/data/anaconda3/envs/lh_verl_m/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 712, in _conv_forward
(WorkerDict pid=2744981)     return F.conv3d(
(WorkerDict pid=2744981)            ^^^^^^^^^
(WorkerDict pid=2744981) RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR cudnnFinalize failedptrDesc->finalize() cudnn_status: CUDNN_STATUS_SUBLIBRARY_LOADING_FAILED

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

SOCKET_IFNAME=$(ip addr | grep 'inet 90.91.103.' | awk -F " " '{print$NF}')

export HCCL_SOCKET_IFNAME=$SOCKET_IFNAME
export GLOO_SOCKET_IFNAME=$SOCKET_IFNAME

set -x
ulimit -n 32768
ENGINE=${1:-vllm}
export CUDA_DEVICE_MAX_CONNECTIONS=1 # For megatron communication/computation overlapping
export CUDA_HOME='/usr/local/cuda-12.4'
export VLLM_ALLREDUCE_USE_SYMM_MEM=0 # for vllm0.11.0 with TP

GEN_TP=${GEN_TP:-4}
CP=${CP:-2}
TP=${TP:-2}
PP=${PP:-1}
EP=${EP:-8}
ETP=${ETP:-1}

HF_MODEL_PATH=/home/l00937981/verl/ckpt/Qwen3-VL-30B-A3B-Instruct

train_path=/home/l00937981/verl/data/geo3k/train.parquet
test_path=/home/l00937981/verl/data/geo3k/test.parquet

python3 -m verl.trainer.main_ppo --config-path=config \
    --config-name='ppo_megatron_trainer.yaml'\
    algorithm.adv_estimator=grpo \
    data.train_files="$train_path" \
    data.val_files="$test_path" \
    data.train_batch_size=32 \
    data.max_prompt_length=1024 \
    data.max_response_length=2048 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    actor_rollout_ref.model.path=$HF_MODEL_PATH \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=8 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.megatron.pipeline_model_parallel_size=$PP \
    actor_rollout_ref.actor.megatron.tensor_model_parallel_size=$TP \
    actor_rollout_ref.actor.megatron.context_parallel_size=$CP \
    actor_rollout_ref.actor.megatron.expert_model_parallel_size=$EP \
    actor_rollout_ref.actor.megatron.expert_tensor_parallel_size=$ETP \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.01 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=$GEN_TP \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=4096 \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=4096 \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=4096 \
    actor_rollout_ref.rollout.name=$ENGINE \
    +actor_rollout_ref.rollout.engine_kwargs.vllm.disable_mm_preprocessor_cache=True \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
    actor_rollout_ref.rollout.n=5 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.megatron.use_mbridge=True \
    actor_rollout_ref.actor.megatron.param_offload=True \
    actor_rollout_ref.actor.megatron.optimizer_offload=True \
    actor_rollout_ref.actor.megatron.grad_offload=True \
    actor_rollout_ref.ref.megatron.param_offload=True \
    +actor_rollout_ref.actor.optim.override_optimizer_config.optimizer_offload_fraction=1 \
    +actor_rollout_ref.actor.optim.override_optimizer_config.overlap_cpu_optimizer_d2h_h2d=True \
    +actor_rollout_ref.actor.optim.override_optimizer_config.use_precision_aware_optimizer=True \
    +actor_rollout_ref.actor.optim.override_optimizer_config.optimizer_cpu_offload=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.moe_router_dtype=fp32 \
    +actor_rollout_ref.actor.megatron.override_transformer_config.moe_enable_deepep=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.moe_token_dispatcher_type=flex \
    +actor_rollout_ref.actor.megatron.override_transformer_config.recompute_method=uniform \
    +actor_rollout_ref.actor.megatron.override_transformer_config.recompute_granularity=full \
    +actor_rollout_ref.actor.megatron.override_transformer_config.recompute_num_layers=1 \
    +actor_rollout_ref.actor.megatron.override_transformer_config.gradient_accumulation_fusion=False \
    +actor_rollout_ref.actor.megatron.override_transformer_config.moe_permute_fusion=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.moe_aux_loss_coeff=0.01 \
    +actor_rollout_ref.actor.megatron.override_transformer_config.moe_z_loss_coeff=0.001 \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger='["console"]' \
    trainer.project_name='verl_grpo_example_geo3k' \
    trainer.experiment_name='qwen3_vl_30b_megatron' \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=20 \
    trainer.test_freq=5 \
    trainer.total_epochs=15 $@

### Expected behavior

H20上没遇到这个问题，H100遇到的

**Comment by ISEEKYAN** [comment]
looks like something wrong with cuDNN lib, are you using the same docker image?

**Comment by EchoMinkki** [comment]
May I ask if you have resolved this issue now? I have encountered the same issue on qwen3-vl-8B-instruct.

**Comment by rongbaoo** [comment]
I have encountered the same issue on qwen3-vl-8B-Thinking.

**Comment by weigao266** [comment]
I have encountered the same issue on qwen3-vl-4B-thinking. Did anyone have a solution?

**Comment by Winter-Jon** [comment]
`pip install nvidia-cudnn-cu12==8.9.2.26` works for me.

**Comment by jasonyux** [comment]
`pip uninstall nvidia-cudnn-cu12` worked for me
