### ISSUE TITLE
vllm开启dp和ep在npu上报错

### ISSUE THREAD

**Issue by glowwormX** [volcengine/verl#4413]
运行30b
开启：
```
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.data_parallel_size=2 \
    actor_rollout_ref.rollout.expert_parallel_size=4 \
```

a2上我希望运行235b tp=8 dp=2，或者其他性能更高的切分策略，先在30b上测试结果报错了; 而去除dp ep正常运行，使用fsdp、megatron均报错

verl11.18代码 51d2104ecb61563c41123a8f0bce2f06b18387dc
vllm 0.11.0.rc2 
cann8.3.rc2

日志：
```
[36m(WorkerDict pid=3381096)[0m INFO 12-04 17:33:17 [layer.py:332] FlashInfer CUTLASS MoE is currently not available for DP.
[36m(WorkerDict pid=3381096)[0m INFO 12-04 17:33:17 [common_fused_moe.py:239] [EP Rank 3/4] Expert parallelism is enabled. Local/global number of experts: 32/128. Experts local to global index map: 0->96, 1->97, 2->98, 3->99, 4->100, 5->101, 6->102, 7->103, 8->104, 9->105, 10->106, 11->107, 12->108, 13->109, 14->110, 15->111, 16->112, 17->113, 18->114, 19->115, 20->116, 21->117, 22->118, 23->119, 24->120, 25->121, 26->122, 27->123, 28->124, 29->125, 30->126, 31->127.
[36m(WorkerDict pid=3381075)[0m INFO 12-04 17:33:17 [layer.py:1052] [EP Rank 2/4] Expert parallelism is enabled. Expert placement strategy: linear. Local/global number of experts: 32/128. Experts local to global index map: 0->64, 1->65, 2->66, 3->67, 4->68, 5->69, 6->70, 7->71, 8->72, 9->73, 10->74, 11->75, 12->76, 13->77, 14->78, 15->79, 16->80, 17->81, 18->82, 19->83, 20->84, 21->85, 22->86, 23->87, 24->88, 25->89, 26->90, 27->91, 28->92, 29->93, 30->94, 31->95.
[36m(WorkerDict pid=3381075)[0m INFO 12-04 17:33:17 [layer.py:332] FlashInfer CUTLASS MoE is currently not available for DP.
[36m(WorkerDict pid=3381075)[0m INFO 12-04 17:33:17 [common_fused_moe.py:239] [EP Rank 2/4] Expert parallelism is enabled. Local/global number of experts: 32/128. Experts local to global index map: 0->64, 1->65, 2->66, 3->67, 4->68, 5->69, 6->70, 7->71, 8->72, 9->73, 10->74, 11->75, 12->76, 13->77, 14->78, 15->79, 16->80, 17->81, 18->82, 19->83, 20->84, 21->85, 22->86, 23->87, 24->88, 25->89, 26->90, 27->91, 28->92, 29->93, 30->94, 31->95.
[36m(WorkerDict pid=3381089)[0m INFO 12-04 17:33:19 [model_runner_v1.py:2667] Loading model weights took 14.9573 GB
[36m(WorkerDict pid=3381096)[0m INFO 12-04 17:33:19 [model_runner_v1.py:2667] Loading model weights took 14.9573 GB
[36m(WorkerDict pid=3381093)[0m INFO 12-04 17:33:19 [model_runner_v1.py:2667] Loading model weights took 14.9573 GB
[36m(WorkerDict pid=3381094)[0m INFO 12-04 17:33:19 [model_runner_v1.py:2667] Loading model weights took 14.9573 GB
[36m(WorkerDict pid=3381073)[0m INFO 12-04 17:33:19 [model_runner_v1.py:2667] Loading model weights took 14.9573 GB
[36m(WorkerDict pid=3381076)[0m INFO 12-04 17:33:20 [model_runner_v1.py:2667] Loading model weights took 14.9573 GB
[36m(WorkerDict pid=3381074)[0m INFO 12-04 17:33:20 [model_runner_v1.py:2667] Loading model weights took 14.9573 GB
[36m(WorkerDict pid=3381089)[0m WARNING 12-04 17:33:20 [cudagraph_dispatcher.py:106] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[36m(WorkerDict pid=3381093)[0m WARNING 12-04 17:33:20 [cudagraph_dispatcher.py:106] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[36m(WorkerDict pid=3381094)[0m WARNING 12-04 17:33:20 [cudagraph_dispatcher.py:106] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[36m(WorkerDict pid=3381096)[0m WARNING 12-04 17:33:20 [cudagraph_dispatcher.py:106] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[36m(WorkerDict pid=3381075)[0m INFO 12-04 17:33:21 [model_runner_v1.py:2667] Loading model weights took 14.9573 GB
[36m(WorkerDict pid=3381074)[0m WARNING 12-04 17:33:21 [cudagraph_dispatcher.py:106] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[36m(WorkerDict pid=3381076)[0m WARNING 12-04 17:33:21 [cudagraph_dispatcher.py:106] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[36m(WorkerDict pid=3381073)[0m WARNING 12-04 17:33:22 [cudagraph_dispatcher.py:106] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[36m(WorkerDict pid=3381075)[0m WARNING 12-04 17:33:22 [cudagraph_dispatcher.py:106] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275] Error executing method 'determine_available_memory'. This might cause deadlock in distributed execution.
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275] Traceback (most recent call last):
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 267, in execute_method
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return run_method(self, method, args, kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm/utils/__init__.py", line 3122, in run_method
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return func(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm_ascend/worker/worker_v1.py", line 227, in determine_available_memory
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     self.model_runner.profile_run()
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm_ascend/worker/model_runner_v1.py", line 2530, in profile_run
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     hidden_states = self._dummy_run(self.max_num_tokens,
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return func(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm_ascend/worker/model_runner_v1.py", line 2493, in _dummy_run
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     hidden_states = self._generate_dummy_run_hidden_states(
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm_ascend/worker/model_runner_v1.py", line 2314, in _generate_dummy_run_hidden_states
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     hidden_states = self.model(input_ids=input_ids,
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm_ascend/compilation/acl_graph.py", line 113, in __call__
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return self.runnable(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return self._call_impl(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return forward_call(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_moe.py", line 675, in forward
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     hidden_states = self.model(input_ids, positions, intermediate_tensors,
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm/compilation/decorators.py", line 310, in __call__
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     output = self.compiled_callable(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/home/ma-user/work/dataset/x30059842_wulan/x30059842/verl/verl_1118/MindSpeed/mindspeed/core/megatron_basic/requirements_basic.py", line 93, in wrapper
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return args[0](*fn_args, **fn_kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_moe.py", line 421, in forward
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     hidden_states, residual = layer(positions, hidden_states, residual)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return self._call_impl(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return forward_call(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_moe.py", line 365, in forward
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     hidden_states = self.mlp(hidden_states)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return self._call_impl(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return forward_call(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_moe.py", line 174, in forward
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     final_hidden_states = self.experts(hidden_states=hidden_states,
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return self._call_impl(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return forward_call(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm/model_executor/custom_op.py", line 44, in forward
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return self._forward_method(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm/model_executor/custom_op.py", line 79, in forward_oot
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return self.forward_native(*args, **kwargs)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 1827, in forward_native
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     fused_output = torch.ops.vllm.moe_forward(
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/torch/_ops.py", line 1158, in __call__
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return self._op(*args, **(kwargs or {}))
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 2144, in moe_forward
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     return self.forward_impl(hidden_states, router_logits)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm_ascend/ops/common_fused_moe.py", line 319, in forward_impl
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     hidden_states, router_logits = forward_context.moe_comm_method.prepare(
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm_ascend/ops/moe/moe_comm_method.py", line 73, in prepare
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     hidden_states, router_logits, mc2_mask = self.fused_moe_prepare_finalize.prepare(
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm_ascend/ops/moe/fused_moe_prepare_and_finalize.py", line 489, in prepare
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     hidden_states = self._naive_multicast(hidden_states,
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]   File "/cache/verl_1118_env_main_py310_vllm_v11_rc2_unpack/lib/python3.10/site-packages/vllm_ascend/ops/moe/fused_moe_prepare_and_finalize.py", line 460, in _naive_multicast
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]     buffer[start:end, :].copy_(x)
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275] RuntimeError: copy_d2d_baseformat_opapi:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:88 NPU function error: call aclnnInplaceCopy failed, error code is 161002
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275] [ERROR] 2025-12-04-17:33:31 (PID:3381073, Device:0, RankID:0) ERR00100 PTA call acl api failed.
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275] [PID: 3381073] 2025-12-04-17:33:31.901.291 AclNN_Parameter_Error(EZ1001): 4096 and 8192 cannot broadcast.
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]         TraceBack (most recent call last):
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275]         The size of tensor self [8192, 2048] must match the size of tensor src [4096, 2048].
[36m(WorkerDict pid=3381073)[0m ERROR 12-04 17:33:31 [worker_base.py:275] 
```

**Comment by Yikun** [comment]
@FightingZhen

**Comment by FightingZhen** [comment]
@glowwormX 由于issue未充分提及你实际运行的环境、脚本、配置等相关信息，我在verl仓库中搜索`actor_rollout_ref.rollout.expert_parallel_size`关键词，发现GSPO算法下的`test_gspo_qwen30b_a3b_ep.sh`进行了该配置，于是基于该脚本进行测试。

**实验发现可以正常跑出一个完整的step，并未出现上述报错现象**，我将尽可能的还原我测试的环境和相关信息给你，希望能对你有所帮助。

**测试环境：**
- 硬件设备：Atlas 800T A3
- 驱动：25.2.0 ( npu-smi info 左上角 )
- CANN：25.2.0 ( /usr/local/Ascend/version.info )
- verl commit-id：5eedbae
- torch/transformers/vllm/vllm-ascend等其他软件安装参考：https://github.com/volcengine/verl/blob/main/docs/ascend_tutorial/ascend_quick_start.rst
- 额外单独安装：mbridge==0.15.1

**训练配置：**
- 模型：Qwen3-30B-A3B-Base，模型减层处理（HF模型文件下 config.json 中， num_hidden_layers 由48调整为12）
- 数据集：训练使用 dapo-math-17k，验证使用 aime-2024
- 卡数：8卡
- 受到卡数限制，batch_size、prompt/response length、rollout_n等超参数均调整到比较小的数值，详情可参考下面的执行脚本

**测试脚本：**
```shell
#!/usr/bin/env bash
set -xeuo pipefail

export VLLM_ASCEND_ENABLE_NZ=0
export HCCL_BUFFSIZE=2048
export ASCEND_RT_VISIBLE_DEVICES=8,9,10,11,12,13,14,15
export NCCL_DEBUG=WARN
# export VERL_LOGGING_LEVEL=DEBUG

project_name='DAPO'
exp_name='GSPO-Qwen3-30B-A3B-Base-MATH'

adv_estimator=grpo

use_kl_in_reward=False
kl_coef=0.0
use_kl_loss=False
kl_loss_coef=0.0

clip_ratio_low=3e-4
clip_ratio_high=4e-4

max_prompt_length=$((1024 * 1))
max_response_length=$((1024 * 2))
enable_overlong_buffer=True
overlong_buffer_len=$((512))
overlong_penalty_factor=1.0

loss_agg_mode="token-mean"
loss_mode=gspo

train_prompt_bsz=64
n_resp_per_prompt=2
train_prompt_mini_bsz=16

# Ray
# RAY_ADDRESS=${RAY_ADDRESS:-"http://localhost:8265"}
# WORKING_DIR=${WORKING_DIR:-"${PWD}"}
# RUNTIME_ENV=${RUNTIME_ENV:-"${WORKING_DIR}/verl/trainer/runtime_env.yaml"}
NNODES=${NNODES:-1}
NGPUS_PER_NODE=${NGPUS_PER_NODE:-8}
# Paths
# RAY_DATA_HOME=${RAY_DATA_HOME:-"${HOME}/verl"}
# MODEL_PATH=${MODEL_PATH:-"${RAY_DATA_HOME}/models/Qwen3-30B-A3B-Base"}
# CKPTS_DIR=${CKPTS_DIR:-"${RAY_DATA_HOME}/ckpts/${project_name}/${exp_name}"}
# TRAIN_FILE=${TRAIN_FILE:-"${RAY_DATA_HOME}/data/dapo-math-17k.parquet"}
# TEST_FILE=${TEST_FILE:-"${RAY_DATA_HOME}/data/aime-2024.parquet"}

#MODEL_PATH=$HDFS_ROOT/model/Qwen3-30B-A3B-Base
#CKPTS_DIR=$DATA_ROOT/checkpoint/${project_name}/${exp_name}
#TRAIN_FILE=$DATA_ROOT/dataset/BytedTsinghua-SIA/DAPO-Math-17k/data/dapo-math-17k.parquet
#aime24_test_path=$DATA_ROOT/dataset/aime-2024.parquet

MODEL_PATH=/home/fighting_zhen/playground/models/Qwen3_30B_A3B_Base
CKPTS_DIR=/home/fighting_zhen/playground/verl_checkpoint/${project_name}/${exp_name}
TRAIN_FILE=/home/fighting_zhen/playground/datasets/DAPO_Math_17k/data/dapo-math-17k.parquet
aime24_test_path=/home/fighting_zhen/playground/datasets/AIME-2024/data/aime-2024.parquet

TEST_FILE="['$aime24_test_path']"

# Algorithm
temperature=1.0
top_p=1.0
top_k=-1 # 0 for HF rollout, -1 for vLLM rollout
val_top_p=0.7

# Performance Related Parameter
use_dynamic_bsz=True
actor_ppo_max_token_len=$(((max_prompt_length + max_response_length) * 1))
infer_ppo_max_token_len=$(((max_prompt_length + max_response_length) * 1))
offload=True

# gen
rollout_name=vllm # vllm or sglang
if [ "$rollout_name" = "vllm" ]; then
    export VLLM_USE_V1=1
fi
gen_tp=2
gen_dp=2
gen_ep=4

# train
train_tp=2
train_pp=1
EP=4
ETP=1

python3 -m verl.trainer.main_ppo \
    --config-path=config \
    --config-name='ppo_megatron_trainer.yaml' \
    data.train_files="${TRAIN_FILE}" \
    data.val_files="${TEST_FILE}" \
    data.prompt_key=prompt \
    data.return_raw_chat=True \
    data.truncation='left' \
    data.max_prompt_length=${max_prompt_length} \
    data.max_response_length=${max_response_length} \
    data.train_batch_size=${train_prompt_bsz} \
    actor_rollout_ref.rollout.n=${n_resp_per_prompt} \
    actor_rollout_ref.actor.policy_loss.loss_mode=${loss_mode} \
    algorithm.adv_estimator=${adv_estimator} \
    algorithm.use_kl_in_reward=${use_kl_in_reward} \
    algorithm.kl_ctrl.kl_coef=${kl_coef} \
    actor_rollout_ref.actor.use_kl_loss=${use_kl_loss} \
    actor_rollout_ref.actor.kl_loss_coef=${kl_loss_coef} \
    actor_rollout_ref.actor.clip_ratio_low=${clip_ratio_low} \
    actor_rollout_ref.actor.clip_ratio_high=${clip_ratio_high} \
    actor_rollout_ref.actor.clip_ratio_c=10.0 \
    actor_rollout_ref.actor.use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=${actor_ppo_max_token_len} \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
    actor_rollout_ref.model.path="${MODEL_PATH}" \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps=10 \
    actor_rollout_ref.actor.optim.weight_decay=0.1 \
    actor_rollout_ref.actor.ppo_mini_batch_size=${train_prompt_mini_bsz} \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.optim.clip_grad=1.0 \
    actor_rollout_ref.actor.loss_agg_mode=${loss_agg_mode} \
    actor_rollout_ref.actor.megatron.param_offload=${offload} \
    actor_rollout_ref.actor.megatron.optimizer_offload=${offload} \
    actor_rollout_ref.actor.megatron.grad_offload=${offload} \
    actor_rollout_ref.actor.megatron.pipeline_model_parallel_size=${train_pp} \
    actor_rollout_ref.actor.megatron.tensor_model_parallel_size=${train_tp} \
    actor_rollout_ref.actor.megatron.expert_model_parallel_size=$EP \
    actor_rollout_ref.actor.megatron.expert_tensor_parallel_size=$ETP \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.80 \
    actor_rollout_ref.rollout.enable_chunked_prefill=True \
    actor_rollout_ref.rollout.max_num_batched_tokens=$((max_prompt_length + max_response_length)) \
    actor_rollout_ref.rollout.temperature=${temperature} \
    actor_rollout_ref.rollout.top_p=${top_p} \
    actor_rollout_ref.rollout.top_k=${top_k} \
    actor_rollout_ref.rollout.val_kwargs.temperature=${temperature} \
    actor_rollout_ref.rollout.val_kwargs.top_p=${val_top_p} \
    actor_rollout_ref.rollout.val_kwargs.top_k=${top_k} \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.n=1 \
    actor_rollout_ref.rollout.name=${rollout_name} \
    actor_rollout_ref.rollout.mode=async \
    actor_rollout_ref.rollout.calculate_log_probs=True \
    actor_rollout_ref.rollout.tensor_model_parallel_size=${gen_tp} \
    actor_rollout_ref.rollout.data_parallel_size=${gen_dp} \
    actor_rollout_ref.rollout.expert_parallel_size=${gen_ep} \
    actor_rollout_ref.ref.megatron.pipeline_model_parallel_size=${train_pp} \
    actor_rollout_ref.ref.megatron.tensor_model_parallel_size=${train_tp} \
    actor_rollout_ref.ref.megatron.expert_model_parallel_size=$EP \
    actor_rollout_ref.ref.megatron.expert_tensor_parallel_size=$ETP \
    actor_rollout_ref.ref.megatron.param_offload=${offload} \
    actor_rollout_ref.actor.megatron.use_mbridge=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.apply_rope_fusion=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.moe_router_dtype=fp32 \
    +actor_rollout_ref.actor.megatron.override_transformer_config.recompute_method=uniform \
    +actor_rollout_ref.actor.megatron.override_transformer_config.recompute_granularity=full \
    +actor_rollout_ref.actor.megatron.override_transformer_config.recompute_num_layers=1 \
    +actor_rollout_ref.actor.megatron.override_transformer_config.gradient_accumulation_fusion=True \
    +actor_rollout_ref.actor.megatron.override_transformer_config.moe_permute_fusion=True \
    reward_model.reward_manager=dapo \
    +reward_model.reward_kwargs.overlong_buffer_cfg.enable=${enable_overlong_buffer} \
    +reward_model.reward_kwargs.overlong_buffer_cfg.len=${overlong_buffer_len} \
    +reward_model.reward_kwargs.overlong_buffer_cfg.penalty_factor=${overlong_penalty_factor} \
    +reward_model.reward_kwargs.overlong_buffer_cfg.log=False \
    +reward_model.reward_kwargs.max_resp_len=${max_response_length} \
    trainer.logger='["console"]' \
    trainer.project_name="${project_name}" \
    trainer.experiment_name="${exp_name}-tp${gen_tp}-ep${gen_ep}" \
    trainer.n_gpus_per_node="${NGPUS_PER_NODE}" \
    trainer.nnodes="${NNODES}" \
    trainer.val_before_train=False \
    trainer.test_freq=10 \
    trainer.save_freq=30 \
    trainer.total_epochs=10 \
    trainer.total_training_steps=300 \
    trainer.default_local_dir="${CKPTS_DIR}" \
    trainer.resume_mode=auto \
    trainer.log_val_generations=10 \
    trainer.device=npu \
    +actor_rollout_ref.actor.megatron.override_transformer_config.use_flash_attn=True
```

**复现结果：可以跑出第一个step**
<img width="2304" height="260" alt="Image" src="https://github.com/user-attachments/assets/e1c0ca15-ea98-48e0-92a3-4794a66dc286" />

**Comment by glowwormX** [comment]
我使用了您的脚本，以及按https://github.com/volcengine/verl/blob/main/docs/ascend_tutorial/ascend_quick_start.rst重新安装了环境，除了Atlas 800T A3、驱动：25.2.0不同，其他均保持一致了，但是仍然报相同的错。
请问可以提供下可以跑出第一个step的环境吗，比如：pip freeze > pip_env.txt，我再对比下

**Comment by mikequan0425** [comment]
@glowwormX I encountered the same problem and would like to ask if you have found the root cause of it and if there is a corresponding solution.

**Comment by glowwormX** [comment]
No. I still haven't solved this problem. I can only disable dp and ep.

> [@glowwormX](https://github.com/glowwormX) I encountered the same problem and would like to ask if you have found the root cause of it and if there is a corresponding solution.

**Comment by mikequan0425** [comment]
@glowwormX Add VLLM_ALL2ALL_BACKEND: "flashinfer_all2allv" in runtime.yaml. Doing this can temporarily circumvent the issue. The default value in vllm-ascend will trigger the tp logic, which in turn causes this error.

**Comment by glowwormX** [comment]
OK thanks, I'll try it

> [@glowwormX](https://github.com/glowwormX) Add VLLM_ALL2ALL_BACKEND: "flashinfer_all2allv" in runtime.yaml. Doing this can temporarily circumvent the issue. The default value in vllm-ascend will trigger the tp logic, which in turn causes this error.

**Comment by glowwormX** [comment]
> [@glowwormX](https://github.com/glowwormX) Add VLLM_ALL2ALL_BACKEND: "flashinfer_all2allv" in runtime.yaml. Doing this can temporarily circumvent the issue. The default value in vllm-ascend will trigger the tp logic, which in turn causes this error.

Already solved. Thank you very much.
