### ISSUE TITLE
Stuck after logging NCCL version, before logging model size

### ISSUE THREAD

**Issue by JunzheShen** [volcengine/verl#597]
Here is the full error message, the code is executed on slurm. It doesn't happen if I ran it on my local server
```
(WorkerDict pid=231421) [rank1]:[E314 14:33:45.172185860 ProcessGroupNCCL.cpp:607] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600009 milliseconds before timing out.
(WorkerDict pid=231421) [rank1]:[E314 14:33:45.173249001 ProcessGroupNCCL.cpp:1664] [PG 0 (default_pg) Rank 1] Exception (either an error or timeout) detected by watchdog at work: 1, last enqueued NCCL work: 1, last completed NCCL work: -1.
(WorkerDict pid=231421) [rank1]:[E314 14:33:45.173272575 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 1] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: -1.
(WorkerDict pid=231421) [rank1]:[E314 14:33:45.173281853 ProcessGroupNCCL.cpp:621] [Rank 1] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
(WorkerDict pid=231421) [rank1]:[E314 14:33:45.173286882 ProcessGroupNCCL.cpp:627] [Rank 1] To avoid data inconsistency, we are taking the entire process down.
(WorkerDict pid=231421) [rank1]:[E314 14:33:45.174821690 ProcessGroupNCCL.cpp:1515] [PG 0 (default_pg) Rank 1] Process group watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600009 milliseconds before timing out.
(WorkerDict pid=231421) Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:609 (most recent call first):
(WorkerDict pid=231421) frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f0e3833cf86 in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libc10.so)
(WorkerDict pid=231421) frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7edee3a1b8d2 in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=231421) frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7edee3a22313 in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=231421) frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7edee3a246fc in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=231421) frame #4: <unknown function> + 0xdbbf4 (0x7f0e9ea17bf4 in /data1/jzshen/miniconda3/envs/searchr1/bin/../lib/libstdc++.so.6)
(WorkerDict pid=231421) frame #5: <unknown function> + 0x77bd (0x7f0ea7c977bd in /lib64/libpthread.so.0)
(WorkerDict pid=231421) frame #6: clone + 0x3f (0x7f0ea72806bf in /lib64/libc.so.6)
(WorkerDict pid=231421) 
(WorkerDict pid=231421) /home/jzshen/Search-R1/verl/utils/tokenizer.py:29: UserWarning: tokenizer.pad_token_id is None. Now set to 128009
(WorkerDict pid=231421)   warnings.warn(f'tokenizer.pad_token_id is None. Now set to {tokenizer.eos_token_id}')
(WorkerDict pid=231421) You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
(WorkerDict pid=231421) [2025-03-14 14:33:45,121 E 231421 231589] logging.cc:113: Unhandled exception: N3c1016DistBackendErrorE. what(): [PG 0 (default_pg) Rank 1] Process group watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600009 milliseconds before timing out.
(WorkerDict pid=231421) Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:609 (most recent call first):
(WorkerDict pid=231421) frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f0e3833cf86 in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libc10.so)
(WorkerDict pid=231421) frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7edee3a1b8d2 in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=231421) frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7edee3a22313 in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=231421) frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7edee3a246fc in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=231421) frame #4: <unknown function> + 0xdbbf4 (0x7f0e9ea17bf4 in /data1/jzshen/miniconda3/envs/searchr1/bin/../lib/libstdc++.so.6)
(WorkerDict pid=231421) frame #5: <unknown function> + 0x77bd (0x7f0ea7c977bd in /lib64/libpthread.so.0)
(WorkerDict pid=231421) frame #6: clone + 0x3f (0x7f0ea72806bf in /lib64/libc.so.6)
(WorkerDict pid=231421) 
(WorkerDict pid=231421) Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1521 (most recent call first):
(WorkerDict pid=231421) frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f0e3833cf86 in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libc10.so)
(WorkerDict pid=231421) frame #1: <unknown function> + 0xe5aa84 (0x7edee36ada84 in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
(WorkerDict pid=231421) frame #2: <unknown function> + 0xdbbf4 (0x7f0e9ea17bf4 in /data1/jzshen/miniconda3/envs/searchr1/bin/../lib/libstdc++.so.6)
(WorkerDict pid=231421) frame #3: <unknown function> + 0x77bd (0x7f0ea7c977bd in /lib64/libpthread.so.0)
(WorkerDict pid=231421) frame #4: clone + 0x3f (0x7f0ea72806bf in /lib64/libc.so.6)
(WorkerDict pid=231421) 
(WorkerDict pid=230966) 
(WorkerDict pid=230966) 
(WorkerDict pid=230966) 
(WorkerDict pid=230966) [2025-03-14 14:33:45,211 E 230966 231591] logging.cc:120: Stack trace: 
(WorkerDict pid=230966)  /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/ray/_raylet.so(+0x13aa8ea) [0x7f58dc4ec8ea] ray::operator<<()
(WorkerDict pid=230966) /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/ray/_raylet.so(+0x13ae022) [0x7f58dc4f0022] ray::TerminateHandler()
(WorkerDict pid=230966) /data1/jzshen/miniconda3/envs/searchr1/bin/../lib/libstdc++.so.6(+0xb135a) [0x7f58dadc635a] __cxxabiv1::__terminate()
(WorkerDict pid=230966) /data1/jzshen/miniconda3/envs/searchr1/bin/../lib/libstdc++.so.6(+0xb13c5) [0x7f58dadc63c5]
(WorkerDict pid=230966) /data1/jzshen/miniconda3/envs/searchr1/bin/../lib/libstdc++.so.6(+0xb134f) [0x7f58dadc634f]
(WorkerDict pid=230966) /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so(+0xe5ab35) [0x7f291f6adb35] c10d::ProcessGroupNCCL::ncclCommWatchdog()
(WorkerDict pid=230966) /data1/jzshen/miniconda3/envs/searchr1/bin/../lib/libstdc++.so.6(+0xdbbf4) [0x7f58dadf0bf4] execute_native_thread_routine
(WorkerDict pid=230966) /lib64/libpthread.so.0(+0x77bd) [0x7f58e40707bd] start_thread
(WorkerDict pid=230966) /lib64/libc.so.6(clone+0x3f) [0x7f58e36596bf] clone
(WorkerDict pid=230966) 
(WorkerDict pid=230966) *** SIGABRT received at time=1741934025 on cpu 58 ***
(WorkerDict pid=230966) PC: @     0x7f58e359a3ba  (unknown)  raise
(WorkerDict pid=230966)     @     0x7f58e407b7e0       4704  (unknown)
(WorkerDict pid=230966)     @     0x7f58dadc635a  (unknown)  __cxxabiv1::__terminate()
(WorkerDict pid=230966)     @     0x7f58dadc6070  (unknown)  (unknown)
(WorkerDict pid=230966) [2025-03-14 14:33:45,215 E 230966 231591] logging.cc:484: *** SIGABRT received at time=1741934025 on cpu 58 ***
(WorkerDict pid=230966) [2025-03-14 14:33:45,215 E 230966 231591] logging.cc:484: PC: @     0x7f58e359a3ba  (unknown)  raise
(WorkerDict pid=230966) [2025-03-14 14:33:45,215 E 230966 231591] logging.cc:484:     @     0x7f58e407b7e0       4704  (unknown)
(WorkerDict pid=230966) [2025-03-14 14:33:45,215 E 230966 231591] logging.cc:484:     @     0x7f58dadc635a  (unknown)  __cxxabiv1::__terminate()
(WorkerDict pid=230966) [2025-03-14 14:33:45,215 E 230966 231591] logging.cc:484:     @     0x7f58dadc6070  (unknown)  (unknown)
(WorkerDict pid=230966) Fatal Python error: Aborted
(WorkerDict pid=230966) 
(WorkerDict pid=231421) /data1/jzshen/miniconda3/envs/searchr1/bin/../lib/libstdc++.so.6(+0xb135a) [0x7f0e9e9ed35a] __cxxabiv1::__terminate()
(WorkerDict pid=231421) /data1/jzshen/miniconda3/envs/searchr1/bin/../lib/libstdc++.so.6(+0xb13c5) [0x7f0e9e9ed3c5]
(WorkerDict pid=231421) /data1/jzshen/miniconda3/envs/searchr1/bin/../lib/libstdc++.so.6(+0xb134f) [0x7f0e9e9ed34f]
(WorkerDict pid=231421) /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so(+0xe5ab35) [0x7edee36adb35] c10d::ProcessGroupNCCL::ncclCommWatchdog()
(WorkerDict pid=231421) 
(WorkerDict pid=231421) 
(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffe5acd21bed6fbed2047802f301000000 Worker ID: 6d9147403fa84ea6d30428c1623df5716a6140a204144f93b0c25a6a Node ID: 0ec1f2543ef5e0c9f86d34616130c6fe14480a8e1c9148ef41722bcf Worker IP address: 192.168.102.18 Worker port: 37645 Worker PID: 230966 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Error executing job with overrides: ['data.train_files=data/nq_search/train.parquet', 'data.val_files=data/nq_search/test.parquet', 'data.train_data_num=null', 'data.val_data_num=null', 'data.train_batch_size=128', 'data.val_batch_size=64', 'data.max_prompt_length=4096', 'data.max_response_length=500', 'data.max_start_length=2048', 'data.max_obs_length=500', 'data.shuffle_train_dataloader=True', 'algorithm.adv_estimator=grpo', 'actor_rollout_ref.model.path=/data1/public/hf/meta-llama/Llama-3.2-1B-Instruct', 'actor_rollout_ref.model.enable_gradient_checkpointing=true', 'actor_rollout_ref.model.use_remove_padding=True', 'actor_rollout_ref.actor.optim.lr=1e-6', 'actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.95', 'actor_rollout_ref.actor.use_kl_loss=true', 'actor_rollout_ref.actor.ppo_mini_batch_size=256', 'actor_rollout_ref.actor.ppo_micro_batch_size=64', 'actor_rollout_ref.actor.fsdp_config.param_offload=true', 'actor_rollout_ref.actor.fsdp_config.grad_offload=true', 'actor_rollout_ref.actor.fsdp_config.optimizer_offload=true', 'actor_rollout_ref.rollout.log_prob_micro_batch_size=128', 'actor_rollout_ref.rollout.tensor_model_parallel_size=1', 'actor_rollout_ref.rollout.name=vllm', 'actor_rollout_ref.rollout.gpu_memory_utilization=0.6', 'actor_rollout_ref.ref.log_prob_micro_batch_size=128', 'actor_rollout_ref.ref.fsdp_config.param_offload=True', 'actor_rollout_ref.actor.kl_loss_coef=0.001', 'actor_rollout_ref.actor.kl_loss_type=low_var_kl', 'algorithm.no_think_rl=false', 'actor_rollout_ref.rollout.n_agent=5', 'actor_rollout_ref.rollout.temperature=1', 'actor_rollout_ref.actor.state_masking=true', 'trainer.logger=[console]', '+trainer.val_only=false', '+trainer.val_before_train=false', 'trainer.default_hdfs_dir=null', 'trainer.n_gpus_per_node=2', 'trainer.nnodes=1', 'trainer.save_freq=100', 'trainer.test_freq=50', 'trainer.project_name=Search-R1', 'trainer.experiment_name=reproduce_llama3.2-1b_inst', 'trainer.total_epochs=15', 'trainer.total_training_steps=305', 'trainer.default_hdfs_dir=null', 'trainer.default_local_dir=verl_checkpoints/reproduce_llama3.2-1b_inst', 'max_turns=2', 'retriever.url=http://127.0.0.1:8000/retrieve', 'retriever.topk=3']
Traceback (most recent call last):
  File "/home/jzshen/Search-R1/verl/trainer/main_ppo.py", line 110, in main
    ray.get(main_task.remote(config))
  File "/data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/ray/_private/worker.py", line 2771, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/ray/_private/worker.py", line 919, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ActorDiedError): ray::main_task() (pid=230599, ip=192.168.102.18)
  File "/home/jzshen/Search-R1/verl/trainer/main_ppo.py", line 197, in main_task
    trainer.init_workers()
  File "/home/jzshen/Search-R1/verl/trainer/ppo/ray_trainer.py", line 617, in init_workers
    self.ref_policy_wg.init_model()
  File "/home/jzshen/Search-R1/verl/single_controller/ray/base.py", line 42, in func
    output = ray.get(output)
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
        class_name: create_colocated_worker_cls.<locals>.WorkerDict
        actor_id: e5acd21bed6fbed2047802f301000000
        pid: 230966
        name: h4qiyLWorkerDict_0:0
        namespace: 6f0008a7-80ad-4271-9826-b4d10b357a36
        ip: 192.168.102.18
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
(WorkerDict pid=230966) [rank0]:[E314 14:33:45.215303843 ProcessGroupNCCL.cpp:607] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600051 milliseconds before timing out.
(WorkerDict pid=230966) [rank0]:[E314 14:33:45.215826347 ProcessGroupNCCL.cpp:1664] [PG 0 (default_pg) Rank 0] Exception (either an error or timeout) detected by watchdog at work: 1, last enqueued NCCL work: 1, last completed NCCL work: -1.
(WorkerDict pid=230966) [rank0]:[E314 14:33:45.215835584 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 0] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: -1.
(WorkerDict pid=230966) [rank0]:[E314 14:33:45.215844971 ProcessGroupNCCL.cpp:621] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
(WorkerDict pid=230966) [rank0]:[E314 14:33:45.215849740 ProcessGroupNCCL.cpp:627] [Rank 0] To avoid data inconsistency, we are taking the entire process down.
(WorkerDict pid=230966) [rank0]:[E314 14:33:45.217411580 ProcessGroupNCCL.cpp:1515] [PG 0 (default_pg) Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600051 milliseconds before timing out.
(WorkerDict pid=230966) Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:609 (most recent call first): [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(WorkerDict pid=230966) frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f58706c4f86 in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libc10.so) [repeated 3x across cluster]
(WorkerDict pid=230966) frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7f291fa1b8d2 in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so) [repeated 2x across cluster]
(WorkerDict pid=230966) frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7f291fa246fc in /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so) [repeated 4x across cluster]
(WorkerDict pid=230966) frame #3: <unknown function> + 0x77bd (0x7f58e40707bd in /lib64/libpthread.so.0) [repeated 7x across cluster]
(WorkerDict pid=230966) frame #4: clone + 0x3f (0x7f58e36596bf in /lib64/libc.so.6) [repeated 3x across cluster]
(WorkerDict pid=230966) [2025-03-14 14:33:45,164 E 230966 231591] logging.cc:113: Unhandled exception: N3c1016DistBackendErrorE. what(): [PG 0 (default_pg) Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600051 milliseconds before timing out.
(WorkerDict pid=230966) Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1521 (most recent call first):
(WorkerDict pid=231421) [2025-03-14 14:33:45,136 E 231421 231589] logging.cc:120: Stack trace: 
(WorkerDict pid=231421)  /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/ray/_raylet.so(+0x13aa8ea) [0x7f0ea01138ea] ray::operator<<()
(WorkerDict pid=231421) /data1/jzshen/miniconda3/envs/searchr1/lib/python3.9/site-packages/ray/_raylet.so(+0x13ae022) [0x7f0ea0117022] ray::TerminateHandler()
(WorkerDict pid=231421) /data1/jzshen/miniconda3/envs/searchr1/bin/../lib/libstdc++.so.6(+0xdbbf4) [0x7f0e9ea17bf4] execute_native_thread_routine
(WorkerDict pid=231421) /lib64/libpthread.so.0(+0x77bd) [0x7f0ea7c977bd] start_thread
(WorkerDict pid=231421) /lib64/libc.so.6(clone+0x3f) [0x7f0ea72806bf] clone
(WorkerDict pid=231421) *** SIGABRT received at time=1741934025 on cpu 60 ***
(WorkerDict pid=231421) PC: @     0x7f0ea71c13ba  (unknown)  raise
(WorkerDict pid=231421)     @     0x7f0e9e9ed35a  (unknown)  __cxxabiv1::__terminate() [repeated 2x across cluster]
(WorkerDict pid=231421)     @     0x7f0e9e9ed070  (unknown)  (unknown)
(WorkerDict pid=231421) [2025-03-14 14:33:45,136 E 231421 231589] logging.cc:484: *** SIGABRT received at time=1741934025 on cpu 60 ***
(WorkerDict pid=231421) [2025-03-14 14:33:45,136 E 231421 231589] logging.cc:484: PC: @     0x7f0ea71c13ba  (unknown)  raise
(WorkerDict pid=231421) [2025-03-14 14:33:45,136 E 231421 231589] logging.cc:484:     @     0x7f0e9e9ed35a  (unknown)  __cxxabiv1::__terminate() [repeated 2x across cluster]
(WorkerDict pid=231421) [2025-03-14 14:33:45,137 E 231421 231589] logging.cc:484:     @     0x7f0e9e9ed070  (unknown)  (unknown)
(WorkerDict pid=231421) Fatal Python error: Aborted
```

**Comment by JunzheShen** [comment]
> same question，have no idea how to solve it.

Hi, `export NCCL_P2P_DISABLE=1` works for me

**Comment by WMeng1** [comment]
it seems not work for me. but also thanks for your reply.

> > same question，have no idea how to solve it.
> 
> Hi, `export NCCL_P2P_DISABLE=1` works for me

**Comment by dbcSep03** [comment]
因为batch_size太大，所以超时了，减少批次

**Comment by JiayuJeff** [comment]
> export NCCL_P2P_DISABLE=1

Also works for me, thx

**Comment by Jnnndjjsnxbhhunheng** [comment]
> 因为batch_size太大，所以rollout超时了，减少批次

但是我似乎是在前10-20个batch随机会出现这个情况，有的可以正常rollout

**Comment by Kirrito-k423** [comment]
中文：

从目前日志看，这更像是初始化阶段的 NCCL / rank-to-GPU 映射问题，而不是模型大小打印本身的问题。verl 的 FSDP 初始化会在打印模型大小前执行一次 `torch.distributed.barrier()`（见 `verl/workers/engine/fsdp/transformer_impl.py`），而本 issue 的日志是在 SeqNum=1 的 NCCL ALLREDUCE 上按默认 600s 超时（默认值见 `verl/trainer/config/ppo_trainer.yaml`）。相关的 #1338 也报告了类似“打印 NCCL version 后卡住”的现象，并出现了 PyTorch 关于 GPU 映射可能导致 hang 的 warning：https://github.com/verl-project/verl/issues/1338

已有多个用户反馈 `export NCCL_P2P_DISABLE=1` 对这类问题有效，包括本 issue 作者的回复：https://github.com/verl-project/verl/issues/597#issuecomment-2731472061 以及 #1338 的确认：https://github.com/verl-project/verl/issues/1338#issuecomment-2908719720 。建议先在启动脚本最前面加上：

```bash
export NCCL_P2P_DISABLE=1
export HYDRA_FULL_ERROR=1
export RAY_DEDUP_LOGS=0
export NCCL_DEBUG=INFO
```

如果仍然复现，请补充以下信息，方便判断是不是 Slurm/Ray 的 GPU 绑定、NCCL 拓扑或 batch/rollout 压力问题：verl commit/version、完整 Slurm 启动命令、`ray status`、`nvidia-smi topo -m`、driver/CUDA/NCCL 版本、完整日志，以及设置 `NCCL_P2P_DISABLE=1` 后是否仍卡在同一位置。

English:

From the current logs, this looks more like an NCCL / rank-to-GPU mapping issue during initialization, not a problem with printing the model size itself. In verl's FSDP initialization, `torch.distributed.barrier()` runs immediately before printing the model size (`verl/workers/engine/fsdp/transformer_impl.py`). The log in this issue then times out on the first NCCL ALLREDUCE after the default 600s timeout (`verl/trainer/config/ppo_trainer.yaml`). Related issue #1338 reports a very similar “stuck after NCCL version” symptom and includes a PyTorch warning that an incorrect rank-to-GPU mapping can hang: https://github.com/verl-project/verl/issues/1338

Several users reported that `export NCCL_P2P_DISABLE=1` helps for this class of issue, including the original reporter here: https://github.com/verl-project/verl/issues/597#issuecomment-2731472061 and a confirmation in #1338: https://github.com/verl-project/verl/issues/1338#issuecomment-2908719720 . Please try adding this before launching:

```bash
export NCCL_P2P_DISABLE=1
export HYDRA_FULL_ERROR=1
export RAY_DEDUP_LOGS=0
export NCCL_DEBUG=INFO
```

If it still reproduces, please share the verl commit/version, full Slurm launch command, `ray status`, `nvidia-smi topo -m`, driver/CUDA/NCCL versions, full logs, and whether it still hangs at the same point after setting `NCCL_P2P_DISABLE=1`.

This response was generated by a scheduled Codex GPT5.5 issue processing task.
