### ISSUE TITLE
The GPU memory is not properly released at the end of each step.

### ISSUE THREAD

**Issue by yyDing1** [volcengine/verl#632]
I executed this [this script](https://github.com/agentica-project/deepscaler/blob/main/scripts/train/run_deepscaler_1.5b_8k.sh) within the framework of veRL and discovered that the version of Deepscaler compatible with veRL is operational, whereas the latest iteration of veRL throws an Out Of Memory (OOM) error.

The GPU memory is not properly released at the end of each step, which leads to a OOM error when the VLLM rollout worker is woken up at the beginning of the second step.

DeepScaler veRL (GPU utilization in the beginning of step 2, before `self.actor_rollout_wg.generate_sequences(gen_batch)`):

![Image](https://github.com/user-attachments/assets/747ff41b-ee56-432c-8319-ce7088396f84)

Latest veRL:

![Image](https://github.com/user-attachments/assets/aaa83bd8-4de7-45dd-8e09-28df561d7a1b)

**Comment by yyDing1** [comment]
I find that PR https://github.com/volcengine/verl/pull/556 removes the `torch.cuda.empty_cache()` in `ActorRolloutRefWorker.update_actor()`, which led to this error.

I resolved the issue by adding `torch.cuda.empty_cache()` back.

I'm not clear on the rationale behind its removal. Is it because the `torch.cuda.empty_cache()` operation is time-consuming? @tongyx361 

However, removing it may lead to insufficient GPU memory during the next round of rollout, thereby reducing the efficiency of the rollout, especially when the `gpu_memory_utilization` is set to a relatively high value.

On the other hand, setting a higher `gpu_memory_utilization` can make the rollout process faster. Therefore, I think retaining `torch.cuda.empty_cache()` might be a better approach?

Or perhaps there's a more appropriate way to handle this?

**Comment by PeterSH6** [comment]
@yyDing1 Let me confirm: Both experiment disable `optimizer_offload=False`?

**Comment by yyDing1** [comment]
Yes, both `actor.fsdp_config.param_offload` and `actor.fsdp_config.optimizer_offload` are set to False in these two experiments.

**Comment by PeterSH6** [comment]
And you're using the latest main branch for Figure 2 right? We're not using grad_offload anymore

**Comment by yyDing1** [comment]
Yes, I remove the deprecated arguments, such as `grad_offload `, `val_temperature`, and `n_val`.
Test scripts for the latest verl:
```bash
set -x

# export CUDA_VISIBLE_DEVICES=4,5,6,7
export VLLM_ATTENTION_BACKEND=XFORMERS

math_train_path=/workspace/datasets/math/train.parquet
math_test_path=/workspace/datasets/qwenbench/math500.parquet
aime_test_path=/workspace/datasets/qwenbench/aime24.parquet

train_files="['$math_train_path']"
test_files="['$math_test_path', '$aime_test_path']"

model_path=/workspace/hf_models/Qwen2.5-3B-Instruct

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=128 \
    data.max_prompt_length=1024 \
    data.max_response_length=3072 \
    actor_rollout_ref.model.path=$model_path \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=128 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=64 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.85 \
    actor_rollout_ref.rollout.n=64 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=64 \
    actor_rollout_ref.ref.fsdp_config.param_offload=False \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.logger=['console','wandb'] \
    trainer.project_name='qwen2_5_3b_math' \
    trainer.experiment_name='qwen2_5_3b_math' \
    +trainer.val_before_train=True \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=-1 \
    trainer.test_freq=10 \
    trainer.total_epochs=15 $@
```

**Comment by wuxibin89** [comment]
@yyDing1 Where do you add empty_cache back? We have 2 `torch.empty_cache()` before and after vllm rollout generation.
https://github.com/volcengine/verl/blob/main/verl/workers/sharding_manager/fsdp_vllm.py#L83
https://github.com/volcengine/verl/blob/main/verl/workers/sharding_manager/fsdp_vllm.py#L133

**Comment by yyDing1** [comment]
Oh, sorry, I think I made a mistake. I pulled from a forked repo rather than the latest one. The OOM error has been solved by PR https://github.com/volcengine/verl/pull/575. I apologize for the confusion and truly appreciate your patience and assistance!
